### ISSUE TITLE
Not seeing filetype icons in tree view

### ISSUE THREAD

**Issue by rjv** [silvestreh/atom-material-ui#10]
Based on the screenshot in the readme, I would expect to see customized file icons in the tree view, but that doesn't seem to be the case for me. I'm using both the Atom Material UI and syntax themes. Is this a configuration I'm missing somewhere?

![screenshot at 100523](https://cloud.githubusercontent.com/assets/532439/8331868/95cd41e8-1a58-11e5-9741-e448fc336908.png)

I'm using Windows 7 Professional and Atom 0.211.0.

**Comment by silvestreh** [comment]
That's odd… I had a similar issue yesterday and the guy wasn't using the [File icons](https://atom.io/packages/file-icons) package. Atom.io doesn't ship with the package.

**Comment by rjv** [comment]
That makes sense. I guess the screenshot was misleading - it made me assume that the UI theme shipped with the icon set. Thanks!

**Comment by silvestreh** [comment]
Heh… I should probably update the screenshot without the file icons (or add a small paragraph to the README file recommending the package)
