### ISSUE TITLE
Broken scollbar

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#100]
Funny scrollbar jitter with `0.6.2` update. 

Windows 10
Atom `1.0.19`

Reproduced when switching to Atom Material UI theme, and then closing and opening atom or switching to a different tab. Example below:

![scrollbar](https://cloud.githubusercontent.com/assets/8268040/10254070/b93b554c-6941-11e5-875c-cf46a174745d.gif)

**Comment by WoodyWoodsta** [comment]
Just tried another theme and it actually does not appear to be Atom Material UI specific

**Comment by silvestreh** [comment]
So it's actually not related to the theme then?

**Comment by WoodyWoodsta** [comment]
Nope! Apologies!
