### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by michaeldeboeve** [silvestreh/atom-material-ui#101]
Are there any plans for a custom color option?
I have now overridden the colors in my user stylesheets, but a custom color setting would be nice.

**Comment by silvestreh** [comment]
Yes, this is a feature that has been requested before. I like the idea, but there's no roadmap… so sometime in the future we'll have that option!

**Comment by silvestreh** [comment]
This is implemented in the `rewrite` branch. Not ETA for the release. Soon™
