### ISSUE TITLE
Add visual indication of which pane are you on

### ISSUE THREAD

**Issue by chamini2** [silvestreh/atom-material-ui#103]
I have enabled the following setting:

    core:
      destroyEmptyPanes: false

In my `config.cson`

When I'm moving between empty panes there's no way to now on which I'm actually standing, could there be more indication of the selected pane?

**Comment by silvestreh** [comment]
You want to (for example) visualize the focus state on tree-view or search/replace panes?

**Comment by chamini2** [comment]
No, on panes, with that setting, there's the option to create empty panes, so there's no cursor to actually show where we are focused.

For example, in this window I have the focus on one of the two empty panes, but don't know on which one:

<img width="952" alt="screen shot 2015-10-10 at 9 26 15 pm" src="https://cloud.githubusercontent.com/assets/2745502/10414281/a57c232e-6f95-11e5-9de0-c7a090b38a73.png">
