### ISSUE TITLE
Drop down menu position seem weird

### ISSUE THREAD

**Issue by binarykiss** [silvestreh/atom-material-ui#107]
The UI is great except for drop down menu. It is not in the right position. Please fix it.

![screenshot from 2015-10-25 00-17-19](https://cloud.githubusercontent.com/assets/8669672/10711705/23e6bd32-7aae-11e5-8a13-3bcc951a2ce6.png)

**Comment by silvestreh** [comment]
Is this on Windows? Linux? I know it's not OS X 'cause you can't style `select`'s `option`s. Which other packages (if any) do you have installed?

**Comment by binarykiss** [comment]
OK, I just double-checked it and found out that the other default UI like "One Dark" have this problem too. Unmaximize and then maximize the window fix it, but the problem may occur randomly again.

Anyway, if you're still curious, here's what I have.
- OS: Ubuntu 15.10
- Packages installed: atom-beautify, language-haskell, minimap, minimap-find-and-replace, minimap-git-diff, minimap-highlight-selected, minimap-selection, todo-show (all are up-to-date)

**Comment by silvestreh** [comment]
Possibly related to atom/atom#6622.
