### ISSUE TITLE
Close icon for modified tabs is blue on hover

### ISSUE THREAD

**Issue by demrks** [silvestreh/atom-material-ui#108]
Title pretty much sums it up, attached is a screenshot. Personally I think the icon should be white/grey like everywhere else.

<img width="694" alt="screen shot 2015-10-30 at 23 07 58" src="https://cloud.githubusercontent.com/assets/5760429/10859167/33ac5fc2-7f5b-11e5-8eeb-44c7c0c7fdaf.png">

**Comment by silvestreh** [comment]
No, this is correct. It reflects the status of the file. Though I understand the contrast against the background could use some love.

**Comment by demrks** [comment]
Ok, I was just wondering about the blue color, because it's not used anywhere else as far as I can tell. Probably use the accent color instead (in my case "teal")? That might also increase the contrast a little...

**Comment by silvestreh** [comment]
Oh, right… I hardly noticed that. Thanks.
