### ISSUE TITLE
Change atom notifications styling to match material design guidelines

### ISSUE THREAD

**Issue by demrks** [silvestreh/atom-material-ui#109]
The atom notifications currently don't really match the overall material design styling of this theme (see screenshot). A slightly changed version of the Material Design Snackbars (https://www.google.com/design/spec/components/snackbars-toasts.html#) would probably work better?

<img width="464" alt="screen shot 2015-10-30 at 23 23 38" src="https://cloud.githubusercontent.com/assets/5760429/10859492/2f5c03b6-7f5e-11e5-9c99-c023f4af60ac.png">

**Comment by silvestreh** [comment]
I could bring them closer to the spec, but given how much info Atom's notifications have, it will be imposible to match it.

**Comment by demrks** [comment]
True, the snackbar examples are much more simple. But as far as I know, only the error messages have that much text. To bring them closer to spec, it's probably enough to just use one background color instead of shades of one color.

**Comment by silvestreh** [comment]
Not exactly MD compliant, but at least is closer.

![captura de pantalla 2015-11-02 a las 19 57 34](https://cloud.githubusercontent.com/assets/1133339/10896957/fef030cc-819b-11e5-9001-2992354081c3.png)

After reading through the toasts section of the spec, we shouldn't even be able to stack notifications on top of another, so yeah, there's no way we can make them follow the guidelines.

I'm mostly posting the screenshot to get feedback, but I'll push this change to the repository anyway.

**Comment by demrks** [comment]
Good stuff, looks good to me. I would probably add a tiny `border-radius` to be a little closer to the spec and get rid of the little darker line in the error message (right under "Oh shit. Something broke"). Just to make sure that these already big atom error notifications don't get even bigger, personal opinion though.

**Comment by silvestreh** [comment]
Just pushed the update to APM. Thanks!

**Comment by demrks** [comment]
Thanks, I just checked by trying to compile a invalid .less file. I think the grey `background-color` in the following screenshot looks a little bit off. Not quite sure if this is intended or needed,  you can probably just get rid of the `atom-notification .detail` background.

<img width="488" alt="screen shot 2015-11-03 at 00 30 24" src="https://cloud.githubusercontent.com/assets/5760429/10897632/5ae0b128-81c3-11e5-9b48-0500002019aa.png">

Also the red `background-color` of `atom-notification.error code` doesn't match the color of the thin red line on the left side anymore. Doesn't have to be changed though or changed to any color, whatever you prefer, just mentioning.

**Comment by silvestreh** [comment]
I'll look into it!
