### ISSUE TITLE
Make the UI theme compatible with light syntax themes

### ISSUE THREAD

**Issue by silvestreh** [silvestreh/atom-material-ui#11]
The user interface should be readable and usable with light syntax themes. Especially those shipped with Atom:

- Atom Light
- Base16 Tomorrow Light
- Solarized Light
- One Light

**Comment by silvestreh** [comment]
Seems to be mostly fine now, but needs more testing… anyone using a light theme please create a new issue if you find something off.

**Comment by douglasmfreitas** [comment]
In light themes the subtitles of the readmes are white, and pretty hard to see.
![atom-material-ui](https://cloud.githubusercontent.com/assets/7896844/8956720/064128b8-35cf-11e5-903f-c19f355a7255.png)

It's not related to this, but when i move the tabs sometimes these white borders appear, but on light themes its hard to notice.
![atom-material-ui-moving](https://cloud.githubusercontent.com/assets/7896844/8956865/3889f452-35d0-11e5-93b1-ce1a3c61acdc.png)

Also, my monitor have low contrast and it's very hard to see these kind of toggles, the scrollbar and the selected text, and its harder on light themes. But I managed changed the color of some of them to the accent color. I think it would be very cool to have some option to use the accent color on more things.
![atom-material-ui-find](https://cloud.githubusercontent.com/assets/7896844/8956719/063f1140-35cf-11e5-9e1a-7eb09aa63452.png)

And thank you for the great UI theme.

**Comment by cobrabr** [comment]
I have a similar problem -- I'm using the [Grandson Of Obsidian](https://atom.io/themes/grandson-of-obsidian) Syntax theme (which is a dark theme), but for some reason, Atom Material UI thinks it's a light theme, so it colors the rest of the UI just like @douglasmfreitas's screenshot shows.

What's the exact configuration in the Syntax theme that Atom Material UI uses to determine whether the theme is light or dark?

**Comment by silvestreh** [comment]
@cobrabr Grandson of Obsidian is an outdated syntax theme. It uses some deprecated classes and that's probably the issue here. There's not much I can do about it.

**Comment by cobrabr** [comment]
Yeah, I noticed it after I posted my comment. Thanks for looking into it, anyway. :)

**Comment by nyc** [comment]
The command palette also highlights letters matching a search in white font, making them impossible to read.

![white-font-screenshot](https://cloud.githubusercontent.com/assets/1140436/8977901/1b737cd0-3652-11e5-95bc-5bddc9bc45c4.png)

**Comment by nyc** [comment]
It also makes the wrap guide invisible. For example, using the Atom Light UI theme and the Atom Light syntax theme, you can see the wrap guide:

![screen shot 2015-07-30 at 12 38 45 am](https://cloud.githubusercontent.com/assets/1140436/8978037/5c5446d4-3653-11e5-8bad-e18510a5fc53.png)

But it's not there with the Atom Material UI theme:

![screen shot 2015-07-30 at 12 38 22 am](https://cloud.githubusercontent.com/assets/1140436/8978039/5e81e9b6-3653-11e5-9d20-3ea3ea10cd5d.png)
