### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by demrks** [silvestreh/atom-material-ui#110]
Although I use teal as my accent color, some buttons and text labels are still showing a blue color.

1) In the "Update" section the "Update all" button and the text in the bottom right corner are blueish. I guess they should be teal in my case.
 
![screen-shot-2015-11-02-at-10 36 40](https://cloud.githubusercontent.com/assets/5760429/10878669/83f3ffbc-814f-11e5-9997-9edc019be29a.jpg)

The class name for the text in the bottom right corner is `.text-info.`. The button uses the following class names:

![screen shot 2015-11-02 at 10 41 17](https://cloud.githubusercontent.com/assets/5760429/10878727/f055f354-814f-11e5-9c0c-97ff9db4d8ca.png)

2) In the autocomplete box (e.g. CSS autocomplete) there is a description of the property with a blue "More" link to the Mozilla Developer page. The class name is `autocomplete-suggestion-list.select-list.popover-list .suggestion-description-more-link`.

![screen shot 2015-11-02 at 10 45 06](https://cloud.githubusercontent.com/assets/5760429/10878796/51eb9060-8150-11e5-94c7-8c9098acd0a4.png)

3) If there are no open files, Atom shows some background tips. These are very hard to read, not sure if this is intended.

![screen shot 2015-11-02 at 10 43 33](https://cloud.githubusercontent.com/assets/5760429/10878853/b6d4edd2-8150-11e5-8ae3-93db7ea7e650.png)

![screen shot 2015-11-02 at 11 00 11](https://cloud.githubusercontent.com/assets/5760429/10878885/f33b5220-8150-11e5-8c27-ea11eeddd555.png)

**Comment by DaveBlooman** [comment]
Also getting some odd colour clashes

![screenshot 2015-11-02 15 43 13](https://cloud.githubusercontent.com/assets/1492067/10886117/7dec896c-8178-11e5-84fa-21a16be9effa.png)

**Comment by silvestreh** [comment]
@DaveBlooman how do you get to that screen?

**Comment by DaveBlooman** [comment]
That is the release notes page

**Comment by silvestreh** [comment]
That's odd… mine looks OK.

![captura de pantalla 2015-11-02 a las 13 19 13](https://cloud.githubusercontent.com/assets/1133339/10887150/55ee5918-8164-11e5-98d4-3a959242d4c4.png)

Which other packages are you using?

**Comment by DaveBlooman** [comment]
Fruits syntax seems to be the culpret

**Comment by demrks** [comment]
I just had to update another package and noticed that the "Update All" button is still blue and not the accent color. Is this just me? (I already updated the material UI theme to the latest version and restarted atom)

![screen shot 2015-11-03 at 09 47 57](https://cloud.githubusercontent.com/assets/5760429/10933973/dd68d71e-82dc-11e5-8183-889919b9d3fc.png)

**Comment by silvestreh** [comment]
@demrks which accent color are you using? The update buttons looks like Cyan.

**Comment by demrks** [comment]
@silvestreh I'm using the teal accent color, which looks similar to this cyan/blue color, but is not quite the same.

<img width="215" alt="screen shot 2015-11-05 at 19 14 51" src="https://cloud.githubusercontent.com/assets/5760429/10977555/077deeb6-83f2-11e5-8567-9af6bec784b6.png">

**Comment by silvestreh** [comment]
Ok, I *think* I found the problem. I'll push it as soon as I have updates to install so I can test it :grin:

**Comment by silvestreh** [comment]
@demrks Should be good now!

**Comment by demrks** [comment]
@silvestreh  Thanks, looks good
