### ISSUE TITLE
Add ripple-effect to tabs depending on click coordination 

### ISSUE THREAD

**Issue by dkerzig** [silvestreh/atom-material-ui#111]
It would feel much more natural to me if the ripple effect (which is quite beautiful btw) displayed on the tabs when I click on them is considering the coordinates where I've clicked and starts there to animate.

From the Material Design Guidelines: https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input
Ripple Effect created with SVG by Codrops: http://tympanus.net/Tutorials/SVGRipples/

**Comment by silvestreh** [comment]
I thought about it, but I didn't want to add logic (as in programming) to the ripple effect. Given that Atom isn't exactly a fast editor, I want to keep it as light as possible.

**Comment by dkerzig** [comment]
Ok I see your point but
1) Have you measured anything about that? I think with a clever technique like the SVG-Animation everything would still be as slick as possible. I know websites with houndreds of these animations and they are still very performant. (And in Atom we only display one animation a time, thats like nothing)
2) You could make it optional via the settings
3) It's in the Google Design Guidelines which feel mandatory for me for an "Material-UI"

**Comment by silvestreh** [comment]
Just pushed an update, `0.7.2`, with this feature. It's enabled by default.

**Comment by dkerzig** [comment]
+999 Kudos
Thank you so much, feels great!
