### ISSUE TITLE
UI Font Size of Material UI  

### ISSUE THREAD

**Issue by abrar2741** [silvestreh/atom-material-ui#112]
The UI is awesome. Please provide something between 'Regular' and 'Big'. May be 'Large' or something like that. It's causing a small problem which you can see it in the screenshot below.

![fix](https://cloud.githubusercontent.com/assets/15705845/11016109/d3f7aff8-859c-11e5-8fae-1e994d47e8dc.png)

**Comment by silvestreh** [comment]
Fixed in `rewrite` branch. No ETA for release yet. Soon™
