### ISSUE TITLE
Grouped Settings not writing to config correctly

### ISSUE THREAD

**Issue by dotJoel** [silvestreh/atom-material-ui#115]
Observed when trying to find out where my tab icons went..

Changing the value of `showTabIcons` does not write it within the `tabs` object in `config.cson`.

**Comment by silvestreh** [comment]
It does for me. Did you delete all previous settings from your `config.cson`. Maybe there's some old stuff in there conflicting with the new.

**Comment by dotJoel** [comment]
No, I didn't delete anything myself.
When I updated the package, it did seem to make me click "Install" after it downloaded/tried.
One of the other settings was correctly in the tabs section.. `rippleAccentColor` but I probably toggled that a couple of times.
I did watch it write a new value to `showTabIcons` to the wrong place.

I can probably test a little more thoroughly tomorrow.

**Comment by silvestreh** [comment]
That's odd… but, is the option even working? Can you see the icons in your tabs or is it totally broken?

**Comment by dotJoel** [comment]
It worked after I inspected the config file and moved the setting within `tabs`.

**Comment by silvestreh** [comment]
I should probably add a flag to reset the settings for the next update which will break everything. :grin:

**Comment by silvestreh** [comment]
I fixed this in the `rewrite` branch. No ETA for the new release though.
