### ISSUE TITLE
Custom icons for files in the sidebar 

### ISSUE THREAD

**Issue by mayankchd** [silvestreh/atom-material-ui#117]
[Material theme](https://github.com/equinusocio/material-theme) for sublime has custom icons depending on the file type .

**Comment by diagramatics** [comment]
We recommend people to use other custom icon packages like [file-icons](https://atom.io/packages/file-icons). The theme is compatible with them. :)

**Comment by mayankchd** [comment]
Thanks , didn't know about that!
