### ISSUE TITLE
Incompatible Packages Panel

### ISSUE THREAD

**Issue by lexcast** [silvestreh/atom-material-ui#118]
I just saw that the incompatible packages panel has no style. Or at least seems weird to me.

![screenshot from 2015-11-16 00-12-38](https://cloud.githubusercontent.com/assets/10590799/11175358/06885340-8bf7-11e5-82ae-e11d715c1029.png)

**Comment by silvestreh** [comment]
This is interesting. Which package is triggering it?

**Comment by lexcast** [comment]
The package is [git-blame](https://github.com/alexcorre/git-blame).
This panel shows up when Atom is updated and a package needs to be rebuild.

**Comment by silvestreh** [comment]
Can't even install it :( … I'll see if I can trigger it some other way.

**Comment by lexcast** [comment]
Maybe downgrading Atom to version 1.0, installing the git-blame package and then upgrading Atom and the panel will be able to be opened.

**Comment by silvestreh** [comment]
I'm closing this one because development efforts are focused on the next version of the theme.

**Comment by lexcast** [comment]
I think this should be re opened as the new version was released and the issue persists.
![incompatible](https://cloud.githubusercontent.com/assets/10590799/13690249/70e6a270-e6f4-11e5-9246-113c71228be4.png)

**Comment by lexcast** [comment]
To get this panel try this:
* Install git-blame package
* Use "Aplication: Open Dev" command to open any project
* Click on the little bug icon

**Comment by silvestreh** [comment]
This is what I'm getting

![captura de pantalla 2016-03-11 a las 12 17 14](https://cloud.githubusercontent.com/assets/1133339/13706315/518eb7b6-e783-11e5-859c-89878697d143.png)

There's no bug icon :( I installed `git-blame` using latest stable Atom and then opened the latest beta.

**Comment by lexcast** [comment]
That message looks different for me.
So I'm thinking that is only me. I've commented everything in my style.less so the problem should be in one of my installed packages.
I'll try to find it.

**Comment by silvestreh** [comment]
I actually made a couple changes to make it look that way… for example, alerts where only styled inside `settings-view`, now they should be styled everywhere. I also added the usual `3rem` padding to the incompatible packages view.

I just pushed those changes to the repository, you can try them right away if you clone this repository and then link it…

```shell
git clone git@github.com:silvestreh/atom-material-ui.git
cd atom-material-ui/
apm install
apm link -d # this way you'll use the repo version only when Atom runs in dev mode
atom -d /path/to/some/project
```

**Comment by lexcast** [comment]
Yes, now the alert looks fine.
But the other panels don't.
![incompatible2](https://cloud.githubusercontent.com/assets/10590799/13708412/1d13393a-e774-11e5-94c4-53d967b66aaa.png)
But I don't know how to trigger those build errors :disappointed:

**Comment by silvestreh** [comment]
I managed to  get it… I removed `~/.atom/packages/git-blame/node_modules/pathwatcher/build`. Hang in there, I'll fix it real soon.

**Comment by silvestreh** [comment]
Finally done! 1.2.4 should fix this for you :smile:

**Comment by silvestreh** [comment]
Arrrghhh… double update. Sorry, I missed some things while doing this.
