### ISSUE TITLE
Add More Material?

### ISSUE THREAD

**Issue by JamesCoyle** [silvestreh/atom-material-ui#119]
Other than the animation, cardlike UI elements, and the Roboto font, this theme doesn't look at all material design in my opinion. What would really help is to make the tab bar look more like the material design toolbar. Elements also need to be sized according to material standards. 

Here is something to show what I mean. This is the [Metro](https://atom.io/themes/metro-ui) theme I've been trying out recently:

![image](https://cloud.githubusercontent.com/assets/10384436/11223530/4c0b3b9a-8d68-11e5-990b-9359d9655b94.png)

In my opinion, this looks much more material design than the actual material design theme. You can even set an accent color just like any material design app has:

![image](https://cloud.githubusercontent.com/assets/10384436/11223092/0b7ba56c-8d66-11e5-8e49-52c1a4054b76.png)

As you can see, the tab bar and first project folder in the tree view are all nicely aligned and themeable (currently set to my windows 10 theme color which is an awesome feature of that skin). The skin even detects I have the atom [tool-bar](https://atom.io/packages/tool-bar) package installed and adds the first icon of that to the themed bar when the toolbar is docked to the left or right. 

I feel that the material theme should at least be doing something similar.

**Comment by JamesCoyle** [comment]
I'll see what I can do but I'm pretty busy at the moment. Need a few things to add to my Github though so might be a fun thing to work on. I take it that it's just CSS styling?

**Comment by silvestreh** [comment]
While it would look nice, the colored application title bar (the window manager) would only work for Windows 10. I can probably get behind a tinted tab bar that matches the selected accent color.

And no, Metro UI is not "more material design", it's awesome, yes, but it follows the Metro UI guidelines which are different from those of Material :wink: 

I understand this theme, `atom-material-ui`, doesn't follow every rule in the spec, but in most cases that's because those rules wouldn't exactly benefit the UX for a text editor (tabs with big icons on top of text, and uppercase text comes to mind).

It has room for improvement indeed, the main headache right now is that it inherited all the baggage from the old Atom Dark UI theme and we have *heavy* CSS selectors. White space and element size do need a revision, true. There's a lot to do and little free time to do it.

> I tend to use a tab width of 2 but you seem to be using 4. Do you know if there is a way to set it for just this project at all?

Please use 4 spaces if you plan to contribute. You can take a look at [EditorConfig](http://editorconfig.org/), I believe there's an Atom package to easily create a config file for it.

**Comment by JamesCoyle** [comment]
Yes I know metro ui isn't actually material design but it illustrates the point that better sizing and consistency look better. I was thinking of allowing the user to choose between the accent color on the tab bar and how it is currently so users that prefer the current look rather than bold and colorful can still have that option. 

Another option for spacing would also be needed as the baseline for the UI scale. Something which switches the icon scale between 16, 24, and 32 pixels and then sizes the UI to be compact, average, or spacious based on that (similar to how it currently works). As you said the user experience is important when it comes to a text editor and this option gives the user control over the ratio of whitespace and content.

It really just comes down to the fact it still looks a lot like the stock atom theme in most aspects. I'll create a branch and see what I can do with it. What is the correct way to enable the working copy as a theme in atom so changes can be viewed? I'm pretty sure I read somewhere the correct way to do it but can't seem to find it in the atom docs.

**Comment by JamesCoyle** [comment]
> Please use 4 spaces if you plan to contribute. You can take a look at EditorConfig, I believe there's an Atom package to easily create a config file for it.

Ah perfect! I've created an editor config file in my local fork and have created a pull request to merge that config if you wish to do so.

**Comment by silvestreh** [comment]
> What is the correct way to enable the working copy as a theme in atom so changes can be viewed?

Uninstall the theme first, then `cd` into your forked repo and run `npm link` in a terminal. 

I'll check your PR :smiley:

**Comment by silvestreh** [comment]
Here's what I've come up with so far. But… this is on an orphan branch I started from scratch. Right now it doesn't have any settings, all colors are picked up from the syntax theme.

#### With Atom Material Light syntax theme
![captura de pantalla 2015-11-19 a las 22 40 34](https://cloud.githubusercontent.com/assets/1133339/11289776/a1524b28-8f0e-11e5-943c-f380347814e5.png)

#### With One Dark syntax theme
![captura de pantalla 2015-11-19 a las 22 43 37](https://cloud.githubusercontent.com/assets/1133339/11289822/297fa1c6-8f0f-11e5-8d1c-a4af44cc42df.png)

The size for tabs and tree-view items follow the spec a little closer. And that's pretty much everything I did for today.

**Comment by JamesCoyle** [comment]
Wow that looks so much better! Great work. :) 

Is there a way I can contribute to that? Would love to give it a try and see if I can lend a hand with the settings. I'm still pretty new to github so still figuring things out. I'd assume I can view your branch and clone it to desktop? Or do I need to fork it?

**Comment by silvestreh** [comment]
@JamesCoyle sure. Open a terminal and do…

    git remote add silvestreh git@github.com:silvestreh/atom-material-ui.git
    git fetch silvestreh
    git checkout rewrite

Do your edits and then

    git add -A
    git commit -m "some commit message"
    git push origin rewrite

And, after all of that, create a pull request so I can check what you did.

**Comment by silvestreh** [comment]
@JamesCoyle I don't want to introduce settings (like choosing accent color, or use Roboto font, etc) right now. We can add those later on. What I want to focus on is making it look half decent to replace the current codebase in the near future (that would be the `master` branch)

**Comment by JamesCoyle** [comment]
I assume I'm being an idiot but I can

**Comment by silvestreh** [comment]
I'm closing this as it's not really a bug and most of these concepts are being developed in a different branch.

**Comment by equinusocio** [comment]
@silvestreh Remember that in a text editor the main focus must be the code, not the tabs. Using the accent color for the tab bar put it to a "I'm the queen" state.

**Comment by JamesCoyle** [comment]
As always the UI will be configurable by the user such as whether to apply the accent color to the background of the bar.  It may be a text editor but other aspects of the user experience also matter. An important part of that is consistent spacing of UI elements which  a major part of the new branch.

**Comment by silvestreh** [comment]
@equinusocio yeah, you can click a couple checkboxes to make it look closer to the way it is now. Here's a screenshot of that:

![captura de pantalla 2015-11-24 a las 22 38 56](https://cloud.githubusercontent.com/assets/1133339/11385927/5120dbf0-92fc-11e5-99fa-ac1f1867bc01.png)

The first icon in the tool-bar is colored that way so it will blend with the tab bar… kind of like the toolbar widget from Android.

![captura de pantalla 2015-11-24 a las 22 42 13](https://cloud.githubusercontent.com/assets/1133339/11386029/a61a5474-92fc-11e5-93b3-4a33bd8f39fd.png)


These are the settings (so far):

![captura de pantalla 2015-11-24 a las 22 44 02](https://cloud.githubusercontent.com/assets/1133339/11386077/f544027a-92fc-11e5-8825-f5cc35586f51.png)

**Comment by equinusocio** [comment]
Have you tried to make "accent" only the tab bar and not the project heading and the left action bar?

**Comment by silvestreh** [comment]
@equinusocio 

> Have you tried to make "accent" only the tab bar and not the project heading and the left action bar?

Nope, didn't try that… yet :grin:. Like I said, I wanted to blend those together so it would look kinda like the Android ActionBar component, but I could add an option to behave the way you're suggesting. 

> PS: remember the elevation, tab bar, sidebar and editor shouldn't have the same elevation level (shadow) 

They don't have the same elevation, that's why they can cast shadows.

    tabs:         -------
    code:         -----------------
    tree-view:    -------------------------------
    tool-bar:     -------------------------------------------

The shadow is the same size because the distance between layers is the same. Though technically the tab bar should cast a bigger shadow on the `tree-view` since it's two layers up.

**Comment by silvestreh** [comment]
@equinusocio Here's the "waterfall" effect I was referring to: https://www.google.com/design/spec/components/toolbars.html#toolbars-usage
