### ISSUE TITLE
Folders disappear and/or overlap in a multi-folder project

### ISSUE THREAD

**Issue by MrASaint** [silvestreh/atom-material-ui#130]
This bug occurred after the 1.0.0 update. I'm not sure if it's connected to #129.

To recreate this issue add several project folders to the tree view and you'll see that the folders become overlapped, and then disappear completely when collapsed.

### Config

```cson
"atom-material-ui":
  ui:
    animations: false
    panelContrast: true
  tabs: {}
  treeView:
    compactList: true
  fonts: {}
```

### Installed Packages

advanced-open-file@0.13.0
aligner@0.17.3
aligner-php@1.0.0
aligner-scss@1.1.0
atom-autocomplete-php@0.18.1
atom-material-syntax@0.2.6
atom-material-syntax-light@0.0.4
atom-material-ui@1.0.1
atom-wordpress@0.3.0
docblockr@0.7.3
editorconfig@1.2.2
emmet@2.3.15
file-icons@1.6.13
highlight-selected@0.11.1
indent-guide-improved@1.4.4
less-than-slash@0.11.1
linter@1.11.3
linter-jscs@3.2.0
linter-jshint@1.2.1
linter-phpcs@1.3.0
minimap@4.16.2
minimap-highlight-selected@4.3.1
minimap-linter@1.0.0
minimap-pigments@0.1.7
open-recent@4.0.1
open-terminal-here@2.1.2
pigments@0.19.1
project-manager@2.6.5
react@0.12.10
remote-sync@3.5.0
todo-show@1.0.1
turbo-javascript@1.2.0

**Comment by silvestreh** [comment]
Just pushed an update for #128 (which was the same as #129)
