### ISSUE TITLE
Revert to previous version

### ISSUE THREAD

**Issue by mradzinski** [silvestreh/atom-material-ui#131]
New version simply blew up our whole team Atom configuration. Not even the Treeview is working any more... nor even other packages like terminal-plus. Maybe it's time to start thinking about reverting all the changes you did in the last version,

**Comment by silvestreh** [comment]
I don't think that's going to happen soon. I'm still ironing out some issues. Please report whatever bug you encounter.

**Comment by nikolowry** [comment]
+1.

If you want to do extensive theming you might want to consider making additional "supporting" packages for the components that attempt to do drastic UI changes. 

The base theme should be un-opinionated - to a point - and really only leave a minimal footprint, this will ensure you're always inline with upstream development as well.

Noticeably "broken" to me:
- Tree View (only shows selected project with no direction on how to switch projects. I am not going to be using the colored headerbar, so it's disappointing to lose normal functionality for aesthetic reasons)
- Tree View project folder title is all uppercase (with no option to disable). Throws me off as namespacing my dirs happens in a very particular manner.
- Packages that use the Bottom Panel are now broken (terminal-plus)

-----

Really appreciate the hard work!

**Comment by m19** [comment]
The new version broke my terminal-plus package too.

**Comment by silvestreh** [comment]
@nikolowry I like the idea of separate packages for extra functionality.

@m19 I don't know exactly what you use terminal-plus for, but it's working for me.

![captura de pantalla 2015-12-01 a las 0 21 19](https://cloud.githubusercontent.com/assets/1133339/11491523/778d0858-97c1-11e5-9c19-49f31bcd24e2.png)

**Comment by mradzinski** [comment]
Terminal-plus issue might only occur on a Windows environment... Can anyone else experiencing this kind of issue confirm if it's using Windows or Mac? I tested it on my Mac as well and weirdly enough it seems to be working. On the other hand, my treeview blew up on a much weirder way: I can't click on it without Atom crashing (no logs, nothing, it just crashes). It started to happen immediately after the update, so I guess it may have something to do with it. I'll try debugging it and see if I can come up with a reason for this behaviour.

**Comment by m19** [comment]
<img width="926" alt="screen shot 2015-12-01 at 11 59 51" src="https://cloud.githubusercontent.com/assets/1519821/11492060/1059063e-9823-11e5-8d5c-1d6fb4d48c0f.png">

@silvestreh 
I disabled all packages except terminal-plus and this is how it looks for me. I'll try to debug and see if the issue is with the terminal-plus package or this theme. It works fine with the default atom themes though.

**Comment by silvestreh** [comment]
If you want to downgrade to the previous version do this:

    apm uninstall atom-material-ui
    apm install atom-material-ui@0.8.0

**Comment by m19** [comment]
Reverting back to the previous version fixed my terminal-plus problem.

**Comment by mradzinski** [comment]
Here as well, reverting to 0.8.0 fixed everything, even the treeview issue, so I guess it's safe to say the update was causing it.

**Comment by silvestreh** [comment]
The latest, 1.0.x, was unpublished. I still would like to ask for help testing it further. If anyone has time or is willing to help out clone this repo and link it.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui/
    apm link

**Comment by nikolowry** [comment]
I was setting up a new computer (in which I installed the latest) and pinpointed the cause of this bug - when "use animations" is disabled, it will cause some nasty side effects on other plugins that most likely are dependent on some listener based on transition/animation timing they programmed for.

**Comment by silvestreh** [comment]
Would you mind opening a new issue for this?

**Comment by BlockBrother** [comment]
Install Atom from .deb file on atom.io version 1.60.0

Reinstalling the atom via snap and disabling all packages did not fix this problem for me.

**Success installing via .deb file!!**
