### ISSUE TITLE
Settings menu background color bug

### ISSUE THREAD

**Issue by chenmnkken** [silvestreh/atom-material-ui#132]
This is bug screenshot. 
![43d6bfee-cb7b-4a17-b1f6-c7b9eba72707](https://cloud.githubusercontent.com/assets/1049101/11490968/726f9852-9818-11e5-9664-02e4435a7ae4.png)

**Comment by silvestreh** [comment]
I've seen this, but I haven't been able to reproduce it consistently. I'm not sure what could be causing it.

**Comment by DuckThom** [comment]
I'm having this issue as well.
The highlight has the right size during the clicking animation but after the animation ends the background color will be 50% of the height of the button.

OS: Arch Linux
WM: Gnome shell
Retina Macbook 13"
Resolution 2560x1600 (Scaling is set to 2, that \*may\* be causing the 1/2 height background color?)

**Comment by silvestreh** [comment]
Yes, it's been fixed in the development version. 1.0.x was unpublished and 0.8.0 is the latest version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!
