### ISSUE TITLE
Tabs no longer show when file has changes

### ISSUE THREAD

**Issue by anisylen** [silvestreh/atom-material-ui#135]
The filenames in the tab bar were usually colored differently depending on the diff state. If it was a new file, it was green and if it was yellow, it was a changed file.

The new update does not have this and it makes it more difficult to know what file you were just working on.

**Comment by Fequois** [comment]
I don't want to speak for @silvestreh but he rewrote the entire theme from scratch so it wouldn't have been possible to implement on a "component-by-component" basis. At least not easily enough to make it worth it for a free, open source text editor theme.

The soonest you'll see this fixed is if you do it and make a PR.

**Comment by anisylen** [comment]
Yeah, my comment at the end there did seem a little pompous and I have removed them. Dude probably has enough work as it is writing the whole thing from scratch.

Apparently, this was a spinoff of Atom-Dark theme and the 1.0.0 versions needed to be written from scratch.

**Comment by silvestreh** [comment]
@anisylen yes, the files are still colored. Folders with modified files inside are not. That's something I forgot about!

**Comment by anisylen** [comment]
Actually I'm sorry I didn't mention this in the title but I meant the file colors in the TAB bar. Normally the files that have changed are also highlighted in the tab bar with a yellow color and green if new.

**Comment by silvestreh** [comment]
@anisylen I don't think this theme ever changed the text color in tabs. Are you sure that wasn't another package?

The only "modified" status indicator is a circle that appears where the close icon is.

![captura de pantalla 2015-12-09 a las 15 11 39](https://cloud.githubusercontent.com/assets/1133339/11694131/304dd504-9e87-11e5-88fc-fdbf2dd4ccdd.png)

The file's git status was never displayed in the tab bar.

**Comment by silvestreh** [comment]
Ooooooo… I think I know what you mean. There's a setting in the tabs package to enable this funcionality :smile: 

Will fix it ASAP. Thanks!!

**Comment by silvestreh** [comment]
Would this work for you?

![captura de pantalla 2015-12-09 a las 15 23 36](https://cloud.githubusercontent.com/assets/1133339/11694443/e227925a-9e88-11e5-8951-c17faeff6808.png)

I tried coloring the text, but if someone's using a yellow-ish tab bar they wouldn't be able to read the file name. Same thing would happen with the colored circle, but at least they would still be able to read the file name.

**Comment by anisylen** [comment]
Hmm, the color of the name changing and not going well with the background seems to be a common problem. I switched to native-ui recently and the tabs look downright ugly when there are git changes. A circle indicator is a great idea.

**Comment by silvestreh** [comment]
@anisylen I pushed these changes to the repository. If you're using 1.x from the repo just do a git pull.
