### ISSUE TITLE
The project name in tree-view is stuck

### ISSUE THREAD

**Issue by anisylen** [silvestreh/atom-material-ui#136]
Check this screenshot for the issue...

![screen shot 2015-12-01 at 3 30 51 pm](https://cloud.githubusercontent.com/assets/13653918/11497674/8c56010c-9840-11e5-9b3e-98b618fc002a.png)

**Comment by pyvim** [comment]
I got simular problem.
![2015-12-01 14 00 58](https://cloud.githubusercontent.com/assets/4338636/11498999/170139dc-9834-11e5-8534-196faea85880.png)

**Comment by lloydpick** [comment]
If you refresh the Atom window it goes away, however you then get the issue that the project name doesn't actually stick to the top of the tree when you scroll...

![screen_shot_2015-12-02_at_10_55_52](https://cloud.githubusercontent.com/assets/71318/11529198/5e8cdf22-98e3-11e5-9b41-4b25f9b857e2.png)

**Comment by silvestreh** [comment]
Yes, this is fixed in the repository. 1.0.x was unpublished and 0.8.0 is the latest again. If you wish to downgrade reinstall the theme.

If you want to continue using 1.0.x, clone this repository and link it with APM. I posted brief instructions to do so in #131

**Comment by pyvim** [comment]
@silvestreh, good, thanks.
