### ISSUE TITLE
Set of predefined colors

### ISSUE THREAD

**Issue by anisylen** [silvestreh/atom-material-ui#138]
Instead of a color wheel where it is not easy to pick out material-compatible colors, add a list of material design colors which can be overridden by using the color wheel.

My apologies if I am flooding your issues page but these are things that I hope can be fixed...

**Comment by silvestreh** [comment]
Don't apologize, it's ok. This release was a massive flop. I'll add a couple presets. Thanks!

**Comment by anisylen** [comment]
Haha, it was not a massive flop at all. It looks really good but there are obviously a bunch of growing pains! Sorry if I made you feel worse but I really am grateful for this amazing theme.

**Comment by silvestreh** [comment]
This feature is back in the "development version." See the [contributing section](https://github.com/silvestreh/atom-material-ui#contributing) in the `README.md` file if you plan on testing it.

**Comment by aniforprez** [comment]
Same guy on a different account...

Dude, I have to say, you are doing excellent work on this theme. I haven't tested out the latest features but it's inspiring how much you're putting into this theme. Best of luck and hope to see more amazing features on this theme!
