### ISSUE TITLE
Failed to load the quick-editor package

### ISSUE THREAD

**Issue by vnabet** [silvestreh/atom-material-ui#139]
1 - After last atom-material-ui update

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.0.4

### Stack Trace

Failed to load the quick-editor package

```
At .z-depth-1 is undefined in e:\VNabet\.atom\packages\atom-material-ui\styles\buttons.less:13:4

LessError: .z-depth-1 is undefined
  at e:\VNabet\.atom\packages\atom-material-ui\styles\buttons.less:13:4
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-material-ui, v1.0.4
atom-typescript, v7.12.1
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.15
file-icons, v1.6.13
fonts, v1.0.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-jshint, v1.2.1
linter-scss-lint, v2.4.0
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
pigments, v0.19.1
project-manager, v2.6.5
Sublime-Style-Column-Selection, v1.3.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by youriw** [comment]
Had the same issue after updating atom-material-ui

**Comment by silvestreh** [comment]
That's an odd one. Looks like quick-editor is trying to read material-ui's `buttons.less` but it's not loading `ui-mixins.less` and `ui-variables.less` where does mixins and variables are defined. I'll fix it ASAP.

**Comment by alexweber** [comment]
:+1:

**Comment by vnabet** [comment]
I still have this error with last update :/

**Comment by vnabet** [comment]
I had to uninstall the theme and reinstall it. Now it works fine.

**Comment by silvestreh** [comment]
@vnabet you were probably using one of the now unpublished 1.0.x versions. You just rolled back to 0.8.0 :smile:
