### ISSUE TITLE
issues with `v1.*`

### ISSUE THREAD

**Issue by stryju** [silvestreh/atom-material-ui#140]
- linter status got screwed (icons, spacing etc)
![screen shot 2015-12-01 at 11 36 06 am](https://cloud.githubusercontent.com/assets/25367/11499819/cdc48548-9820-11e5-894d-699c67e5aa5e.png)
- omnibox spacing looks weird if not broken
- forced roboto font for UI - why isn't this optional anymore?

**Comment by silvestreh** [comment]
Which linter is that? Might sound stupid but, what's an omnibox?

Yes, Roboto is default now. The theme was rewrote from scratch and since tipography is an integral part of Material Design and this is a theme inspired by it, it made perfect sense.

**Comment by JoelESvensson** [comment]
Could it at least be possible to use another font if you want to?

**Comment by anisylen** [comment]
@silvestreh I think by omnibox he means the status bar at the bottom. The one showing 'upload-to-cloud' icon and "html/icon.svg".

Also please also consider making Roboto optional as it was previously because the font is a little too thin for the file tree. It's ok if it's on by default.

**Comment by JoelESvensson** [comment]
Exactly. I find Roboto a bit difficult to read at times

**Comment by silvestreh** [comment]
I'll make Roboto optional. Anyone got a clue what package is that in the screenshot?

**Comment by stryju** [comment]
it's nuclide diagnostics ui (part of [nuclide](https://github.com/facebook/nuclide))

it's OK in v0.8.0

![screen shot 2015-12-02 at 5 26 26 pm](https://cloud.githubusercontent.com/assets/25367/11538494/31800e78-991a-11e5-9585-b8ee102034fa.png)

re omnibox - the extensible panel that allows you to find files

**Comment by silvestreh** [comment]
@stryju thanks. I'll get those packages and work with them. 

> re omnibox - the extensible panel that allows you to find files
aha! I call it fuzzy finder :smile:

**Comment by jota-v** [comment]
+1 for making Roboto mono optional for the code part. 
Doesn't have good readability, at least in my computer, had to change the theme, but I miss atom-material-ui.

**Comment by silvestreh** [comment]
@jota-v Roboto Mono is not included in 1.0.x … We were talking about Roboto for the UI, not the code.

1.0.x was unpublished and 0.8.0 is the latest version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!

**Comment by silvestreh** [comment]
Man nuclide looks interesting but it makes Atom sooooooooooooooooo slow. Unbearable to work with. I wanted to support these packages, but looks like I actually *can't*.

**Comment by stryju** [comment]
nuclide is fast when set up properly ;-)

**Comment by anisylen** [comment]
@stryju at the risk of derailing this conversation, can you give some tips on how to set it up so it doesn't drag atom down like an anchor? installing it made atom run at something like 5fps or less and commands were processed incredibly slowly...

**Comment by silvestreh** [comment]
@stryju I tried installing following the repo's instructions. I tried building from source too. I tried on OS X. I tried on Windows. Nuclide lagged on all those scenarios to the point where Atom is no longer usable. 

Nuclide is slow when set up following documentation ;-)

**Comment by silvestreh** [comment]
@stryju just pushed some styles for nuclide.

@anisylen to get Nuclide running at decent speed first uninstall all nuclide packages and then build them from source.

    rm -rf ~/.atom/packages/nuclide-* ~/.atom/packages/hyperclick
    git clone git@github.com:facebook/nuclide.git
    cd nuclide/
    ./scripts/dev/setup

Also, if you're running NPM 3.x you'll have to downgrade to a previous, 2.x, version: `npm install -g npm@2.14.10`. Otherwise Nuclide setup will fail.

**Comment by stryju** [comment]
@silvestreh cool! will check it out when i have some spare time :)

---

@anisylen yeah, as @silvestreh mentioned - building from source is usually a good idea

i have a rather specific setup, so it runs rather smooth here ;-)
