### ISSUE TITLE
Styling of several packages fails

### ISSUE THREAD

**Issue by weidler** [silvestreh/atom-material-ui#141]
The styling of several packages is different to before/doesnt work/looks strange, including:

- file-icons by DanBrooker (Icons in Tab Pane only get shown when active, changing to tab lets the title jump right for the icon)
- Script by rgbkrk (Success message is extremly huge while the messages the programm i run are wrapped by a strange white border)
- ...
- I think something changed about the Indent Guide (atom default), not sure tho

Would be awesome if thatcould be fixed.

**Comment by chazzlabs** [comment]
It looks like the styling of other themes is also affected.  In my environment it appears that the styles of Atom Dark/Light, One Dark/Light, and Seti are being overridden by atom-material-ui's.

**Comment by chazzlabs** [comment]
After debugging this a bit locally, I think the problem might be that some of Atom's default style variables are being overridden in atom-material-ui.  Atom's variables can be seen here: https://atom.io/docs/latest/hacking-atom-creating-a-theme#variables

A couple examples from [ui-variables.less](https://github.com/silvestreh/atom-material-ui/blob/master/styles/ui-variables.less):
```
@text-color: fade(@syntax-text-color, 80%);
@base-background-color: transparent;
```

I tested this using the [linter plugin](https://github.com/atom-community/linter), which uses @text-color and @base-background-color to style its error popup ([from linter-plus.less](https://github.com/atom-community/linter/blob/master/styles/linter-plus.less)):
```
#linter-inline {
  @linter-inline-link: fade(@base-background-color, 66%);
  @linter-inline-fg: @base-background-color;
  @linter-inline-bg: @text-color;
  margin-top: 4px;
  padding: @spacing;
  color: @linter-inline-fg;
  border-radius: @component-border-radius * 1.5;
  border-top-left-radius: 0;
  background: @linter-inline-bg;
  box-shadow: 0 1px 3px hsla(0, 0, 0%, 0.4);
  ...
```

Changing @text-color and @base-background-color in atom-material-ui successfully changes the style of linter's error popup.

Admittedly this is my first time looking at package development.  What is the etiquette when using Atom's variables?  Is it the responsibility of the package developer to know that other packages might override Atom variables, or should Atom's variables remain unchanged?  It seems like you'd want to override Atom's variables when creating a custom theme.

**Comment by silvestreh** [comment]
@chazzlabs yes, it is expected to overwrite those variables, but they *shouldn't* conflict with other themes when the material ui is deactivated. That's what has been puzzling me for a while now.

**Comment by silvestreh** [comment]
All problems in OP were pushed to the repository. No release yet though. Everyone's welcome to clone the repository and test.
