### ISSUE TITLE
Issues with icons in tabs

### ISSUE THREAD

**Issue by Robert-W** [silvestreh/atom-material-ui#144]
The icons in some tabs are not aligned properly and are occasionally colliding with the text.  This does not happen with every file-icon but does with `.bowerrc` and `.gitignore` every time, as well as some others.  In this screenshot the `.gitignore` is not actually the active tab, but the icon is just hanging out anyway.

Also there used to be a way to show file icons in all tabs, not just the active tab, but that seems to have gone away in the latest versions, would love to see that feature back since it made finding a specific file amongst many open tabs much easier.

Thanks.

<img width="535" alt="screen shot 2015-12-01 at 11 27 03 am" src="https://cloud.githubusercontent.com/assets/1177959/11506796/23c72876-981f-11e5-8e14-6407fd4de96e.png">

**Comment by silvestreh** [comment]
It's been fixed in the development version. 1.0.x was unpublished and 0.8.0 is the latest version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!

**Comment by Robert-W** [comment]
Thanks.  Ill wait for the next stable release, I've already rolled back to 0.8.0.  Thanks again for the theme. :+1:

**Comment by silvestreh** [comment]
Thank you for using it :+1:
