### ISSUE TITLE
Updating resets setting preferences

### ISSUE THREAD

**Issue by ryanaltvater** [silvestreh/atom-material-ui#146]
The last 2 times I have updated, my setting preferences for the plugin have automatically reset. I wasn't experiencing this issue until recently (within the last month).

**Comment by silvestreh** [comment]
Yes, that was intentional. But should only happen once. It checks for a particular key in your localStorage, if it isn't set it will reset the theme's settings and then set it to avoid settings being reset again.

This should've happened once when updating from 0.8.0 to 1.0.0

**Comment by ryanaltvater** [comment]
Okay, makes sense I guess. I apologize if it was intentional. I just updated to 1.0.5 and it reset again. How do I set that key to keep it from resetting?

**Comment by silvestreh** [comment]
open a DevTools console and type: `localStorage.setItem('atom-material-ui:configOk', true);`

BTW, 1.0.x was unpublished and 0.8.0 is the latest version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!

**Comment by ryanaltvater** [comment]
I typed it in the console and it returned ³undefined². Does that sound
right?


--
Ryan Altvater
Designer & Developer
www.ryanaltvater.com <http://www.ryanaltvater.com>

From:  Silvestre Herrera <notifications@github.com>
Reply-To:  silvestreh/atom-material-ui
<reply+001465d36a69689526b94deec894a3403be1cb09e614ac0d92cf000000011279d1949
2a169ce07235ab5@reply.github.com>
Date:  Friday, December 4, 2015 at 5:11 PM
To:  silvestreh/atom-material-ui <atom-material-ui@noreply.github.com>
Cc:  Ryan Altvater <ryan@ryanaltvater.com>
Subject:  Re: [atom-material-ui] Updating resets setting preferences (#146)

localStorage.setItem('atom-material-ui:configOk', true);

**Comment by silvestreh** [comment]
@ryanaltvater yes, that is fine :smile: Do your settings still get reset?

**Comment by ryanaltvater** [comment]
I haven't tested it, but did notice that my copy of the plugin went back to the older version which I like. If I notice any issues in the future, I will re-comment and report back here. Thanks a lot! :+1:

**Comment by silvestreh** [comment]
Awesome. :)
