### ISSUE TITLE
update doesnt work correctly

### ISSUE THREAD

**Issue by lgrube** [silvestreh/atom-material-ui#147]
get this error when trying to update
![screen shot 2015-12-01 at 11 58 08 am](https://cloud.githubusercontent.com/assets/10444043/11509301/f6e02980-9822-11e5-93f9-c9da9a9c1eda.png)

**Comment by AWTrost** [comment]
:+1: FWIW: when looking at the json from https://www.atom.io/api/packages/atom-material-ui/ its listed there, but the url it lists (the one in the screengrab above) 404's.

**Comment by silvestreh** [comment]
Same as #148 … I killed the 1.0.x releases and switched back to 0.8.0 … if anyone's willing to help testing clone the repo and then link it (steps to do that in #131)
