### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by VikramTiwari** [silvestreh/atom-material-ui#148]
Something happened to @github or was this intentional @silvestreh? Missing releases since 0.8.0

![screen shot 2015-12-01 at 09 58 46](https://cloud.githubusercontent.com/assets/1330677/11509334/5ea957d2-9812-11e5-93cb-8ad091b29ce6.png)

**Comment by VikramTiwari** [comment]
Got here while trying to update package on Atom.

![screen shot 2015-12-01 at 10 03 38](https://cloud.githubusercontent.com/assets/1330677/11509465/13dd9226-9813-11e5-93d6-ad072353d2f0.png)

**Comment by silvestreh** [comment]
Yeah, I rolled back the 1.0 branch, sorry. Reinstall the package.

**Comment by jerone** [comment]
Remember that you can't re-use the same version tags.

Why did you pull the new releases?

And do you recommend downgrading for the users that installed 1.0 (I'm on 1.0.1) and up or just wait for the next release?

**Comment by silvestreh** [comment]
Yeah, I recommend downgrading unless you're having no issues with 1.0.1 (until you open a new Atom window without a treeview and things will explode).
