### ISSUE TITLE
Settings config-menu active state broken when User interface font size is changed

### ISSUE THREAD

**Issue by mattbanks** [silvestreh/atom-material-ui#149]
I changed my User interface font size to 15 (16 was too big for me). When I change this, the active state on the `.settings.view .config-menu .nav > li` items is broken. It animates properly to the full width and height, and then after the animation finishes, the active state changes to roughly 50% height. It works properly at 16pt font size for User interface.

Screenshot:
![screenshot 2015-12-01 14 09 08](https://cloud.githubusercontent.com/assets/302970/11511242/f4f93e6e-9835-11e5-9f63-41713bf9f60e.png)

I wish I had time to play with the CSS to fix this, but I have to get back to a project. I believe the issue is here, after a super quick look at the code - https://github.com/silvestreh/atom-material-ui/blob/master/styles/settings/config-menu.less#L19-L20

**Comment by silvestreh** [comment]
Thanks. I'll take a look at this as soon as I get some free time :)

**Comment by silvestreh** [comment]
It's been fixed in the development version. 1.0.x was unpublished and 0.8.0 is the latest version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!
