### ISSUE TITLE
Tree View no longer greys out ignored files

### ISSUE THREAD

**Issue by tylerFowler** [silvestreh/atom-material-ui#150]
I find that after the latest update (1.0.5), the menu items in the TreeView that were formerly greyed out due to being present in the gitignore, are now filled in.

**Comment by silvestreh** [comment]
Thanks. The theme was rewrote from scratch in the lastest update. You can downgrade to 0.8.0 if you wish:

    apm uninstall atom-material-ui
    apm install atom-material-ui@0.8.0

But I'll appreciate all issues you can report if you decide to stick with 1.0.x.

**Comment by tylerFowler** [comment]
I've also found that git highlighting no longer works for parent directories. So a file will be highlighted showing it has changes (or is new or whatever), though the parent folder icons no longer highlight to show that a change is somewhere downstream. Though I can't remember if that's a package now or if it's default Atom behavior..
