### ISSUE TITLE
Adding other projects to tree view doesn't work

### ISSUE THREAD

**Issue by JoelESvensson** [silvestreh/atom-material-ui#151]
Also, when you collapse a project in the tree view it disappears. They all seem to be stacked on top of each other

**Comment by silvestreh** [comment]
This is fixed in the repository. 1.0.x was unpublished and 0.8.0 is the _latest_ version once more. If you wish to downgrade just reinstall the theme:

    apm uninstall atom-material-ui
    apm install atom-material-ui

However, if you wish to continue using 1.0.x, clone this repository and link it with APM.

    apm uninstall atom-material-ui
    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link
    apm install

Thanks!
