### ISSUE TITLE
Global Search not highlighting 

### ISSUE THREAD

**Issue by layonferreira** [silvestreh/atom-material-ui#153]
When I do a global search with atom-material-ui the  search results are not highlighted.
this only happens after the last update.

### note
Os: OSX el captain
![snip20151202_1](https://cloud.githubusercontent.com/assets/5243855/11530738/1533285c-98ef-11e5-906f-6bdc4948b679.png)

Cheers.

**Comment by silvestreh** [comment]
Thanks! I'll take a look at this.

**Comment by silvestreh** [comment]
Fixed in the repo. Thanks!

**Comment by layonferreira** [comment]
Thanks for the hard work
