### ISSUE TITLE
Tinted tab bar loses color when atom is not primary window.

### ISSUE THREAD

**Issue by skbolton** [silvestreh/atom-material-ui#155]
Loving the new tinted tab bar update. Only a small annoyance but it loses the color when you take focus off of atom

**Comment by silvestreh** [comment]
Yep, that's intentional. I meant to let users know which Atom window is focused.

**Comment by skbolton** [comment]
Gotcha, would it be a pain for you to point me in the direction of overriding it in my configuration?

**Comment by silvestreh** [comment]
Sure, open your stylesheet and paste this snippet:

`.tinted-tab-bar .is-blurred .tab-bar:not([data-reactid]) { -webkit-filter: none; }`

That should do it.

**Comment by silvestreh** [comment]
or… `.is-blurred * { -webkit-filter: none !important; }` should also take care of any other components which have this "blurred-status" effect.
