### ISSUE TITLE
Can't change accent color

### ISSUE THREAD

**Issue by viggy96** [silvestreh/atom-material-ui#157]
I can no longer change the accent color on the theme.

**Comment by silvestreh** [comment]
Which theme version are you using? Did you upgrade to 1.0 and then rolled back?

**Comment by viggy96** [comment]
Theme version 0.8.0. For the accent colour, there is only a text box. I tried inputting colour words (i.e. red, blue, etc) and hex values, but it doesn't seem to work. I've also tried uninstalling and reinstalling the theme.

**Comment by silvestreh** [comment]
Alright, looks like something might be wrong with your settings. I don't know exactly why or how it happens, but if there are changes to the settings schemas you'll continue to see settings that are no longer in use.

You can either open your config file located in `~/.atom/config.cson` and delete your settings for `atom-material-ui` or open a DevTools console and type: `atom.config.set('atom-material-ui')` to reset the theme's settings.

Hope that helps.

**Comment by viggy96** [comment]
Thanks. That worked.
