### ISSUE TITLE
Invisibles too invisible

### ISSUE THREAD

**Issue by chester1000** [silvestreh/atom-material-ui#159]
When `Show Invisibles` and `Atom Material` UI Theme are enabled in Atom, invisibles are really hard to see:

<img width="68" alt="screen shot 2015-12-10 at 13 45 59" src="https://cloud.githubusercontent.com/assets/526657/11707890/7940a15c-9f44-11e5-8573-af4b461ac4c8.png"> <img width="47" alt="screen shot 2015-12-10 at 13 45 40" src="https://cloud.githubusercontent.com/assets/526657/11707891/7965c9be-9f44-11e5-8fa2-bd4ded310b26.png">

Problem also occurs with all `Syntax Themes`

**Comment by chester1000** [comment]
Possible dup of https://github.com/silvestreh/atom-material-ui/issues/56

**Comment by silvestreh** [comment]
This belongs to the syntax theme repo :) … but I'll take a look anyways

**Comment by silvestreh** [comment]
Just pushed an update for the syntax theme.

**Comment by chester1000** [comment]
Thank you, but I don't think it's a syntax theme repo issue, because

1. Your fix didn't fix it for me :P,
2. Issue persists with Material UI Theme and different Syntax Themes selected as well:

 <img width="44" alt="screen shot 2015-12-11 at 00 58 41" src="https://cloud.githubusercontent.com/assets/526657/11722211/86e3835c-9fa2-11e5-8a5b-63e3b3771578.png"> <img width="51" alt="screen shot 2015-12-11 at 00 58 52" src="https://cloud.githubusercontent.com/assets/526657/11722208/86dddd8a-9fa2-11e5-9d8c-26a0c1e2dbe6.png"> <img width="41" alt="screen shot 2015-12-11 at 00 58 27" src="https://cloud.githubusercontent.com/assets/526657/11722209/86df56ce-9fa2-11e5-9663-a5d949b39152.png"> <img width="47" alt="screen shot 2015-12-11 at 00 58 15" src="https://cloud.githubusercontent.com/assets/526657/11722210/86e18854-9fa2-11e5-8e79-14072d89976f.png"> <img width="52" alt="screen shot 2015-12-11 at 00 57 59" src="https://cloud.githubusercontent.com/assets/526657/11722212/86e6571c-9fa2-11e5-927a-5231704676a8.png">

When different UI theme is selected, but syntax theme is Material then it does look a little better:

<img width="44" alt="screen shot 2015-12-11 at 00 59 16" src="https://cloud.githubusercontent.com/assets/526657/11722262/c6a650d2-9fa2-11e5-823e-fa9decedba9e.png">

Here's a non-Material Theme and non-Material Syntax for comparison:

<img width="49" alt="screen shot 2015-12-11 at 00 59 36" src="https://cloud.githubusercontent.com/assets/526657/11722281/d92495b6-9fa2-11e5-97df-b5d14d1d7693.png">

**Comment by chester1000** [comment]
After a little digging in Atom, looks like disabling this solves the issue:

<img width="338" alt="screen shot 2015-12-11 at 01 17 08" src="https://cloud.githubusercontent.com/assets/526657/11722658/0162396e-9fa5-11e5-829f-03cd348097fe.png">

When I press `<style>…</style>` there it points to `~/.atom/packages/atom-material-ui/index.less`, but I ain't no less ninja and I can't locate relevant lines ;(.

**Comment by silvestreh** [comment]
Aah… Probably Material UI 0.8.0 had some styles for those elements that should've been in the syntax theme. I'm focusing whatever free time I have in fixing the 1.0 release which is an entirely different code base.

1.0 was released a couple weeks ago but I rolled it back because there were too many bugs. If you want, you're welcome to try the current development version and test the hell out of it (need testers). To do so you have to [download the repo](https://github.com/silvestreh/atom-material-ui/archive/master.zip) and extract it to `~/.atom/packages`. Or you could clone the repository and link it with APM:

    git clone git@github.com:silvestreh/atom-material-ui.git
    cd atom-material-ui
    apm link && apm install

**Comment by chester1000** [comment]
Ok, I am on 1.0.5 and the first thing I must say is, **please** get rid of those awful color pickers :P. If you really, really want to keep them somewhere, then add a color picker with a limited, hand-picked set of colors first, and hide current ones under `advanced` or `more` or sth...

Second, invisibles seem to be more visible now indeed, still really hard to see, though :/.

Also, my syntax colors seem to changed as well, and I must say I like them better now :D

Finally, what is this thing in the bottom of the screen, that says _"Settings"_? Was it always here? :P

<img width="1121" alt="screen shot 2015-12-11 at 02 25 21" src="https://cloud.githubusercontent.com/assets/526657/11724351/872c3988-9fae-11e5-8ef9-05257fd6d513.png">

**Comment by chester1000** [comment]
My problem with color pickers is that they're completely overwhelming, all those tabs and options. Users would rather stay with the default color, then mess with the picker and eventually end up with a worse color without an easy way to get back.

Predefined colors give the ability of instant reverse and less choice makes the choice significantly easier. If user wants yellow (s)he doesn't need to think "how bright it should be?", "how saturated?", "maybe a little bit more green?", etc ;). Yellow is just yellow. 

Just pick one shade of the spectrum [here](https://www.google.com/design/spec/style/color.html#) and grab all the colors with it. Or use the colors from the previous version, they were great!

**Comment by silvestreh** [comment]
>Ok, I am on 1.0.5 and the first thing I must say is, please get rid of those awful color pickers

The color pickers are staying :grin:. I do plan on adding a combo to pick a predefined color from the MD palette (like the previous version.)

>invisibles seem to be more visible now indeed, still really hard to see, though :/

Alright, I'll make them more opaque. I rarely use them, but I can see them alright. Monitor brightness perhaps?

>Also, my syntax colors seem to changed as well, and I must say I like them better now :D

Thank @equinusocio, the syntax theme is a direct port from his SublimeText theme. :smile: 

>Finally, what is this thing in the bottom of the screen, that says "Settings"? Was it always here? :P

Yep, it's always been there. When you're viewing a file, its path will appear there. Since settings view doesn't really have a path it only shows "Settings".

**Comment by chester1000** [comment]
> The color pickers are staying :grin:. I do plan on adding a combo to pick a predefined color from the MD palette (like the previous version.)

:cry: :sob: 

I guess I'll stay on default until better solution ships :stuck_out_tongue_winking_eye: .

**Comment by silvestreh** [comment]
I'm writing that feature as we speak. It's not too far away :stuck_out_tongue_winking_eye:

**Comment by chester1000** [comment]
Super glad to hear that :smiley:

**Comment by silvestreh** [comment]
@chester1000 done. do a `git pull` and reload atom (or download again the ZIP file and extract it)

**Comment by chester1000** [comment]
@silvestreh I did that and I like it now. Thank you! :)
