### ISSUE TITLE
Dropdowns are unreadable

### ISSUE THREAD

**Issue by raulsntos** [silvestreh/atom-material-ui#16]
Dropdowns have a white background and a very light text color which makes it unreadable, luckily hovering over the items gives the hovered item a blue background so this doesn't really means it's unusable, just though you should know though you probably already knew.
Note that I'm using OneDark which comes with Atom so not a weird syntax theme and the same thing happens with all the other preinstalled syntax themes like Atom Dark and Solarized Dark.
I'm using Atom 1.0.0 in Windows 8.1.
![dropdown](https://cloud.githubusercontent.com/assets/3903059/8388785/06cb24cc-1c67-11e5-9623-952c7a385683.png)
It look worse in monokai syntax theme, which makes the text color white so you can't see the text at all, but I understand it's a third party plugin, just letting you know.
![dropdown](https://cloud.githubusercontent.com/assets/3903059/8388833/c4a70632-1c67-11e5-8e99-97654a3becb2.png)

**Comment by silvestreh** [comment]
Yeah, you're right. This came up a few days ago. Though I had fixed it but looks like I didn't.

It's absolutely important to me that the UI theme works with other syntax themes. Even light variants.

I just pushed an update to fix this. Update and let me know if it's better for you too.

**Comment by raulsntos** [comment]
Much better, thank you! It looks perfect now :smiley:
