### ISSUE TITLE
Hidden and Git ignored files are no longer dim

### ISSUE THREAD

**Issue by BrandonZacharie** [silvestreh/atom-material-ui#160]
![screen shot 2015-12-10 at 01 20 53](https://cloud.githubusercontent.com/assets/27306/11711601/6fb8ba10-9edc-11e5-90d3-5f287cfd0f0f.png)

**Comment by silvestreh** [comment]
Which version of Material UI are you running?

**Comment by silvestreh** [comment]
I'm closing this one as I suspect it's for an unpublished version of the theme. Also, this is fixed in the "development version."
