### ISSUE TITLE
Panel height too big

### ISSUE THREAD

**Issue by steelbrain** [silvestreh/atom-material-ui#161]
![screenshot](https://cloud.githubusercontent.com/assets/4278113/11763017/e4c4c02a-a0b6-11e5-823a-a97ff27e0067.png)
It's the new linter panel, looks huge with this theme

**Comment by silvestreh** [comment]
which linter is that?

**Comment by steelbrain** [comment]
It's the ui split branch I'm working on

**Comment by steelbrain** [comment]
We're splitting linter and it's ui, community will then be able to create complete linter UI via an API. The default ui will be in `linter-ui-default` package

**Comment by silvestreh** [comment]
I see… is it relatively easy to set this unreleased linter so I can take a look and make it not look huge?

**Comment by steelbrain** [comment]
Sure, checkout these PRs
https://github.com/atom-community/linter/pull/995
https://github.com/AtomLinter/linter-ui-default/pull/1

**Comment by silvestreh** [comment]
Ahá… it's inheriting styles from `panel-heading`… is `linter-new-panel` the final name for the component tag?

**Comment by steelbrain** [comment]
Negative, I'm gonna rename it to `linter-default-panel` or something before publishing

**Comment by silvestreh** [comment]
Alright… just pushed styles for it. :)

**Comment by steelbrain** [comment]
Another question I have in mind is, if the panel works perfectly with default themes then why do you add explicit styles in this theme instead of fixing what's actually mistaken :)

**Comment by silvestreh** [comment]
Hmmm… good question. I guess a heading should have a bigger font than the rest of the text… Take Markdown for example:

This is a heading
====

This is not a heading

At least that's the reasoning behind the styles of this theme. So, in that sense, the elements in Atom's status bar shouldn't be headings. Though I'm not sure if the Atom community uses headings in a different manner that I'm not used to.

**Comment by steelbrain** [comment]
While I can't say I disagree that heading should be bigger than the rest of the text. I was just following the styleguide. Can you check the style guide (`styleguide:show`) with `material-ui` on? It'll show you everything UI element that it could possibly break. For the record, I am just following the panel styles there, at least I'm trying to

**Comment by silvestreh** [comment]
I *think* you should be using the `panel-body` class for the linter panel. It would make more sense (semantically speaking), at least for me.

![captura de pantalla 2015-12-14 a las 13 37 01](https://cloud.githubusercontent.com/assets/1133339/11786883/cd6f25f2-a267-11e5-80de-20f740561cf4.png)

**Comment by steelbrain** [comment]
@silvestreh, sorry for the late reply but we're already using the `panel-body` class for panel body, but the problem is with the heading where we use the `panel-heading` class. Please see this screenshot using the `One Dark` theme of the styleguide http://i.imgur.com/Hl7VVR0.png
