### ISSUE TITLE
How to get the colored titlebar as shown in the screenshots?

### ISSUE THREAD

**Issue by sean-clayton** [silvestreh/atom-material-ui#162]
As seen here:

![](https://camo.githubusercontent.com/5b4f09095cc756749e62574d1889fba3e9383f91/687474703a2f2f692e696d6775722e636f6d2f4e464a423437512e706e67)

How does one achieve the tinted titlebar with the window controls?

**Comment by silvestreh** [comment]
Photoshop… :grin:

**Comment by silvestreh** [comment]
TBH… I should probably remove those :)

**Comment by Nephrited** [comment]
Given that these coloured tilebars are present in the Sublime theme this theme is based off, would it be worth requesting they be built into the theme?

https://i.imgur.com/SesxI1L.png <-- What my Sublime setup looks like, and ideally what I'd like my Atom to be able to mimic.
