### ISSUE TITLE
Blend treeview with tab bar setting not persisting

### ISSUE THREAD

**Issue by JamesCoyle** [silvestreh/atom-material-ui#164]
It seems this setting doesn't get applied when atom is reopened but the checkbox is still checked in the settings. Toggling the checkbox triggers it to update and show the projects element again. Seems like it's just failing to check on load if it should be shown.

**Comment by silvestreh** [comment]
It does persist for me. Are you having this issue when opening a new window from within Atom? Or opening Atom for the first time?

**Comment by JamesCoyle** [comment]
Both. The setting isn't applied when any atom window is opened.

**Comment by silvestreh** [comment]
Well, that's odd… I can't reproduce this :confused:. The only thing I can think of is a conflicting old setting.

**Comment by JamesCoyle** [comment]
I've uninstalled and deleted the theme and then removed any settings in the config to remove any possible conflict and then reinstalled. Still the same issue. No errors are shown and the log just has warnings about other packages using the now depreciated `::shadow` and `/deep/` selectors. 

Unfortunately I don't really understand how the settings and coffeescript aspect of the theme works yet so can't really see if there is an issue with that which is causing the setting to not be applied on startup.

**Comment by silvestreh** [comment]
@JamesCoyle fortunately, there's no more CoffeeScript. It's all JavaScript now (ES6) transpiled with Babel.

I still can't reproduce it on Windows 10 nor OS X 10.10.

**Comment by JamesCoyle** [comment]
Just updated my local version and the issue seems to no longer be present. Not sure what the cause was but it seems you fixed it. Still having the #165 issue though.
