### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by JamesCoyle** [silvestreh/atom-material-ui#165]
I pressed the ALT key to show the menu at the top. No clue what caused this.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of null

```
At C:\Users\SolusSoftworks\Google Drive\Projects\Repositories\atom-material-ui\node_modules\perfect-scrollbar\src\js\plugin\instances.js:72

TypeError: Cannot read property 'dataset' of null
    at getId (C:\Users\SolusSoftworks\Google Drive\Projects\Repositories\atom-material-ui\node_modules\perfect-scrollbar\src\js\plugin\instances.js:72:21)
    at Object.exports.get (C:\Users\SolusSoftworks\Google Drive\Projects\Repositories\atom-material-ui\node_modules\perfect-scrollbar\src\js\plugin\instances.js:108:20)
    at Object.module.exports [as update] (C:\Users\SolusSoftworks\Google Drive\Projects\Repositories\atom-material-ui\node_modules\perfect-scrollbar\src\js\plugin\update.js:13:21)
    at Immediate._onImmediate (C:/Users/SolusSoftworks/Google Drive/Projects/Repositories/atom-material-ui/lib/amu-bindings.js:36:27)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view",
      "tool-bar",
      "highlight-line"
    ],
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false
  },
  "atom-material-ui": {
    "fonts": {},
    "ui": {},
    "tabs": {
      "tintedTabBar": true
    },
    "treeView": {
      "blendTabs": true
    },
    "colors": {
      "abaseColor": {
        "red": 76,
        "green": 74,
        "blue": 72,
        "alpha": 1
      }
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.0.5
editorconfig, v1.2.2
file-icons, v1.6.13
flex-tool-bar, v0.7.2
highlight-line, v0.11.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-cpplint, v1.0.0
linter-flake8, v1.9.3
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
minimap, v4.18.2
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
Remote-FTP, v0.7.15
save-session, v0.16.0
sync-settings, v0.6.0
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
Looks like a problem with `perfect-scrollbar`… I'll check in a Windows machine because looks like I won't be able to reproduce this on OS X.

**Comment by silvestreh** [comment]
Do you have a package that replaces the bundled tree-view?

**Comment by JamesCoyle** [comment]
I use Remote-FTP which has its own tree-view. That package always seems to have issues really.

**Comment by silvestreh** [comment]
What *might* be happening is that `perfect-scrollbar` is trying to attach to `Remote-FTP`'s tree instead of the bundled `tree-view ` package.

This could also be the answer to #164 

Try disabling that package and see if it works. That way we can at least determine that this is the cause and work on it :smile:

**Comment by JamesCoyle** [comment]
I can't replicate this with or without that package enabled. #164 is not solved by disabling Remote-FTP either. :/

**Comment by JamesCoyle** [comment]
It's triggered whenever the height of the scrollbars changes. I get the error everytime I press `ALT' to show the menu and everytime I toggle the setting in Atom's core settings as well as when I adjust the height of the window.

What does the perfect scrollbar package do exactly?

**Comment by silvestreh** [comment]
@JamesCoyle perfect-scrollbar replaces the OS scrollbar only if scrollbars are always visible. In OS X there's an option to always show scrollbars. Windows always shows scrollbars with no option to hide them. I'm not sure what happens on linux though, I'm suspect they're always visible like on Windows.

Why replace the OS scrollbar? OS scrollbars create a visual separation between the `tree-view` and `tab-bar`. That kills the "blend tree view with tab bar" look.

**Comment by JamesCoyle** [comment]
Can you not use webkit scrollbars instead though?

**Comment by silvestreh** [comment]
Yep, I tried webkit scrollbars. Same problem unfortunately.

**Comment by JamesCoyle** [comment]
What problem exactly? I'm not really understanding what you are saying with regards to the visibility on different OS's.

**Comment by silvestreh** [comment]
This is what it looks like without perfect scrollbar:

![captura de pantalla 2016-01-19 a las 18 46 34](https://cloud.githubusercontent.com/assets/1133339/12432939/fb7fcd2a-bedc-11e5-990e-be0a5a075031.png)

Notice how the scroll track is always visible and appears on top of the "Projects" title. This other screenshot is with PS enabled:

![captura de pantalla 2016-01-19 a las 18 47 27](https://cloud.githubusercontent.com/assets/1133339/12432976/25c82500-bedd-11e5-891b-87e012e6068f.png)

Atom will detect wether the current OS settings are set to always show scrollbars and apply a class to its `workspace`.

![captura de pantalla 2016-01-19 a las 18 49 11](https://cloud.githubusercontent.com/assets/1133339/12433022/7a8b04a4-bedd-11e5-95e1-d20105854bc9.png)

Lastly, this is OS X settings where you can choose wether to show scrollbars all the time or only while scrolling.

![](http://cdn.osxdaily.com/wp-content/uploads/2011/08/always-show-scroll-bars-mac-os-x-lion.jpg)

**Comment by JamesCoyle** [comment]
Ah ok. Well the issue I was having seems to be fixed for now so not really sure what the issue was.
