### ISSUE TITLE
Text displayed in text inputs is smaller than the expected

### ISSUE THREAD

**Issue by blude** [silvestreh/atom-material-ui#166]
To make it a tad easier to read and more consistent with the current UI.

A quick preview:

## Before
![text size in mini inputs](https://cloud.githubusercontent.com/assets/616018/11907999/ac2e8fe4-a5bf-11e5-8b24-9f31f1cdfd77.png)

## After

![better text-size](https://cloud.githubusercontent.com/assets/616018/11908044/1028c2bc-a5c0-11e5-9080-6d465c8bac4a.png)

**Comment by silvestreh** [comment]
Which version of the theme are you using? If you're still using `0.8.0` you're welcome to try the development version. Check the contributing section of the `README.md` file for instructions.

As for the font size, well, you can use that in your personal stylesheet.

**Comment by blude** [comment]
Thanks for the input, @silvestreh. It looks great now.

I understand this is a subjective matter though I think the theme would be benefited by a more legible typography. I'd appreciate your feedback on this.

Thanks for the awesome work!
