### ISSUE TITLE
Linting popup incorrect styling

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#169]
Not entirely sure who is at fault here, `atom-linter` or `atom-material-ui`, but the popup showing linting errors is incorrectly styled as seen below (as of https://github.com/silvestreh/atom-material-ui/commit/a12155f54a0a35c2eb4492a2958ca2bef8fd12c7)

![screenshot from 2015-12-28 11 40 16](https://cloud.githubusercontent.com/assets/8268040/12016813/40ae3792-ad58-11e5-9943-fa00d7e84d75.png)

I would love to fix and PR, but don't have time :wink:

**Comment by WoodyWoodsta** [comment]
Also incorrect styling for the linter errors panel at the bottom of the window:

![screenshot from 2015-12-28 12 17 10](https://cloud.githubusercontent.com/assets/8268040/12017269/084f325c-ad5d-11e5-95dc-93035ab4a8c8.png)

**Comment by silvestreh** [comment]
Here's what it looks like for me:

![captura de pantalla 2016-01-04 a las 14 07 55](https://cloud.githubusercontent.com/assets/1133339/12095326/ad58ccba-b2ec-11e5-9027-8c136a0b49b9.png)

Still, I believe we're using different versions of the plugin.

**Comment by WoodyWoodsta** [comment]
Switched to JSHint but that didn't fix. Removed and installed all linter packages again and still no luck. Are you running the published version (`1.11.3`) or cloned locally from [here](https://github.com/atom-community/linter)?

I have `1.11.3` as installed via `apm` and it appears to be different (different info in popup and error panel below issues section).

**Comment by WoodyWoodsta** [comment]
Well I guess https://github.com/silvestreh/atom-material-ui/commit/f93bd1725a87d2f9acdfa18db939bba7198b4782 fixed it, didn't it :eyes: Thanks for the fix, nonetheless

**Comment by silvestreh** [comment]
@WoodyWoodsta yeah, I'm running Linter from the repository so I could add support for the upcoming update.
