### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Nonlimit** [silvestreh/atom-material-ui#17]
![color](https://cloud.githubusercontent.com/assets/11960153/8396559/e1c81588-1db3-11e5-87d2-18c6feb21d8c.PNG)
Please change color from white to more darken.

**Comment by silvestreh** [comment]
Any reason in particular?

**Comment by anderson-arlen** [comment]
+1

The contrast between the panel and the background is too high. Especially when working and you bring down the command palette. Blinding. It makes my eyes bleed.

**Comment by tripathiakshit** [comment]
I feel that bringing the background down from #fff to #eee should be enough/

**Comment by Nonlimit** [comment]
White color distracts eyes too much, it doesn't fit in the overall color scheme.Also it is hard to see the installation and version numbers properly on the white background

**Comment by silvestreh** [comment]
Done! … just pushed an update. 0.4.11 should improve this.
