### ISSUE TITLE
Theme colours are saved in the source files, not in config

### ISSUE THREAD

**Issue by Alaneor** [silvestreh/atom-material-ui#170]
When I change the theme's colours to one of the predefined options, the configuration is saved into the _styles/custom.less_ file. I would expect this to go to my _config.cson_ file, where configuration normally resides.

Given the file's name, I expect this is currently how it really is supposed to work, so this issue is not really a bug report, but more like a suggestion for improvement. :smile: 

Here are the changed variables from that file:

```diff
diff --git a/styles/custom.less b/styles/custom.less
index a993bb7..25d6eed 100644
--- a/styles/custom.less
+++ b/styles/custom.less
@@ -1,6 +1,6 @@
-@accent-color: #528c94;
-@accent-text-color: desaturate(darken(#80deea, 35%), 20%);
-@base-color: #80deea;
+@accent-color: #a28832;
+@accent-text-color: desaturate(darken(#ffd54f, 35%), 20%);
+@base-color: #ffd54f;
 :root {
    font-size: 16px;
 }

```

**Comment by WoodyWoodsta** [comment]
+1

**Comment by silvestreh** [comment]
yes, this is supposed to work like that.

**Comment by WoodyWoodsta** [comment]
Any chance you could put that in the .gitignore then? Makes PRs a little cleaner :smile:

**Comment by silvestreh** [comment]
If the file is not present, the theme would fail to load because is required inside `index.less`. So ignoring it is kinda out of the question. The contents of `custom.less` are overwritten when the theme is loaded, so you won't override other people's settings.

**Comment by WoodyWoodsta** [comment]
Ok bummer. I tried `@import (optional) "custom"` in `index.less` to no avail - not entirely sure why the import options aren't working. 

I see that when the theme activates after settings changes, it writes to `custom.less` which will obviously create the file if it isn't there. Would be great if this happened on any activation if the file does not exist (initial activation).

I'm going to lengths, because pulling into dirty repos can end up in a bit of a mess, save for the effort.

**Comment by silvestreh** [comment]
@WoodyWoodsta there's an updated [CONTRIBUTING guide](https://github.com/silvestreh/atom-material-ui/blob/master/CONTRIBUTING.md#code-contributions) that you'd probably want to check out. Specifically the Code contributions section that briefly talks about ignoring your own theme settings.

**Comment by WoodyWoodsta** [comment]
Aha! That looks good, thanks!
