### ISSUE TITLE
Tab icon misalignment

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#172]
Tab icons appear misaligned, specifically the git diff notification!
![screenshot from 2015-12-30 07 28 55](https://cloud.githubusercontent.com/assets/8268040/12046721/0c2f80fa-aec7-11e5-9dd2-99fcbf57c10f.png)

**Comment by WoodyWoodsta** [comment]
Comparing a few other themes, I think this one might be with file icons package. Not sure what others' thoughts are on the alignment on the git diff indicator. An aside - it looks a little like a linting indicator, which is what I first thought it was :stuck_out_tongue_closed_eyes:

**Comment by silvestreh** [comment]
Did you change the tab bar size? If so, that's why it might look odd.

**Comment by WoodyWoodsta** [comment]
Yup! Compact tab bar is causing the alignment issue - I see you have a fixed `top` property. If you want, I can PR with it fixed for compact tab bar layout?

**Comment by silvestreh** [comment]
Just pushed a fix for this :smile:
