### ISSUE TITLE
Tree view color

### ISSUE THREAD

**Issue by Echosgraphik** [silvestreh/atom-material-ui#175]
Hi,

Very nice theme.
I've a little problem. I do not know how to have the same colors in the tree view like your screenshot. In mine, all is just white.

![atom](https://cloud.githubusercontent.com/assets/1105011/12149740/adb582c4-b4a5-11e5-9d85-f53f30d483f2.jpg)

Regards

**Comment by silvestreh** [comment]
You're running version `0.8.0` from APM (latest stable). The screenshots are from the development version which you can clone from the repo. More info on that in the [CONTRIBUTING section of the README file](https://github.com/silvestreh/atom-material-ui#contributing).

**Comment by Echosgraphik** [comment]
Thanks.

Unfortunatly, the tree view is always colorless

**Comment by silvestreh** [comment]
Check the theme's settings. You're probably using default values :smile:

**Comment by Echosgraphik** [comment]
Thank you. This is my settings :

![1](https://cloud.githubusercontent.com/assets/1105011/12165564/4a227de6-b51f-11e5-985c-607955f382d3.jpg)
![2](https://cloud.githubusercontent.com/assets/1105011/12165581/65ab4246-b51f-11e5-937d-60a66e24629b.jpg)

**Comment by silvestreh** [comment]
Yep, you're still using the stable version. The screenshots in the repository are from the development version. If you want to install it then do this in a terminal:

```shell
apm uninstall atom-material-ui
git clone git@github.com:silvestreh/atom-material-ui.git
cd atom-material-ui/
apm link && apm install
```

And then restart atom.
