### ISSUE TITLE
Slim scrollbars unusable for file tree

### ISSUE THREAD

**Issue by azizov4singree** [silvestreh/atom-material-ui#177]
Unable to scroll scrollbar in file tree or with vertically splitted panels by mouse because resizing action binded to same region.

**Comment by silvestreh** [comment]
This relates to the `0.8.0` version which will be replaced by a completely different codebase soon enough. I'd like to invite you to install the latest development version from this repository and share your (much needed) feedback on it.

Here's how:

```shell
apm uninstall atom-material-ui
git clone git@github.com:silvestreh/atom-material-ui.git
cd atom-material-ui/
apm link && apm install
```

**Comment by azizov4singree** [comment]
@silvestreh, you are right, it works fine in last build, where I can send feedback for you?

**Comment by silvestreh** [comment]
Right here, on GitHub. Open issues for questions, bugs, unexpected behaviors, or send a pull request if you fixed a piece of code or wrote a new feature.

The theme was re-written from scratch and I didn't fork an existing theme this time around, so some things (like third party packages) might break.

Thanks!
