### ISSUE TITLE
Improve styling of foldername-tabs package

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#178]
I'm using the awesome [foldername-tabs](https://atom.io/packages/foldername-tabs) package in combination with this theme. Foldername-tabs replaces the title of each tab with some more path information. 

I was wondering if you could restore the text ellipsis and fix the room for the close button when foldername-tabs package is enabled.

![2016-01-16 19_12_27-settings __10 10 0 203_www_www_sites_www stempunt nu_1 4 2b_wog atom](https://cloud.githubusercontent.com/assets/55841/12373762/28234334-bc85-11e5-827e-3f8349a93a02.png)

***

_Atom 1.4.0_
_Atom Material UI 0.8.0_
_foldername-tabs 0.1.6_

**Comment by silvestreh** [comment]
Hi @jerone. All development efforts are focused on the next version, `1.0`, which is a complete rewrite. You're welcome to try it out. Follow the steps in the [CONTRIBUTING section of the README](https://github.com/silvestreh/atom-material-ui#contributing) file to get the latest (development) version.

**Comment by jerone** [comment]
Yeah I know, tried the pulled 1.0 already. Just wanted to make sure that the foldername-tabs package was included in compatibility tests. If I find the time I'll try the master.

**Comment by silvestreh** [comment]
Here's how it looks on `1.0`.
![captura de pantalla 2016-01-19 a las 18 21 11](https://cloud.githubusercontent.com/assets/1133339/12432340/7e6e5fa2-bed9-11e5-8cdb-6dbf1c002d20.png)

**Comment by silvestreh** [comment]
and here with much more info
![captura de pantalla 2016-01-19 a las 18 28 00](https://cloud.githubusercontent.com/assets/1133339/12432592/edcb87d4-beda-11e5-9181-5bcce994c0d1.png)

**Comment by jerone** [comment]
Awesome :+1:
