### ISSUE TITLE
`file-icons` v1.6.14 introduces tab icon misalignment

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#180]
Just updated to the latest version of `file-icons` and the tab icons are misaligned. Tested `file-icons` with One Dark and Isotope and the issue is not present.

![amui1](https://cloud.githubusercontent.com/assets/8268040/12442838/1281c116-bf5c-11e5-9c29-16a31d1fefb7.png)

**Comment by TobiasBales** [comment]
For me the icons actually are not visible anymore at all

**Comment by silvestreh** [comment]
Which version are you using?

**Comment by silvestreh** [comment]
Ok, just installed the `file-icons` with the development version of material ui and I can see the problem. I just pushed a fix for the development version. 

The latest release, `0.8.0`, is a completely different codebase and I'm no longer supporting it. I hopefully can release the new version sometime soon, but if you want to try it now (which I would encourage) you can do so by following the instructions in the [CONTRIBUTING section of the README file](https://github.com/silvestreh/atom-material-ui#contributing).

**Comment by WoodyWoodsta** [comment]
I've been using from a clone of this repo since `0.8.0` became unusable in Nov last year. Would love to contribute but it's a nightmare keeping the commits clean when `styles/custom.less` is tracked.

Anyhow, thanks for the fix! Really hope that a working version goes up on apm soon.

**Comment by silvestreh** [comment]
Yeah, that `custom.less` thing. It's not really a big issue actually. If you commit your own settings they'll get overwritten by my own. Same goes for you, when I commit my settings Atom overwrites them with your own.

**Comment by WoodyWoodsta** [comment]
Absolutely, that's fine. But if I try to pull changes from upstream, then I have to make sure that I delete that file (or `git reset --hard`) and close atom before I pull. Also, If I have other changes and I want to pull, I can't even stash, because when I reapply the stash, the `custom.less` is always a conflict, thus each time I do that, it adds yet another commit to the history involving the merging of the stash.

Maybe I need more git skill :stuck_out_tongue_closed_eyes:

**Comment by silvestreh** [comment]
Yeah, it can get messy. Unfortunately we'll have to wait until this gets merged: https://github.com/atom/less-cache/pull/8. That way we can use `@import` options.

**Comment by WoodyWoodsta** [comment]
Cool :+1:
