### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by framerate** [silvestreh/atom-material-ui#181]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'addEventListener' of null

```
At /Users/framerate/.atom/packages/atom-material-ui/lib/bindings.coffee:29

TypeError: Cannot read property 'addEventListener' of null
  at Object.module.exports.apply (/Users/framerate/.atom/packages/atom-material-ui/lib/bindings.coffee:29:17)
  at /Users/framerate/.atom/packages/atom-material-ui/lib/atom-material-ui.coffee:126:26

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.3.0
atom-material-syntax, v0.2.10
atom-material-ui, v1.0.1
autocomplete-paths, v1.0.2
circle-ci, v0.10.1
feedback, v0.38.0
file-icons, v1.6.14
language-ejs, v0.2.0
linter, v1.11.3
linter-eslint, v5.2.7
linter-jsonlint, v1.1.4
react, v0.14.1

# Dev
No dev packages
```

**Comment by framerate** [comment]
@silvestreh I know you said the coffee doesn't exist, but atom is telling me I'm up to date. So maybe there's another issue going on here?

**Comment by silvestreh** [comment]
@framerate Yeah, you're using an unpublished version. `1.0.x` had **SO** many issues that I had to pull it and revert to the previous stable release, `0.8.0`.

If you want to revert back to the stable, but outdated, just reinstall the theme and you should be golden. If you want to test the latest features follow these simple steps:

```shell
apm uninstall atom-material-ui
git clone git@github.com:silvestreh/atom-material-ui.git
cd atom-material-ui/
apm link && apm install
```

**Comment by framerate** [comment]
Gotcha. Thanks for this!
