### ISSUE TITLE
<kbd> text not visible on light theme

### ISSUE THREAD

**Issue by stevenwu** [silvestreh/atom-material-ui#185]
Screenshot below:
<img width="375" alt="screen shot 2016-01-29 at 12 45 36 pm" src="https://cloud.githubusercontent.com/assets/312446/12687710/660eb088-c686-11e5-9310-b48ad997b4c0.png">

**Comment by silvestreh** [comment]
Please, share your Atom version, UI Theme version, Syntax theme version, OS, and how to reproduce the bug and I'll reopen the issue.
