### ISSUE TITLE
Dividing Lines

### ISSUE THREAD

**Issue by webcraftniray** [silvestreh/atom-material-ui#186]
Guys... I love the Material UI for Atom.

My only issue it the tree view not having dividing lines between boxes...

This means that when i use something like remote FTP, there is no way of telling between the two tree views. It's also hard to know where to click and drag to widen the treeview block.

**Comment by silvestreh** [comment]
Yeah, that's something I could improve. There are lots of packages that I don't use and could use some tweaks. [Remote-FTP](https://atom.io/packages/remote-ftp) is next in line.

Thanks!

**Comment by silvestreh** [comment]
Actually… now that I think about this issue, it can be solved by enabling shadows (or contrast in panels.) Here's what it looks like now:

![captura de pantalla 2016-02-19 a las 14 57 51](https://cloud.githubusercontent.com/assets/1133339/13184181/2c532132-d719-11e5-91a4-129d23262efa.png)

**Comment by webcraftniray** [comment]
:+1:
