### ISSUE TITLE
Flex Tool Bar package

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#188]
[Flex Tool Bar package](https://atom.io/packages/flex-tool-bar) enhances the [Tool Bar package](https://atom.io/packages/tool-bar). One of those features is to add a button when Atom is in dev mode. By default those buttons are [colored red](https://github.com/cakecatz/flex-toolbar/blob/master/styles/flex-tool-bar.less#L4). Material UI theme is overriding that color, making it only visible on hover.

***

_Atom 1.5.0-beta2
Material UI https://github.com/silvestreh/atom-material-ui/commit/0b24be68918294ccd837b98c301a5a06ffdff0f4
Tool Bar 0.2.0
Flex Tool Bar 0.7.3_

**Comment by silvestreh** [comment]
I'm not sure how to reproduce this one. I have both packages installed, yet I fail to see those extra buttons.

**Comment by jerone** [comment]
Ah, you have to add an extra property in your cson (it's not documented on the [readme](https://github.com/cakecatz/flex-toolbar#flex-tool-bar), only shown in the [example](https://github.com/cakecatz/flex-toolbar#sample-code)):

```cson
  {
    type: "button"
    icon: "document"
    callback: "application:new-file"
    tooltip: "New File"
    iconset: "ion"
    mode: "dev"
  }
```

**Comment by silvestreh** [comment]
This is how they look now.

![captura de pantalla 2016-02-02 a las 23 55 56](https://cloud.githubusercontent.com/assets/1133339/12771500/8884d360-ca08-11e5-9fe2-ace4b0845803.png)

**Comment by jerone** [comment]
Very cool! I wasn't planning to introduce badges to the Too Bar anytime soon so this is fine.

**Comment by jerone** [comment]
The new dev icons overlap a bit to much of the button icons:
![atom-material-ui-tool-bar-dev](https://cloud.githubusercontent.com/assets/55841/12895256/c243e392-ce9b-11e5-8aab-d3e700621dfa.png)

**Comment by silvestreh** [comment]
What I find odd about your screenshot is that the badges have black color instead of white. I'll take a look at their positioning.

**Comment by jerone** [comment]
I'm running 1864afb1fbd3b3a1a5ec33e12e4361a3bb173d13 from 3 feb. Color is `#263238`.

**Comment by jerone** [comment]
Please reopen this issue as per https://github.com/silvestreh/atom-material-ui/issues/188#issuecomment-181513997

**Comment by jerone** [comment]
Ah, this happens when enabling the setting "Compact Tab Bar".

**Comment by jerone** [comment]
Did some testing and found a few (small) issues:

1. Dev icons overlap buttons, see https://github.com/silvestreh/atom-material-ui/issues/188#issuecomment-181513997
2. Horizontal tool bar has a fixed height, but when there are "too" many buttons they should overflow to a second row. Removing [the](https://github.com/silvestreh/atom-material-ui/blob/master/styles/packages/tool-bar.less#L15) [heights](https://github.com/silvestreh/atom-material-ui/blob/master/styles/packages/tool-bar.less#L161) solved this issue.
3. Vertical tool bar has a [gutter shadow](https://github.com/suda/tool-bar/pull/61) when there are "too" many buttons. Removing [`position:relative;`](https://github.com/silvestreh/atom-material-ui/blob/master/styles/packages/tool-bar.less#L2) solves this.
4. Buttons look off compared to spacers: ![atom-material-ui](https://cloud.githubusercontent.com/assets/55841/13197771/83b5ad6c-d7f7-11e5-8026-c50689330669.png)

**Comment by silvestreh** [comment]
@jerone thanks! I just pushed fixes for those. The shadows from your third list item are still not perfect as I'm using one of the pseudo elements for the theme's panels shadows, so you'll only get the top shadow.

**Comment by jerone** [comment]
Awesome! Confirmed all fixed. To bad about the bottom gutter shadow, that's more useful then the upper shadow.

**Comment by silvestreh** [comment]
I'll see if I can refactor that piece of code to avoid using it :smile:

**Comment by silvestreh** [comment]
Actually… now that I took a better look at it… I'm not using that pseudo element at all. I was hiding it for some reason… maybe I thought it was some glitch and didn't understand what it was for.

Anyway, it's been fixed now :)
