### ISSUE TITLE
Tool Bar package spacer

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#189]
Spacers from the [Tool Bar package](https://atom.io/packages/tool-bar) are invisible.

***

_Atom 1.5.0-beta2
Material UI https://github.com/silvestreh/atom-material-ui/commit/0b24be68918294ccd837b98c301a5a06ffdff0f4
Tool Bar 0.2.0_

**Comment by silvestreh** [comment]
Yes, this was intentional. I'll make them visible to follow [the spec](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Q05OWk5YLUh0NGc/components_menus_usage6.png).

**Comment by jerone** [comment]
Great!
