### ISSUE TITLE
0.4.11 makes the entire UI light

### ISSUE THREAD

**Issue by rjv** [silvestreh/atom-material-ui#19]
Not entirely sure how to describe this other than providing a screenshot. I updated to the latest version and it turned Atom's UI to a light-themed skin. I'm using Windows 7, Atom v1.0.0.

![screenshot at 153734](https://cloud.githubusercontent.com/assets/532439/8416638/0f0741a6-1e75-11e5-957a-ecb363da2602.png)

**Comment by silvestreh** [comment]
Which syntax theme are you using?

**Comment by silvestreh** [comment]
The UI theme picks up background and text colors from the syntax theme. Some syntax themes might not look good, especially light syntax themes.

**Comment by rjv** [comment]
I'm using the Atom Material syntax theme.

![screenshot at 175024](https://cloud.githubusercontent.com/assets/532439/8419390/5fc7a1c8-1e87-11e5-96c4-b5e0cdef8599.png)

**Comment by silvestreh** [comment]
OOOOK… That's pretty odd. I'm betting you tried switching themes for a bit. Or restart Atom.

I can't reproduce this. Did you try reinstalling the theme?

**Comment by rjv** [comment]
Yeah very odd - I tried switching to different themes and then switching back, but it wouldn't "let go" of the light skin. It happened solely by me installing an upgrade. I uninstalled both themes per your recommendation and it got me back to the dark skin. Thanks.

**Comment by seanwash** [comment]
FWIW I had this happen to me too. Uninstalling and reinstalling both fixed it.

**Comment by silvestreh** [comment]
Yeah, I came across it once while developing the theme. I figured it was an Atom bug, but I really am not sure about it. I don't think it's related to this theme though.
