### ISSUE TITLE
Font blurry when Atom webview doesn't have focus

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#190]
See tabs and Tool Bar: 
![Atom Material UI](https://cloud.githubusercontent.com/assets/55841/12761713/6734ad8c-c9ec-11e5-8c55-72b748509535.png)

It happens when Atom webview loses focus. You can reproduce it by having two different windows open and switch focus between them. Other way to reproduce is to open the Developer Tools and give that focus.

_Atom 1.5.0-beta2
Material UI https://github.com/silvestreh/atom-material-ui/commit/0b24be68918294ccd837b98c301a5a06ffdff0f4
Windows 7_

**Comment by silvestreh** [comment]
Nice catch. Might be windows-only though as I can't reproduce it. 

Unfocused windows have a `-webkit-filter` effect applied that might be causing this.

**Comment by jerone** [comment]
I searched through all styles and inherited styles on the text in a tab, while focus to dev tools, and couldn't find anything about `-webkit-filter` or any other property. Could it be Chromium...

**Comment by jerone** [comment]
It's not only the text that's blurry, but also the background color changes (above focused, below blurred): 
![atom material ui blurry](https://cloud.githubusercontent.com/assets/55841/12764032/d9dd2bec-c9f7-11e5-9de2-c6cf9b992402.png)

**Comment by silvestreh** [comment]
This is from `tabs.less`

```css
.is-blurred .tinted-tab-bar .tab-bar:not([data-reactid]) {
    -webkit-filter: grayscale(0.65) brightness(1.25);
}
```

![focus](https://cloud.githubusercontent.com/assets/1133339/12771149/b0451d68-ca05-11e5-8c36-9b9bc09ddca9.png)

**Comment by silvestreh** [comment]
@jerone I recently removed the filters. Could you check if this solves your issue?

**Comment by jerone** [comment]
This no longer seems to be an issue. Thanks!
