### ISSUE TITLE
Atom-Build looks ugly with Material-Design

### ISSUE THREAD

**Issue by dkerzig** [silvestreh/atom-material-ui#191]
(I am not sure if this belongs more to the [build-package](https://atom.io/packages/build), if yes please let me know.)

I use the Material-Design theme and Atom-Build on a daily basis and have to admit (even if the positioning got adjusted a bit in the last update of `build`) that the style of the side-panel in which the build-output is shown just not fits into the rest of the editor-theme. I've included a screenshots, my main pain-points are:

- The Action-Buttons in the right upper corner are looking so curiously stacked
- The background-color of the output should be the same like the tree-view in at the left. Otherwise it's so hard to see the end of the opened file and the beginning of the build-process sometimes.
- The time how long the process is running sticks at the completely wrong place without any padding or so. This should have the same typographic styles like the tab-names and should be positioned left-aligned
- The terminal output should have a padding-left
- Optionally: The terminal output could have a smaller font-size than the base

So If this belongs to this package I would be even proud to do it by myself but I really don't know where to start, I have never developed an atom package nor a theme. And I don't know how to specifically target this build-panel.

![atom-build-material](https://cloud.githubusercontent.com/assets/3930150/12788417/ab2bba0a-ca99-11e5-9939-fb18c66b8053.png)

**Comment by silvestreh** [comment]
How's this for a change?

![captura de pantalla 2016-02-20 a las 21 50 09](https://cloud.githubusercontent.com/assets/1133339/13200185/6e634274-d81c-11e5-8436-c5058476b9d2.png)

**Comment by dkerzig** [comment]
Awesome, you made my day @silvestreh. I really appreciate your commitment to make it a joy for others to do their jobs! 
Just one more thing, I'm using this panel always orientated to the right instead of bottom (you can change this in the settings) and with that the top-bar could have the same size like the tab-bar next to it (maybe it's because I'm using small sized tabs with Material-UI). And the icons could be equally distributed and aligned to the left or so.

Thanks!
Regards from Germany.

**Comment by dkerzig** [comment]
I also noticed another thing, unfortunately I am not able to scroll until the last line :/ 

![build in atom](https://cloud.githubusercontent.com/assets/3930150/13496821/a27e2c2e-e152-11e5-888a-8939f4d7bb13.png)


Thanks for your patience, Dennis!
