### ISSUE TITLE
Rewrite Issue - File Icons Misaligned

### ISSUE THREAD

**Issue by JamesCoyle** [silvestreh/atom-material-ui#192]
The file icons in the tabs are misaligned for me. 

![image](https://cloud.githubusercontent.com/assets/10384436/12865834/2fef7002-ccb0-11e5-938e-fe39a9cfb7aa.png)

**Comment by silvestreh** [comment]
Not for me.

![captura de pantalla 2016-02-09 a las 19 10 57](https://cloud.githubusercontent.com/assets/1133339/12932293/e4abe8f6-cf60-11e5-9e3b-f255656abe2d.png)

**Comment by JamesCoyle** [comment]
Any idea what's causing it?

**Comment by JamesCoyle** [comment]
Weird... I remerged with upstream and it's fine now.

**Comment by silvestreh** [comment]
I remember removing all "icon-related" code from Material UI to avoid these kind of issues… well, except for the right margin in tabs and forcing them to be the same color as the filename text.
