### ISSUE TITLE
No more colored tab bar and less color options?

### ISSUE THREAD

**Issue by victorleblais** [silvestreh/atom-material-ui#194]
Hi,

I've been using this theme for a while now and I had to reinstall my Atom environment from scratch.

And to my despair, it looks way different that it used to.

Here is a screenshot from this repository's .README, and that's how it used to look like:

![Previous look of Material-UI](https://camo.githubusercontent.com/545d5462428d9da9c99c1fc0cbd82e47488fd690/687474703a2f2f692e696d6775722e636f6d2f457850596d4a592e706e67)

And it had those settings (screenshot from issue #119): 
![Previous Material-UI settings](https://cloud.githubusercontent.com/assets/1133339/11386077/f544027a-92fc-11e5-8825-f5cc35586f51.png)

But now it looks like that (note: no more colored bar at the top):
![New look of Material-UI](https://raw.githubusercontent.com/leo/material-ui/screenshots/with-code.png)

And you can only choose from 10 accent colors:
![New settings of Material-UI](http://i.imgur.com/zgxTZp2.png)

Questions:
* Why removing options?
* Do you plan to implement them back?

**Comment by jerone** [comment]
> But now it looks like that (note: no more colored bar at the top):

Had the same situation, but have not tried to reproduce. If my memory serves me right, you need to enable "Tinted Tab Bar" option and restart Atom.

**Comment by victorleblais** [comment]
> enable "Tinted Tab Bar" option

Except, I do not have this option. [Here's a webm video](http://webm.host/b48f9/) showing the available settings I have.

Note: I'm on Atom 1.5.0-beta3 and material-ui 0.8.1

**Comment by silvestreh** [comment]
@victorleblais That's the reason. You're using version `0.8.1`. The new options are available only in the development version. 

You can install the development version through a terminal like so:

```shell
git clone git@github.com:silvestreh/atom-material-ui.git
cd atom-material-ui/
apm link -d && apm install
```

This will install Material UI only in dev mode, meaning you have to run `atom --dev` to use it and both versions, dev and stable, can coexist. If you don't want to use dev mode, just remove de `-d` flag in `apm link` command above.

**Comment by silvestreh** [comment]
Also, the screenshot you posted:

![](https://raw.githubusercontent.com/leo/material-ui/screenshots/with-code.png)

Is another material design theme with the same name. Its author should've named the package slightly different to avoid confusion.

**Comment by victorleblais** [comment]
Sorry for that mistake.

Thanks for clarifying the situation. It's pretty weird since I definitely had the colored tab bar before by installing the package using the integrated manager, not by manually cloning and running it in dev mode.

Oh well. Thanks again for your answer and your work !

**Comment by silvestreh** [comment]
@victorleblais ah yes, you were running an unpublished version. A couple months ago I thought it was ready for primetime but I was awfully wrong, so I had to pull the update.
