### ISSUE TITLE
Rewrite Issue - Perfect Scrollbar Bug (Again :/)

### ISSUE THREAD

**Issue by JamesCoyle** [silvestreh/atom-material-ui#196]
I made a quick video to show what sometimes happens:
https://www.youtube.com/watch?v=bxBp4iUwDLA

It seems that the error I was getting about the perfect scrollbar is now occurring in the devtools console causing it to be opened every time the error is thrown - which happens to be when the devtools are closed.

**Comment by silvestreh** [comment]
I'm guessing that's not Atom's tree-view package, is it?

**Comment by JamesCoyle** [comment]
It happens even when I don't have any tree views. It seems like some code either in the theme or the perfect scrollbar package needs to incorporate some error handling.

**Comment by silvestreh** [comment]
Care to share which packages you have installed so I can try to reproduce it? Run `apm list --installed` in a terminal.

**Comment by silvestreh** [comment]
Just removed PS in the latest commit. I'll probably reimplement it in the future… maybe as a separate package.

**Comment by JamesCoyle** [comment]
As requested and for future reference: 
├── atom-material-ui@0.8.1
├── autohide-tree-view@0.25.1
├── editorconfig@1.2.4
├── file-icons@1.6.14
├── flex-tool-bar@0.7.3
├── highlight-line@0.11.1
├── linter@1.11.3
├── linter-cpplint@1.0.1
├── linter-flake8@1.10.1
├── linter-htmlhint@1.0.2
├── linter-jshint@2.0.2
├── linter-php@1.1.8
├── minimap@4.19.0
├── minimap-autohide@0.10.1
├── minimap-bookmarks@0.2.0
├── minimap-find-and-replace@4.4.0
├── minimap-highlight-selected@4.3.1
├── minimap-selection@4.3.1
├── open-html-in-browser@0.1.0
├── Remote-FTP@0.7.20
├── sync-settings@0.6.0
├── tool-bar@0.2.1
└── valign@1.1.3

**Comment by silvestreh** [comment]
BTW, PS won't be needed anymore since I refactored the "tree-view blend with tab-bar" feature. :smile:
