### ISSUE TITLE
Close button doesn't contrast well in Notifications

### ISSUE THREAD

**Issue by aniforprez** [silvestreh/atom-material-ui#201]
Hey man! Your update looks freaking amazing and is the material UI that I always wanted! This is now my theme of choice!

Issue is that the close button on notifications looks a bit too dim IMO. Can't get a screencap cause they disappear too quickly and I don't know how to get a notification to test.

**Comment by silvestreh** [comment]
You can paste this snippet in the dev console:

```javascript
atom.notifications.addInfo("Test Notification", { dismissable: true });
atom.notifications.addError("Test Notification", { dismissable: true });
atom.notifications.addFatalError("Test Notification", { dismissable: true });
atom.notifications.addWarning("Test Notification", { dismissable: true });
atom.notifications.addSuccess("Test Notification", { dismissable: true });
```

**Comment by aniforprez** [comment]
Yes, it looks much better now. Thanks! Again, great theme!
