### ISSUE TITLE
Colors of tab icons gone.

### ISSUE THREAD

**Issue by SpikeShape** [silvestreh/atom-material-ui#202]
After the recent update I realized that the icons on the tab bar are unified to use the accent color.
But I would like to keep their original color because this helps me to see which file is which since I have a lot of files that have the same name but are a different file type.

Is this feature still there and I am just missing it or did you remove that to make the icons work with the tinted tab bar?

**Comment by haitamattar** [comment]
view the code of atom material ui
open the folder "styles" and open "tabs.less"
at the end of the less file comment or remove "color: @accent-text-color !important; "
`.has-custom-icons .tab-bar:not([data-reactid]) .tab {
    .title[data-path] {
        &::before {
            // Override icon color in icon-packages as it can hurt readability
            // with some @base-color.
            color: @accent-text-color !important; 
            margin-right: 1rem;
        }
    }
}`

**Comment by SpikeShape** [comment]
Fair enough but thats not how it's supposed to be done since this change is gone when another update arrives. So although your solution works perfectly fine it's more of a workaround rather than a fix.

But I will use your solution until @silvestreh can give any feedback on this matter.
Thank you very much!

**Comment by haitamattar** [comment]
yes you are right, the new update is a mess. Like why should a theme change my editor font and icon colors which is an other extension.

**Comment by SpikeShape** [comment]
Thats not what I wanted to say. I meant that I don't want to mess around with the original theme files since these changes are gone when an update is pushed.

But sadly I can't argue with your statement... I assume it was just too much of an overhaul of the whole theme so I assume things got missing.

I guess patience will do best. Until then a workaround has to do the trick.

**Comment by silvestreh** [comment]
@haitamattar I'm not changing your syntax font in this theme. I am, however, changing the font smoothing method.

The problem of not overriding the icon color is that if you set a `@base-color` similar to, say, the color of the coffee script icon, then I'd have lots of issues about some file type icon not being visible while others are.

I agree that overriding another package's setting is not optimal, it's not something that I *enjoy* doing, but I'm trying to avoid the situation I described above.

**Comment by SpikeShape** [comment]
I totally get that. Thats why I would suggest an option in the settings menu to either set the color of the icons or keep its original color.
Since I personally would like to avoid the tinted tabs I would leave the colors of the icons as they are while I others, who choose to opt in to having tinted tabs, might want to unify their colors.
