### ISSUE TITLE
Font weight displayed wrong

### ISSUE THREAD

**Issue by SpikeShape** [silvestreh/atom-material-ui#203]
Since the last update my editor font that used to be bold-ish looks like a medium or light font. I am using the font called 'Hack' from the braver/fonts package.
When I select a different theme, the font goes back to normal but when using your material UI, it's rather thin again.

Edit: removed typo

**Comment by risc12** [comment]
Same problem here, after the new update rendering of fonts is strange.

**Comment by silvestreh** [comment]
Fonts are antialiased by default. If you wish to not use antialiasing open your personal stylesheets located in `~/.atom/styles.less` and paste the following:

```css
:root {
    -webkit-font-smoothing: subpixel-antialiased;
}
```

This `subpixel-antialiased` mode is the default in webkit, but it renders fonts in an "incorrect" way as light fonts often look regular, and regular fonts look semi-bold (which, it seems to be the way you guys want it to be)

**Comment by SpikeShape** [comment]
Thank you for the feedback.
So that means that all themes are doing it wrong at the moment?

**Comment by silvestreh** [comment]
No, not themes. Chrome is doing it wrong. Actually, it's not about being right or wrong, but fonts look closer to what they should look like if you antialias them using the `antialiased` value, like this:

```css
:root {
    -webkit-font-smoothing: antialiased;
}
```
