### ISSUE TITLE
User interface font size

### ISSUE THREAD

**Issue by Eldair** [silvestreh/atom-material-ui#204]
Hello,

I tried changing user interface font size, but no matter what value I insert, everything remains the same.

**Comment by Kais-DkM** [comment]
I can confirm this issue.
Right after the upgrade, user interface font size remains 16pt whatever value I insert.

**Comment by k4nar** [comment]
I'm also having this issue, even after restarting atom.

**Comment by FrontDevs** [comment]
+1

**Comment by bdemirel** [comment]
Same here. Mine even changed the settings to default after the update.
