### ISSUE TITLE
Colors of Git status in tree view

### ISSUE THREAD

**Issue by SpikeShape** [silvestreh/atom-material-ui#205]
Since the last update the colors of changed or added files are gone when it is focused. It seems to be overwritten by the primary color.
I liked the previous version more because both color and background of changed or added files changed into green and yellow respectively. I found this coloring method really good and got used to it in a heartbeat.
Is there a way of adding this as an option in your theme's settings?

**Comment by WoodyWoodsta** [comment]
I agree with this! Now have to focus another file to see the status of the
previous.
