### ISSUE TITLE
Tree view spacing

### ISSUE THREAD

**Issue by glasseyes42** [silvestreh/atom-material-ui#206]
Have a large gap between the icon and text... Cannot seem to get rid of it no matter what I try in the settings, resetting workspaces, etc.

**Comment by SpikeShape** [comment]
I second this. It seems a bit too much.
One could try to reduce it by setting custom styles without having to touch the theme itself, though.

**Comment by glasseyes42** [comment]
```less
.list-tree.has-collapsable-children .list-nested-item > .list-tree > li {
   padding-left: 0.5rem;
 }
.compact-tree-view {
  .tree-view {

    .name.icon::before {
      margin-right: 0.5rem;
    }

    li:not(.list-nested-item), li.list-nested-item > .list-item {
      line-height: 1.5rem;
    }
  }
}```

...works for me in "my stylesheet".
The padding-left explicitly takes care of the the icon issue. The rest just deals with the tree feeling a little expanded for my taste even in compact mode.

**Comment by silvestreh** [comment]
Yes, the spacing is *almost* in line with the design spec. It should be more spacious, but I still made it a little more compact than the spec.

![](https://camo.githubusercontent.com/6a1bc710dd1bdb557115878580e9eade1ba252e2/68747470733a2f2f6d6174657269616c2d64657369676e2e73746f726167652e676f6f676c65617069732e636f6d2f7075626c6973682f6d6174657269616c5f765f342f6d6174657269616c5f6578745f7075626c6973682f3042364f6b647a373574715173597a645652476f7a52485659626d732f636f6d706f6e656e74735f6c697374735f6b65796c696e6573312e706e67)

You can use @glasseyes42 snippet to change it.
