### ISSUE TITLE
blurry icons and file-tree spacing

### ISSUE THREAD

**Issue by stryju** [silvestreh/atom-material-ui#207]
after the latest update, file-tree (and tab) the file-icons are blurry and the spacing is way too big (even in "compact" mode)

![screen shot 2016-02-22 at 11 47 55 am](https://cloud.githubusercontent.com/assets/25367/13217423/3080a138-d95a-11e5-883d-30ad64c6aab9.png)

**Comment by silvestreh** [comment]
There are no styles changing the icons in the latest release (other than margins.) The spacing follows the material design spec.

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsYzdVRGozRHVYbms/components_lists_keylines1.png)

**Comment by WoodyWoodsta** [comment]
As far as the spacing is concerned, the user has opted for a compact view,
thus the margin on the label text should be reduced proportionally to the
change in line-height.

>

**Comment by silvestreh** [comment]
@WoodyWoodsta sure, it could work that way… actually is a pretty good idea. I'll implement it for the next update.

**Comment by WoodyWoodsta** [comment]
I use MD pretty extensively in the front end work that I do - I've found
its a brilliant design framework but very ideal. Very suited to small
scale, simple apps. Atom isn't as small scale, thus bending the odd length
to make it user friendly is a good thing, IMO! Looking good though 👍

>

**Comment by jerone** [comment]
:+1: Could this also be extended to the expand/collapse arrows in the tree?

**Comment by silvestreh** [comment]
@jerone sure thing!

**Comment by stryju** [comment]
great, thanks!
