### ISSUE TITLE
Everything is quite large with 1.1.0 compared to 0.8.1

### ISSUE THREAD

**Issue by hatched** [silvestreh/atom-material-ui#208]
It appears that there were some changes with 1.1.0 that makes the UI very large. I'm also not able to change the font size any lower than 10 to try and reduce it back down to its 0.8.1 size. Was this intentional, or can we get the previous sizes back?

**Comment by silvestreh** [comment]
Why would you want to use anything lower than 10? Here's what 10 look like:

![captura de pantalla 2016-02-22 a las 12 57 09](https://cloud.githubusercontent.com/assets/1133339/13223639/d890b8f0-d963-11e5-8c13-6047fcc99488.png)

Also, update to 1.1.1 where the font size option was fixed and now it actually works.

**Comment by hatched** [comment]
Looks like 1.1.1 fixed it :) thanks!
