### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by Nonlimit** [silvestreh/atom-material-ui#21]
![bug](https://cloud.githubusercontent.com/assets/11960153/8416157/6e0acde4-1eac-11e5-8136-122e864fb1b8.PNG)
Offset text in tabs. If you include a standard topic (any) and click on the Color Picker then the text in the tabs will be displayed normally

**Comment by silvestreh** [comment]
That's a nice catch. I didn't have this package installed. I'll work on a fix. Thanks!

**Comment by silvestreh** [comment]
I just pushed a fix. Let me know if it's any better.

**Comment by Nonlimit** [comment]
Wonderful works,thanks)
