### ISSUE TITLE
Specified User interface font size does not persist across window reloads

### ISSUE THREAD

**Issue by rjv** [silvestreh/atom-material-ui#212]
Setting the **User interface font size** does not persist across window reloads.

**Reproduction Steps:**

1. Navigate to _Atom Material UI_ settings and change **User interface font size** from the default _16_ to _14_. 
2. Reload the editor window.

**Expected behavior:**

The smaller UI font size persists.

**Observed behavior:**

The UI font appears as if it were set back to the default despite **User interface font size** still being set to _14_.

**Atom version:** 1.5.3
**OS and version:** Windows 10

**Installed packages:**

├── advanced-open-file@0.14.2
├── angularjs@0.3.4
├── atom-beautify@0.28.22
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.1.2
├── custom-invisibles@0.1.2
├── docblockr@0.7.3
├── emmet@2.4.1
├── facebook-syntax@1.0.0
├── file-icons@1.6.15
├── ionic-framework-snippets@1.2.1
├── language-aspx@0.4.0
├── language-cshtml@0.1.1
├── linter@1.11.3
├── linter-eslint@6.0.0
├── linter-php@1.1.8
├── merge-conflicts@1.3.7
├── minimap@4.19.0
├── php-cs-fixer@2.5.6
├── pigments@0.24.1
├── project-manager@2.7.6
├── react@0.14.1
├── Sublime-Style-Column-Selection@1.5.1
└── todo-show@1.3.0

**Additional information:**

* Problem can be reproduced in safe mode: N/A
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by jamby** [comment]
Can confirm, this is also happening with me too.

**Comment by silvestreh** [comment]
Thanks! Just pushed a fix. I'll publish an update ASAP.
