### ISSUE TITLE
evrything is quite big

### ISSUE THREAD

**Issue by veegee2** [silvestreh/atom-material-ui#214]
After morning update to, is everything bigger than before. When i change user intarface font size in theme i got some error. Now i update atom to version 1.5.3 and atom-material-ui to version 1.1.2 but the problem persist.

**Comment by silvestreh** [comment]
I don't know what "some error" might be. Please provide more information. Check the [CONTRIBUTING file](https://github.com/silvestreh/atom-material-ui/blob/master/CONTRIBUTING.md) to learn how to fill a proper bug report.

**Comment by xDae** [comment]
+1

**Comment by veegee2** [comment]
I am sorry for that. After reinstall is the size working.
