### ISSUE TITLE
Git file changed indicator not showing on multiple files with the same name

### ISSUE THREAD

**Issue by aniforprez** [silvestreh/atom-material-ui#216]
When opening 2 or more files with the same name, if any of them are changed, the git diff indicator does not show up

**Reproduction Steps:**

1. Open a file in a git repo and add changes and save. Indicator shows up.
2. Open another file with the same name. This adds the folder of each file to the tab name
3. File changed indicator disappears

**Expected behavior:**

The file changed indicator should show up on all files when they are changed and shouldn't disappear when opening multiple files with the same name

**Screenshots and GIFs**

Changed file
![screen shot 2016-02-23 at 12 13 05 pm](https://cloud.githubusercontent.com/assets/993132/13243829/cb3f45a8-da27-11e5-872d-459d5ff8c715.png)

Multiple files of the same name as changed file
![screen shot 2016-02-23 at 12 13 28 pm](https://cloud.githubusercontent.com/assets/993132/13243841/e6f9ef6e-da27-11e5-82dd-9302e04a850c.png)

**Atom version:** 1.5.3
**OS and version:** Mac OSX 10.11.3

**Installed packages:**

Zen@0.16.3
advanced-open-file@0.14.2
aligner@0.19.1
aligner-css@1.2.0
aligner-scss@1.1.0
angularjs@0.3.4
atom-beautify@0.28.22
atom-html-preview@0.1.13
atom-material-syntax@0.4.3
atom-material-syntax-light@0.4.3
atom-material-ui@1.1.0
atom-ternjs@0.13.2
auto-detect-indentation@0.4.2
auto-update-packages@1.0.0
autocomplete-modules@1.4.1
autocomplete-paths@1.0.2
autocomplete-python@1.6.1
bottom-dock@0.3.7
chester-atom-syntax@0.1.1
color-picker@2.1.1
csscomb@0.3.1
docblockr@0.7.3
dracula-theme@1.2.0
dracula-ui@0.3.0
editorconfig@1.2.4
emmet@2.4.1
figlet@0.5.3
file-icons@1.6.14
font-viewer@0.3.1
git-control@0.4.0
git-diff-details@0.22.0
git-history@3.2.0
git-log@0.4.1
git-plus@5.13.0
gulp-manager@0.2.18
highlight-selected@0.11.2
indentation-indicator@0.6.0
linter@1.11.3
linter-coffeelint@1.1.2
linter-eslint@6.0.0
linter-htmlhint@1.0.2
linter-jscs@3.4.6
linter-jshint@2.0.2
linter-jsonlint@1.1.5
merge-conflicts@1.3.7
minimap@4.19.0
minimap-bookmarks@0.2.0
minimap-find-and-replace@4.4.0
minimap-git-diff@4.1.8
minimap-highlight-selected@4.3.1
minimap-pigments@0.1.7
minimap-selection@4.3.1
native-ui@0.17.0
open-in-browser@0.4.6
pane-split-moves-tab@0.0.3
pdf-view@0.39.0
pigments@0.24.1
pretty-json@0.4.1
project-manager@2.7.6
project-ring@0.36.2
project-viewer@0.2.30
release-notes@0.53.0
slack-ui@0.7.0
sort-lines@0.14.0
split-diff@0.5.5
swackets@0.10.0
sync-settings@0.6.0
tab-switcher@1.3.3
tabs-to-spaces@1.0.2
todo-show@1.3.0
toggle-quotes@1.0.0
tree-view-breadcrumb@0.8.1
turbo-javascript@1.4.0

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by SpikeShape** [comment]
Is this even part of this theme? I can't find any option to switch on these dots to represent the git status.

**Comment by aniforprez** [comment]
It's a setting in the default Atom Tabs package. It gives you the option to 'Enable VCS Coloring'.

**Comment by SpikeShape** [comment]
I totally missed that. Thank you for that!

**Comment by silvestreh** [comment]
Looks like this is a bug with the `tab-bar` package.

**Comment by silvestreh** [comment]
Nope, it's a bug within this theme! :smile:
