### ISSUE TITLE
Generate Accent Color option causes atom editor to whitescreen 

### ISSUE THREAD

**Issue by James-Byrne** [silvestreh/atom-material-ui#219]
Just installed a new atom-material update which included the new features for colouring the top bar and generating an accent colour based of chosen colours. After turning on the Generate Accent Colours option Atom Material crashed with a ream of errors showing within the editor. I thought nothing of it and restarted atom to fix the issue. Atom now displays as a white screen with the dev tools open. 

**Reproduction Steps** 

- Open Atom 
- Go to packages/Atom-Material
- Turn on the Generate Accent Colour option

**Expected Behaviour**

- Atom should Generate custom accent colours 

**Observed Behaviour**

- Atom Material Crashes with errors 

**Resulting Screenshot**

![screen shot 2016-02-23 at 10 54 53](https://cloud.githubusercontent.com/assets/6131765/13249589/10fbc02c-da1d-11e5-9573-582c1d3718c8.png)

**Atom Version**: Latest Stable (Unable to check atm)
**OS Version** : OSX El Capitan version : 10.11.3 (15D21)

**Installed Packages** : 

![screen shot 2016-02-23 at 10 58 53](https://cloud.githubusercontent.com/assets/6131765/13249600/16231c4e-da1d-11e5-848e-7881107d7aab.png)

**Comment by James-Byrne** [comment]
Uninstalling atom-material fixes the issue (allows use of atom again) but re-installing presents the error again.

**Comment by silvestreh** [comment]
This is a bug with `settings-view` where it sometimes returns an invalid HEX color. There's nothing I can do about it, except filing a bug report with them ([which I already did](https://github.com/atom/settings-view/issues/712)).

If you'd like, you can run this in a dev console to reset the colors back to default

```javascript
atom.config.set('atom-material-ui.colors')
```

Also, try to avoid picking very dark colors as those are the ones that seem to trigger this bug.

**Comment by James-Byrne** [comment]
That fixed the issue for me, Ill avoid using it for now and keep an eye on your issue. Cheers

**Comment by silvestreh** [comment]
Yeah, sorry about that. I'm refactoring this bit of code to better handle this problem. Looks like it fails with pink-ish colors most of the time.
