### ISSUE TITLE
My user styles

### ISSUE THREAD

**Issue by larsenwork** [silvestreh/atom-material-ui#22]
Thanks for a great theme. I find this improves the UI a bit (clear sans could be substituted with Roboto although clear sans is better for UI. 
```
@font-size: 13px;
@font-family: 'Clear Sans';
body, atom-workspace {
  font-size: @font-size;
  font-family: @font-family;
}
.tree-view,
.tab-bar .tab,
atom-text-editor[mini],
.btn,
.author {
  font-size: @font-size;
  font-family: @font-family;
  letter-spacing: 0.03em;
}
```
minimal tree view
```
.tree-view {
  padding-left: 0;
  margin-left: -5px;
  margin-top: 5px;
  &.list-tree.has-collapsable-children .list-nested-item {
    > .list-item:before {
      content: "";
    }
    &.collapsed > .list-item:before {
      content: "";
    }
    > .list-tree > li {
      padding-left: 10px;
    }
  }
}
```

Just meant as inspiration. Close when read :+1:

**Comment by silvestreh** [comment]
I thought about using Roboto for most of the UI though the tree view looked terrible with Roboto. On top of that it would add a couple MB to the download, so I'm really torn about it.

I'm already including the fonts Roboto Mono and Material Design Icons. But yeah, I'll consider it. Thanks.
