### ISSUE TITLE
Tabs too small

### ISSUE THREAD

**Issue by SK83RJOSH** [silvestreh/atom-material-ui#221]
Tabs are generally too small (width-wise) after this most recent update. The following screenshot illustrates this problem fairly well, as I don't think a default atom feature / tab title should be getting cut off.

![evrzr1ax](https://cloud.githubusercontent.com/assets/1371787/13263648/77a53554-da38-11e5-8065-446478d9ed55.png)

**Comment by SK83RJOSH** [comment]
Also I understand this is entirely a matter of preference, but I think the width / margin should be bumped up just a tad so this doesn't occur for things like Project Find.

**Comment by silvestreh** [comment]
You can edit your own stylesheet located in `~/.atom/styles.less` and give them whatever width you're comfortable with.

```css
.tab-bar .tab {
    max-width: 16rem;
}
```

**Comment by jared-christensen** [comment]
Is there a way I could make them auto match the width of the text? I tried messing with the css but could not figure it out.
