### ISSUE TITLE
Non-integer fontSize values have issues with the treeView

### ISSUE THREAD

**Issue by SK83RJOSH** [silvestreh/atom-material-ui#223]
When there's a rather large amount of content in the tree view (enough for there to be overflow) you can no longer interact with the tree view. Here's a short video illustrating the problem:

![example](https://cloud.githubusercontent.com/assets/1371787/13263957/f27e0a8e-da39-11e5-937c-088866df6a59.gif)

**Comment by SK83RJOSH** [comment]
This occurs on Atom 1.6.0-beta5.

Additional information:

Items in the tree view do appear to get selected, but the scroll position gets randomly reset and the file preview is never opened.

**Comment by silvestreh** [comment]
I can't reproduce it… Please share more details. Check the CONTRIBUTING file.

**Comment by SK83RJOSH** [comment]
When "blend tree view" is enabled and the current project has a large number of files (and causes the tree view to y-overflow) you are unable to click anything while the tree view is scrolled down.

**Reproduction Steps:**

1. Create a large project with many files and directories / Open a system directory with many files.
2. Enable Blend tree view.
3. Scroll down to the bottom of the tree view.
4. Try to click an object in the tree.

**Expected behavior:**

The object should be highlighted and a file preview should open.

**Observed behavior:**

The object gets highlighted but the scroll position is reset to the top and the file preview is never opened.

**Atom version:** 1.6.0-beta5
**OS and version:** Windows 10

**Installed packages:**

├── atom-material-ui@1.2.0
├── emmet@2.4.1
├── file-icons@1.6.15
├── highlight-selected@0.11.2
├── language-glsl@2.0.1
├── language-lua@0.9.4
├── language-moonscript@1.7.1
├── lesscompile@0.6.0
├── linter@1.11.3
├── linter-less@2.4.2
├── linter-lua@1.0.1
├── love-launcher@0.5.0
├── minimap@4.19.0
├── minimap-bookmarks@0.2.0
├── minimap-find-and-replace@4.4.0
├── minimap-git-diff@4.1.8
├── minimap-highlight-selected@4.3.1
├── minimap-linter@1.1.1
├── minimap-selection@4.3.1
└── monokai@0.18.0

**Additional information:**

* Problem can be reproduced in safe mode: No
* Problem started happening recently, didn't happen in an older version of Atom: Unsure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by silvestreh** [comment]
Still can't reproduce it:

![amu](https://cloud.githubusercontent.com/assets/1133339/13271531/55021b5c-da74-11e5-90a0-4072d90562eb.gif)

Does the dev console output anything useful?

**Comment by SK83RJOSH** [comment]
Nothing useful unfortunately, I've also tried disabling quite a few packages manually and played around with my tree-view / core settings to no avail. :disappointed:

**Comment by SK83RJOSH** [comment]
Aha, found out what it was while looking into an unrelated issue: Certain user interface font-sizes cause the sidebar to break; an example would be 13.5 (which I was using because 14 causes the settings icon to clip  ![pjey4rth](https://cloud.githubusercontent.com/assets/1371787/13272304/0cd158b2-da69-11e5-9eb2-56e69facdf1e.png))

**Comment by silvestreh** [comment]
Got it… I can only reproduce it on Atom 1.6.0-beta5 though…

**Comment by SK83RJOSH** [comment]
I'd say that this is low priority then, could be fixed with a future update and occurs under a pretty obscure circumstance for which there is a workaround (just don't use odd font-sizes). :smile:

**Comment by silvestreh** [comment]
Yeah, or probably just parse that value to ensure it's always an integer while I work on an actual fix :smile:

**Comment by silvestreh** [comment]
Stupid me referenced the wrong issue in commit message. This is solved by d345328a8127cc0a1949b771a69f5817290305e9.
