### ISSUE TITLE
Terminal Plus not working within Atom Material UI 

### ISSUE THREAD

**Issue by James-Byrne** [silvestreh/atom-material-ui#225]
[Short description of problem here]

Since the latest update was I noticed that the terminal plus package no longer works, it still works with other UI themes that I install 

**Reproduction Steps:**

1. Install the terminal plus package 
2. Install the atom-material-ui package 
3. Try to open a new terminal pane 

**Expected behavior:**
A terminal pane should open, displaying the terminal prompt. 

**Observed behavior:**
A terminal pane opens but without displaying the prompt 
[Describe observed behavior here]

**Atom version:**  1.5.3
**OS and version:** OSX El Capitan 10.11.3 (15D21)

**Installed packages:**

├── angular2-snippets@0.3.0
├── angularjs@0.3.4
├── angularjs-snippets@0.10.18
├── atom-beautify@0.28.22
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.2.0
├── atom-ternjs@0.13.2
├── autocomplete-angular-material@0.4.0
├── autocomplete-html-entities@0.1.0
├── autocomplete-ionic-framework@0.2.2
├── chester-atom-syntax@0.1.1
├── ex-mode@0.8.0
├── file-icons@1.6.15
├── git-control@0.4.0
├── imdone-atom@1.3.27
├── ionic-framework-snippets@1.2.1
├── jshint@1.8.3
├── linter@1.11.3
├── linter-csslint@1.3.1
├── linter-tslint@0.7.0
├── merge-conflicts@1.3.7
├── minimap@4.19.0
├── minimap-find-and-replace@4.4.0
├── minimap-git-diff@4.1.8
├── minimap-linter@1.1.1
├── native-ui@0.17.0
├── oceanic-reef-syntax@0.6.0
├── relative-numbers@0.5.0
├── terminal-plus@0.14.5
├── vim-mode@0.64.0
└── wakatime@5.0.8

**Comment by benedictleejh** [comment]
I'd like to add that I'm also facing the same problem on Linux. Funnily enough, it works on OS X 10.10 Yosemite for me.

**Atom version**: 1.5.3
**OS and version**: [Netrunner Rolling](http://www.netrunner.com/)

**Installed Packages**:
├── atom-beautify@0.28.22
├── atom-material-ui@1.2.0
├── file-icons@1.6.15
├── gitignore-snippets@0.2.5
├── gl-light-syntax@2.2.0
├── language-dots@0.0.4
├── language-elm@1.3.2
├── language-pfm@0.82.0
├── linter@1.11.3
├── linter-elm-make@0.4.0
├── markdown-preview-plus@2.2.2
├── minimap@4.19.0
├── minimap-highlight-selected@4.3.1
├── nuclide@0.119.0
├── open-recent@5.0.0
├── pigments@0.24.1
├── terminal-plus@0.14.5
├── tool-bar@0.2.1
└── tool-bar-main@0.0.9

**Comment by James-Byrne** [comment]
Any tips on how I could debug this myself?

**Comment by Alaneor** [comment]
Terminal Plus working just fine for me using the latest Atom Material theme and Terminal Plus on OS X.

**Comment by silvestreh** [comment]
It's working for me on OS X and Windows 10… 

@James-Byrne I really cannot think of much else other than checking the dev console for errors and inspecting the DOM as I'm not familiar with Terminal Plus inner workings.

**Comment by James-Byrne** [comment]
@silvestreh It seems to be an issue with my machine. I have tried removing everything including dotfiles and still no luck. Also no errors thrown at all. Ill keep working on it but I'll close this issue since its specific to my machine. Thanks for the help though
