### ISSUE TITLE
`merge-conflicts` package is with broken styles

### ISSUE THREAD

**Issue by StefanDimov** [silvestreh/atom-material-ui#228]
This is with the Material Theme:

![bug-layout](https://cloud.githubusercontent.com/assets/4311659/13311662/ec390baa-db98-11e5-9919-300df1b2350d.PNG)

This is when I switch to Atom Dark:

![good-one](https://cloud.githubusercontent.com/assets/4311659/13311666/fc364fae-db98-11e5-8ba2-9cde2cfda602.PNG)

The problematic elements are put on top of `<<<<<<< HEAD`, `=======` and '>>>>>>> branch'. They are transparent for some reason, that the problem.

Some of the popup modals aren't styled properly as well (really strange layout).

**Comment by soul-wish** [comment]
I have the same issue with material theme. Some popups are not styled properly (it seems like all styling is missing for *Git Plus* package, for example). The same problem with *merge-conflicts* package. Don't sure what t can be.. Any help would be appreciated.
Here is a screenshot of *Git Plus* popup window:
![screen-material](https://cloud.githubusercontent.com/assets/1968098/13439512/9732190a-dff6-11e5-90a8-ea7ef9a19bce.png)
