### ISSUE TITLE
New Blue Theme Retains Teal Attributes 

### ISSUE THREAD

**Issue by codeman6100** [silvestreh/atom-material-ui#23]
The Blue color theme uses the teal check-boxes in the settings UI.
![screenshot from 2015-06-30 16 14 21](https://cloud.githubusercontent.com/assets/7398125/8440887/2c99a6ea-1f43-11e5-8fe5-6dcd42b76e8b.png)

**Comment by silvestreh** [comment]
Sorry about that! Should be fixed now.

**Comment by codeman6100** [comment]
Looks good!
