### ISSUE TITLE
Ability to disable or move the git status icon in tabs

### ISSUE THREAD

**Issue by jamby** [silvestreh/atom-material-ui#230]
Is there any way to either disable with the git status icon for files in the tabs bar or even moving it over to the right side (to be next to the close button)?

**Comment by silvestreh** [comment]
Yeah, the option to disable it is inside the tabs package.

**Comment by silvestreh** [comment]
Also, moving it to the right might be confusing as there's already an icon indicating wether the file has unsaved changes.

**Comment by jamby** [comment]
So I just put some css in my `styles.less` that would just move it in between the space of the icon and the file name.

```
.tab-bar .tab .title[class*="status-"] {
  padding-left: 0px;
}

.tab-bar .tab .title.status-modified::after {
  left: 1.75em;
  margin-right: 0;
}
```

Seems to do the trick.

**Comment by mattandrews** [comment]
Would be great to be able to disable this – at the moment I'm finding it really confusing (is that indicating unsaved modifications, or VCS changes?).

**Comment by jamby** [comment]
@mattandrews You can disable it. Go to your Atom tabs package, and disable VCS.

**Comment by mattandrews** [comment]
@jamby amazing, didn't realise this was controlled there. Thank you!

**Comment by silvestreh** [comment]
I'm closing this as this functionality is already available within the tabs package (disable VCS coloring) and it's not part of this theme.
