### ISSUE TITLE
Find and Replace Highlight colors

### ISSUE THREAD

**Issue by cumanacr** [silvestreh/atom-material-ui#232]
First, hi, awesome theme you make.

I updated today to version 1.2.0, and notice that the white border that before highlight the words was replace with a teal tone.

It's so subtle that is difficult to know where the words are.

I suggest a color picker to the border color on highlight words with "Find and Replace" ctrl+f

Regards,

**Comment by silvestreh** [comment]
Hi @cumanacr,

The highlight color is determined by the base color you picked in the theme's settings. Could you share a screenshot so I can take a better look?

**Comment by cumanacr** [comment]
Hi @silvestreh,

Here is the screenshot, looking for the word "pea" as you can see at line 3 there is a border white result, which is the one I am currently selecting, the others have teal borders, before the update, all results have white borders and teal color inside and it was easier to identify.

Sorry for the late response, I hope you can check this out anyway.

Regards

![atom-find](https://cloud.githubusercontent.com/assets/6874136/13588595/8230437a-e496-11e5-9a6e-19ac17946fae.png)

**Comment by silvestreh** [comment]
I fixed this in 1ed42fe7471bab9570ad43bcf5ce53139b1372f8. I still haven't published the update to APM though.

**Comment by cumanacr** [comment]
Way better, I changed it manually, thank you very much
