### ISSUE TITLE
`display: inline-block;` on `.btn` wins over Bootstrap's `.btn-block`

### ISSUE THREAD

**Issue by ssorallen** [silvestreh/atom-material-ui#233]
Nuclide uses Bootstrap's `btn-block` class, and it worked fine in atom-material-ui v1.1.0. However, v1.2.0 added `display: inline-block;` to the `.btn` class. Because theme stylesheets are included after Bootstrap stylesheets, the `.btn-block` class has become a no-op because it is always loses on document order specificity.

The change happened in commit https://github.com/silvestreh/atom-material-ui/commit/b56260b8bf80c4c8cbb551d48c7555425560d308

**Comment by silvestreh** [comment]
I don't use Nuclide, but I have installed (yet disabled) just in case these issues pop up. Would you be willing to show me how to reproduce this? I'm thinking a small change to the buttons CSS selector might do the trick.

**Comment by ssorallen** [comment]
You can reproduce this by inspecting a button with `class="btn"` in developer mode and adding the `btn-block` class to it. The [`.btn` declaration](https://github.com/silvestreh/atom-material-ui/blob/d5b025a770f41bc1e67caf17eb52de2600767082/styles/buttons.less#L5) in 'atom-material-ui' declares `display: inline-block;` and wins over the `.btn-block` class in Bootstrap.

Added to the settings view "Open Config Folder" button:
<img width="474" alt="screen shot 2016-03-06 at 6 14 29 pm" src="https://cloud.githubusercontent.com/assets/29612/13559308/b00c7c48-e3c7-11e5-9db1-4d092a0bfade.png">

`.btn-block` losing on specificity:
<img width="332" alt="screen shot 2016-03-06 at 6 15 07 pm" src="https://cloud.githubusercontent.com/assets/29612/13559314/c6bf88a4-e3c7-11e5-84e3-4925b8272275.png">

`.btn` from 'atom-material-ui' winning with `.btn`:
<img width="333" alt="screen shot 2016-03-06 at 6 15 14 pm" src="https://cloud.githubusercontent.com/assets/29612/13559318/d785d206-e3c7-11e5-96a3-8fab497096a4.png">

**Comment by ssorallen** [comment]
[`.btn`](https://github.com/twbs/bootstrap/blob/v3.3.4/less/buttons.less#L10) is already declared as `display: inline-block;` in Bootstrap v3.3.4, which is the current version that gets installed with Atom. I believe you can safely remove that line from 'atom-material-ui' and be fine.
