### ISSUE TITLE
z-index modification to tab-bar conflict with the autohide-tree-view package

### ISSUE THREAD

**Issue by VincentGuinaudeau** [silvestreh/atom-material-ui#236]
see https://github.com/olmokramer/atom-autohide-tree-view/issues/65

I open this issue to know if the modification on the z-index of the tab is really useful to this theme, because I just removed it and it apparently fixed my problem.

**Comment by silvestreh** [comment]
Thanks! … The elevated zIndex value is there to enable the tab-bar to cast shadows on top of the text editor. I agree 2000 might be too much :grin:

I'll post an update soon fixing this an a couple other issues.
