### ISSUE TITLE
When I open Atom, it pop up a message: "there were breaking changes and material ui had to reset its settings"

### ISSUE THREAD

**Issue by cuiweiqiang** [silvestreh/atom-material-ui#237]
![image](https://cloud.githubusercontent.com/assets/863696/13492641/430cf8de-e174-11e5-9862-fd7d25f966a4.png)

How can I solve it? Everytime open it and show message.
Atom version: 1.5.4

**Comment by silvestreh** [comment]
That's odd… A key should've been saved to your localStorage. Open a dev console and type this:

```javascript
localStorage.setItem('atom-material-ui:configUpdated', true);
```

That should solve your problem. I'll try to check why it didn't set this localStorage key for you.

**Comment by D-side** [comment]
Reporting in from Windows 10. Same issue here. Worse, `localStorage` seems to not persist! I've tried adding my own key-value to it, it was gone after a restart.

Also, I'm seeing this in the Dev Tools:

    Error setting item in object: Validation failed at atom-material-ui, undefined must be an object

**Comment by cuiweiqiang** [comment]
@silvestreh I type this,  then it seems not use. And the editor theme change to default. I type this:
`localStorage.setItem('atom-material-ui:configUpdated', false);`  
the material theme was disappeared, I reinstall the theme, it works!

**Comment by silvestreh** [comment]
I removed the piece of code that was checking wether the configuration was updated or not :smile:
