### ISSUE TITLE
Forcing ui to dark?

### ISSUE THREAD

**Issue by mlilley** [silvestreh/atom-material-ui#239]
Various "dark" syntax themes cause materia-ui to switch to "light" (when I *think* it should be dark).

For example, material-ui switches to light when attempting to use any of the following syntax themes:
- https://github.com/ssteinker/atom-twilight
- https://github.com/cannikin/twilight-syntax
- https://atom.io/themes/twilight-syntax-spacegray-eighties
- https://atom.io/themes/twilight-syntax-spacegray-ui

What is the mechanism that triggers which light or dark scheme material-ui uses?  
Is there an override available to force material-ui into either a light or dark mode, or do the syntax themes need to be updated somehow to be compatible with material-ui?

![screen shot 2016-03-03 at 1 48 39 pm](https://cloud.githubusercontent.com/assets/20426/13510749/e07b3c8a-e146-11e5-9a6b-f8c25377cf28.png)

**Comment by silvestreh** [comment]
This is an issue with the syntax themes. They don't expose their syntax-variables. You can take a look at this PR I opened for [spacegray-base16-ocean-dark](https://github.com/carloe/spacegray-base16-ocean-dark/pull/13) fixing this problem.

**Comment by mlilley** [comment]
Excellent, thanks for your help.

**Comment by cannikin** [comment]
I'm the maintainer of 3 of those 4 themes you listed! I don't use atom at the moment, but if someone wants to open a PR for fixes I'll happily merge.
