### ISSUE TITLE
Tab size

### ISSUE THREAD

**Issue by ZheFeng** [silvestreh/atom-material-ui#24]
Is it possiable to make the tab size customisable. Like SuperLarge, Large, Normal, Small, SuperSmall

**Comment by silvestreh** [comment]
Everything is possible, but I fail to see the point on giving the tabs a fixed size. They resize dynamically based on how many tabs you have open.

That being said, why would you like to have fixed widths?

**Comment by ZheFeng** [comment]
well, yes I see. Actually, what I want is reduce the height of the tab. I want to reduce it cause it's take too many space for me.

**Comment by silvestreh** [comment]
Oh… now that makes sense. I wasn't thinking about their height :smile:. I could add that as an option, sure.

**Comment by silvestreh** [comment]
Option added in 0.5.0

**Comment by ZheFeng** [comment]
Awesome. Thank you. The update looks great.
