### ISSUE TITLE
Atom Build latest version

### ISSUE THREAD

**Issue by noseglid** [silvestreh/atom-material-ui#240]
I am the maintainer of [atom-build](https://github.com/noseglid/atom-build). I'm making some changes to the layout in the upcoming version which unfortunately breaks with material UI. Do you want to work together to get a nice design for it? The code is available on the master branch (but it is not yet released).

**Comment by dkerzig** [comment]
+1 for seeing my two most beloved plugins working together

Just referencing #191

**Comment by noseglid** [comment]
@dkerzig I saw that issue and I'd be damned if we're gonna let it happen again! :)

**Comment by silvestreh** [comment]
@noseglid do your changes work well with other themes? I mean, do you want me to do something specifically for material ui or a good default for every other theme?

**Comment by noseglid** [comment]
It works well with the built in themes and a few others I've tested. I'm trying to use the variables provided by Atom to make that possible. It may be that it works well if we just remove the special handling that is in this theme now.
