### ISSUE TITLE
Strange looking sections

### ISSUE THREAD

**Issue by PinkiePieStyle** [silvestreh/atom-material-ui#245]
After last Update i've got this

Atom 1.5.4
Material-UI 1.2.5
![material](https://cloud.githubusercontent.com/assets/7350146/13711960/76f6be16-e7c1-11e5-9e03-e885854f5424.png)

**Comment by silvestreh** [comment]
I'm sorry… what's strange about it?

**Comment by silvestreh** [comment]
You mean this?

![captura de pantalla 2016-03-11 a las 16 16 47](https://cloud.githubusercontent.com/assets/1133339/13712867/b3b47d7e-e7a4-11e5-9393-c69d07c07ad5.png)

**Comment by PinkiePieStyle** [comment]
The blue(ish) Field right. 
On other PC with Material-UI 1.2.0 it looks correct.

Same as in your Screenshot

**Comment by silvestreh** [comment]
Thanks! Should be fixed in 1.2.6 :+1:

**Comment by PinkiePieStyle** [comment]
Thx too for ur great work...
