### ISSUE TITLE
Font-weight of code is not the same between panes

### ISSUE THREAD

**Issue by eramdam** [silvestreh/atom-material-ui#248]
![screen shot 2016-03-14 at 2 50 53 pm](https://cloud.githubusercontent.com/assets/1409924/13761163/2f0f9bec-e9f4-11e5-8f81-1b6bf69cfc2f.png)

The un-focused pane (on the left) has a sightly smaller font-weight, resulting in annoying visual effect when switching from one pane to another.

**Comment by silvestreh** [comment]
`font-weight` is not involved here, it's the pane's `opacity`. I'll do something different to avoid annoying you.
