### ISSUE TITLE
Command palette background is white

### ISSUE THREAD

**Issue by diagramatics** [silvestreh/atom-material-ui#25]
An image explains it better.

![](https://cloud.githubusercontent.com/assets/5153378/8507182/85f619b4-227a-11e5-96b6-a3caa3d3e0da.png)

Using the "alternative command palette background" option fixes it though, as expected. But right out of the box with the dark Material syntax gives me that. I suspect this has to do with the ongoing work in #11?

**Comment by silvestreh** [comment]
No, that's the default behavior. You have an option to make it darker.

**Comment by diagramatics** [comment]
Ah, well it could use a little bit of work though. The icon needs a little bit of left margin and the text aren't exactly readable IMO.

And while we're at it (and because I don't want to add a new issue for another topic), how close is this theme going to follow the Material Design guidelines?

**Comment by silvestreh** [comment]
Yeah, everything could use a little work. I'm open to pull requests :)
