### ISSUE TITLE
Incompatiable with html-preview package

### ISSUE THREAD

**Issue by pot-code** [silvestreh/atom-material-ui#250]
When html-preview function is on, hide it then,  open  the **setting**  panel, part of the preview just display as a background underneath the setting tabs on the left.It's cool in someway, but odd indeed

Could you please fix that? thanks!

**Comment by silvestreh** [comment]
which html-preview package are you referring to? I'm getting more than a few search results :smile:

**Comment by pot-code** [comment]
I should apologize first, I haven't described clearly, html-preview is just **one of the chain**.I tested it again in case of coincidence,here is what I have done to meet the bug:

> Involved packages:**atom-html-preview** by webBoxio, ** maximize panes**  by santip

1. open a html file or something else.
2. press ctrl-shitf-H to active html-preview ,editor split into two panes one each side. html file on the left while preview is on the right.
3. press ctrl-shift-Enter to maximize the html file pane ,preview pane hid automatically.
4. open the setting pane by shortcuts ,the hidden preview appears on the left accidently.

I'm not sure if I have stated clearly ,anyway

**Thank you for your time!**

![screenshot](https://cloud.githubusercontent.com/assets/17687881/13896665/a7714db8-edcf-11e5-9ee0-ad8f9bb3a30a.png)

**Comment by silvestreh** [comment]
The <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> did nothing for me. But after resizing the HTML preview pane I could still see the settings menu shadow on top of it. After some fiddling, this is what I got:

![captura de pantalla 2016-03-25 a las 0 38 10](https://cloud.githubusercontent.com/assets/1133339/14037420/246f1556-f222-11e5-9b39-67a639562d88.png)

**Comment by pot-code** [comment]
Ok, I modified the shortcuts, It works for me .It actives   **maximize panes**(by santip)
