### ISSUE TITLE
Tabs input fields in settings

### ISSUE THREAD

**Issue by gosteev** [silvestreh/atom-material-ui#253]
Hello. Today i updated plugin to the latest version, and got this:
![ss 2016-03-17 at 12 58 28](https://cloud.githubusercontent.com/assets/6203574/13831327/a5d9a806-ebdb-11e5-8e1b-90f91cd1a239.png)

two text input fields instead of dropdowns, as it was before.
how can i manage this options?

Atom 1.6.0-beta7, windows10 x64

**Comment by silvestreh** [comment]
Duplicate. Same as #251 … I should probably add a *known issues* to the readme file
