### ISSUE TITLE
When package updates, settings are not reapplied.

### ISSUE THREAD

**Issue by coolhome** [silvestreh/atom-material-ui#255]
When the UI is updated the color goes back to green.

Atom: 1.6.0 (Note: Occurred before 1.6.0 as well)

Packages
├── Remote-FTP@0.7.20
├── atom-alignment@0.12.1
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.2.9
├── docblockr@0.7.3
├── file-icons@1.6.18
├── highlight-selected@0.11.2
└── minimap@4.21.0

**Comment by silvestreh** [comment]
Same as #243
