### ISSUE TITLE
Background Color for Dropdowns

### ISSUE THREAD

**Issue by The5heepDev** [silvestreh/atom-material-ui#26]
The background color of the dropdown menus is white -- rendering the text unreadable. It is also fairly ugly, and it can be fixed. The other themes seem to change the background of the dropdowns fine, so I know it can be done. 

Here's a screenie with the Atom Material Theme:

![screenshot from 2015-07-07 20-15-33](https://cloud.githubusercontent.com/assets/8976745/8560379/f45e978e-24e4-11e5-97c9-b1a78d58d862.png)

Here's a screenie with the Atom Dark Theme:

![screenshot from 2015-07-07 20-22-22](https://cloud.githubusercontent.com/assets/8976745/8560459/f54b664e-24e5-11e5-9967-19469a319b34.png)

Edit: 
I took a look at your index.less file... It seems as though you aren't including the dropdowns.less file. Is that the issue?

**Comment by silvestreh** [comment]
What version of the theme are you using? This was fixed a few releases back.

**Comment by The5heepDev** [comment]
I used the version that the install tab uses. 0.5.0?

![screenshot from 2015-07-07 21-19-49](https://cloud.githubusercontent.com/assets/8976745/8561087/f00d3ae2-24ed-11e5-912d-fe030e91efa5.png)

**Comment by silvestreh** [comment]
Yep, that's the latest. I just checked my code and I made the fix specifically for Windows hosts. I just pushed some code to make the fix available to other platforms. Will publish a patched version as soon as I finish setting up a Ubuntu virtual machine to test it.

**Comment by The5heepDev** [comment]
I'm using arch linux with gnome if it makes any difference.

**Comment by silvestreh** [comment]
*should* be fixed in 0.5.1. Cheers!

**Comment by The5heepDev** [comment]
Thanks mate!
