### ISSUE TITLE
Vertical scrollbar UI isn't where the grab handle is

### ISSUE THREAD

**Issue by hatched** [silvestreh/atom-material-ui#260]
Ubuntu 14.04
Atom 1.60

The vertical scroll bar handle is a little to the right of where it needs to be (horizontal is correct). I have to grab just to the left of the handle to actually use the scrollbar, if I grab on the handle it switches to adjust the width of the split pane. I've tried a few other themes and it appears that this is related to this theme only and not another package.

** indicate the active themes

```
├── atom-dark-fusion-syntax@1.1.0
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.2.9 **
├── atom-ternjs@0.13.2
├── autocomplete-go@1.0.4
├── base16-eighties-dark@2.1.1 **
├── base16-ocean-dark-spacegray@0.12.0
├── base16-syntax@1.6.2
├── environment@1.2.0
├── file-icons@1.6.18
├── go-config@1.1.2
├── go-get@1.0.1
├── go-plus@4.0.1
├── gofmt@1.1.3
├── gometalinter-linter@1.0.4
├── gorename@1.0.0
├── highlight-selected@0.11.2
├── isotope-ui@2.7.1
├── linter@1.11.4
├── linter-eslint@7.1.3
├── monokai@0.18.0
├── navigator-godef@1.0.2
├── no-caffeine-syntax@0.17.2
├── nucleus-dark-ui@0.7.16
├── polaris-syntax@0.1.0
├── seti-syntax@0.4.1
├── seti-ui@0.9.1
└── tester-go@1.0.2
```

**Comment by silvestreh** [comment]
Does this happen with left or right-aligned panels?

**Comment by silvestreh** [comment]
Nevermind… I get what you meant.

![captura de pantalla 2016-03-24 a las 15 11 38](https://cloud.githubusercontent.com/assets/1133339/14026682/c2c1ef8a-f1d2-11e5-8ece-cb6f66c2f950.png)

**Comment by hatched** [comment]
Much better thanks a lot!
