### ISSUE TITLE
UI Font Size Setting in theme oversizes when user inputs 1 by accident

### ISSUE THREAD

**Issue by Gunny123** [silvestreh/atom-material-ui#267]
UI font size over sizes when you leave a one before you enter another digit. Instead, defaults to 10 and then adds the digit.

**Reproduction Steps:**

1. Delete any value in the User Interface font size field within the settings of the theme
2. Enter "1" followed by a number of your choice 
3. UI Font size gets insanely large

**Expected behavior:**

Font size should stay the same until user enters a digit after 1

**Observed behavior:**

See looped video below

**Screenshots and GIFs**

[Video](https://streamable.com/4jmc)

**Atom version:** 1.6.2
**OS and version:** Mac OS X 10.11.4 

**Installed packages:**

├── aligner@0.19.1
├── atom-beautify@0.29.0
├── atom-html-preview@0.1.19
├── atom-jade@0.3.0
├── atom-jshint@2.0.0
├── atom-material-syntax@0.4.5
├── atom-material-syntax-light@0.4.4
├── atom-material-ui@1.2.10
├── autoclose-html@0.23.0
├── chester-atom-syntax@0.1.1
├── color-picker@2.1.1
├── emmet@2.4.3
├── file-icons@1.7.0
├── github-2016-syntax@1.2.0
├── language-javascript-jsx@0.3.7
├── language-swift@0.4.0
├── linter@1.11.4
├── minimap@4.21.0
├── minimap-find-and-replace@4.5.0
├── pigments@0.26.0
├── pinned-tabs@0.2.2
├── tool-bar@0.4.0
├── tool-bar-main@0.0.9
└── xcode-theme@1.4.0

**Additional information:**

* Problem can be reproduced in safe mode: Yes 
* Problem started happening recently, didn't happen in an older version of Atom: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: All

**Comment by silvestreh** [comment]
I'm not sure I can anticipate a user accidentally input a number he/she didn't mean to input. What I did is restrict the range you can input as fontSize from 10 all the way up to 32 and defaults to 16. 

This number is used as the base fontSize for the editor. All sizes are based on this number using `REM`s. 

While I understand your problem, I don't think there's much I can do to handle it other than lowering the max value and avoid the UI to get that much bigger.

**Comment by Gunny123** [comment]
I'm just saying if one delays input by one second the theme thinks its 10 and when the user inputs another digit it scales to a value of 100 plus that number. So if I enter 1 and wait a second deciding what the next digit I want to be, lets say 4. It will scale to 104

**Comment by silvestreh** [comment]
Yeah, I managed to reproduce it. I believe this is how the core `settings-views` package handles input changes. Not much I can do about it.

**Comment by Gunny123** [comment]
Mkay. Thought I'd bring it up anyway. Thanks for looking in to it
