### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by german-rios-gonzalez** [silvestreh/atom-material-ui#268]
Hello, I have this error when I try this package:

Line number: 127
'custom.less' wasn't found

LessError: 'custom.less' wasn't found
  at /home/german.rios.gonzalez/.atom/packages/atom-material-ui/styles/ui-variables.less:127:0

There is some thing that I did wrong?

**Comment by german-rios-gonzalez** [comment]
I'm very sorry, this only happens when I install atom from a copr of mosquito in fedora, when I install the package by the atom download page there is no errors

**Comment by kmare** [comment]
I have the same problem. I'd like to keep using the mosquito repo on fedora. Isn't it fixable somehow?

**Comment by silvestreh** [comment]
@kmare the `custom.less` file is where your personal settings are saved. This [file is in the repo](https://github.com/atom-material/atom-material-ui/blob/master/styles/custom.less) and should exist when installing the theme.

I wouldn't know WHY it's missing in your case. Try reinstalling the theme:

```shell
apm uninstall atom-material-ui
apm install atom-material-ui
```

Or, alternatively, create the file yourself:

```shell
touch ~/.atom/packages/atom-material-ui/styles/custom.less
```

This could be fixed if someone would merge this one-year-old [pull request](https://github.com/atom/less-cache/pull/8) which I don't think it'll happen any time soon. This would enable theme developers to use LESS' `import` options.

**Comment by kmare** [comment]
Thank you! It was as you said. uninstalling and reinstalling didn't help, but creating (touch) the file did the trick.
