### ISSUE TITLE
Add folder animations to the theme 

### ISSUE THREAD

**Issue by Gunny123** [silvestreh/atom-material-ui#269]
Would there be a way to implement the [folder animations like in the Sublime Text Material UI theme](http://gfycat.com/HotSlushyJellyfish)?

Apologies for the number of issue submissions already.

**Comment by silvestreh** [comment]
That would involve changing the icons and it's something I'm not going to do until I find a way for not having blurry icons. Check #193 for some more info.

**Comment by Gunny123** [comment]
Understood. Thanks for the reply.
