### ISSUE TITLE
More compact tree view setting

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#27]
Would be great to be able to set the "line height" of the items in the tree view, or at least be able to set it to "compact" - I'm finding the current spacing between files and folders a little too... spacious! It allows less items to be in view. 

**Atom Material UI**
![materialtreeview](https://cloud.githubusercontent.com/assets/8268040/8633023/4ce0ef50-27b6-11e5-9f03-9c773b1b8c0a.PNG) 

**One Dark UI**
![onedarktreeview](https://cloud.githubusercontent.com/assets/8268040/8633024/4ce3fe8e-27b6-11e5-9c33-a331572f8039.PNG)

**Comment by silvestreh** [comment]
Sounds good. I increased the line height to better match the MD spec, but I understand some people would rather have more items in view. I'll add the setting, thanks!

**Comment by alexbeletsky** [comment]
+1 here, on 13'' it a way tooo much.. I was quite surprised after the upgrade. Previously `height` was better, from my perspective.

I thought it might be setting for that but did find anything.

**Comment by silvestreh** [comment]
Done! Just pushed 0.5.2.

**Comment by alexbeletsky** [comment]
Upgraded, works as charm!

**Comment by WoodyWoodsta** [comment]
Great stuff! Thanks!

**Comment by alexbeletsky** [comment]
one question @silvestreh .. I've just noticed, at my home machine where I haven't upgraded yet, I have different icons for file types. They are colorful and actually looks really good. Did you change that in few latest releases.. is this because it's better suite material scheme?

**Comment by silvestreh** [comment]
Nope, I didn't change the icons in the treeview. Those are provided by the `file-icons` package.

**Comment by alexbeletsky** [comment]
Got it, thanks a lot.

**Comment by egold** [comment]
How does one find/change the setting for the tree view line height? Besides editing the .less file in the theme directory?

**Comment by silvestreh** [comment]
@egold: Go to settings, then navigate to the Themes section. In there you'll find a cog icon next to the theme dropdown selector.

![captura de pantalla 2016-08-13 a las 8 48 33 p m](https://cloud.githubusercontent.com/assets/1133339/17646222/5864cfd8-6197-11e6-90b5-b90b9e86a311.png)


If you can't see the cog icon, just click the package card for `atom-material-ui` anywhere but the title.

![captura de pantalla 2016-08-13 a las 8 49 07 p m](https://cloud.githubusercontent.com/assets/1133339/17646225/67ed28ce-6197-11e6-8271-e3141d858619.png)

**Comment by egold** [comment]
Brilliant! Thanks so much @silvestreh. I was specifically looking for that button, but I think the fact that I didn't see it on any of the Themes (besides yours) was making me assume it wasn't a thing.
