### ISSUE TITLE
2 characters combining into 1

### ISSUE THREAD

**Issue by dudeofawesome** [silvestreh/atom-material-ui#273]
If I type `fi` or `fl` in any text widgets within atom, the 2 characters get combined into 1 single width character.

![screen shot 2016-04-14 at 6 58 09 pm](https://cloud.githubusercontent.com/assets/1683595/14549221/e4f674bc-0272-11e6-81af-e10e1e02fe04.png)

This only happens with a lowercase `f` and lowercase `i` or `l`, and only in that order. Changing any of the characters to uppercase causes them to not merge.

If I change my theme to Atom Dark, then the issue goes away, so I believe this is caused by Atom Material UI.

The font I am using is [Fira Mono](https://github.com/powerline/fonts/tree/master/FiraMono)

I am using Atom Material UI with Atom 1.7.0 (although this issue has been around since at least 1.6.x) on OS X 10.11.3

**Comment by silvestreh** [comment]
It's called [ligatures](https://en.wikipedia.org/wiki/Typographic_ligature). Both characters are still there, but they're rendered as a special single character. If you want to override this behavior, open your user stylesheet and add this:

```css
atom-text-editor, atom-text-editor::shadow {
    text-rendering: optimizeSpeed;
}
```

Personally, I love programming ligatures available in Fira Code:

![](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

**Comment by dudeofawesome** [comment]
TIL. When I tried out Fira Code, fi and fl stopped being combined.
