### ISSUE TITLE
UI problem with atom's Minimap package

### ISSUE THREAD

**Issue by SubhamSatyajeet** [silvestreh/atom-material-ui#278]
When using the minimap package (https://atom.io/packages/minimap), the settings menu in the minimap, when revealed, shows the first option in the menu highlighted.

![90](https://cloud.githubusercontent.com/assets/7932787/14974028/61eeb1de-110d-11e6-9327-9d972aa1f114.png)

One Dark UI, One Dark Syntax (provided by default on Atom)

![91](https://cloud.githubusercontent.com/assets/7932787/14974038/854cf94c-110d-11e6-8b03-df536086e549.png)

Atom Material UI, Atom Material Dark Syntax

**Comment by silvestreh** [comment]
Duplicate of #270
