### ISSUE TITLE
font size is small

### ISSUE THREAD

**Issue by b4456609** [silvestreh/atom-material-ui#28]
The font size is too small compare with one dark theme. Maybe add a font size in setting page.

**Comment by silvestreh** [comment]
Font size? on the UI or the text editor? There's already a setting for that in the main settings page.

**Comment by b4456609** [comment]
The main setting page only change size in editor.
Tree view and Taps.

**Comment by q13** [comment]
+1

**Comment by silvestreh** [comment]
I'll add a setting to change UI's font size.

**Comment by silvestreh** [comment]
The new setting is available in 0.5.3

**Comment by b4456609** [comment]
Great. Thanks

**Comment by Webdesiigner** [comment]
So how do I change the font size of the the UI ?
