### ISSUE TITLE
Marked text in Installer not readable

### ISSUE THREAD

**Issue by stebiger** [silvestreh/atom-material-ui#29]
After marking text in an input text element on the atom editor the chosen color makes it unreadable.

![image](https://cloud.githubusercontent.com/assets/8200750/8700662/77b12826-2b0d-11e5-8ca7-680c936fc45e.png)

**Comment by silvestreh** [comment]
I'll take a look. Thanks!

**Comment by silvestreh** [comment]
Should be fixed in 0.5.3

**Comment by stebiger** [comment]
Yes it is fixed - but now it is very hard to see what text parts are selected.

![image](https://cloud.githubusercontent.com/assets/8200750/8771313/6d09d3da-2ec0-11e5-8763-2d6976b74b59.png)
