### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by k4nar** [silvestreh/atom-material-ui#3]
Hi. First, thanks for this awesome theme!

In the screenshot, I can see that the scrollbar should be thin and follow the main theme. However, on my system I don't get those:

![screenshot2](https://cloud.githubusercontent.com/assets/2692721/8284189/eec7ec0c-18fb-11e5-90da-dbbc16bcd5f7.png)

I'm using Atom 210 with Archlinux and KDE 5.

**Comment by silvestreh** [comment]
Will check! I'll need to set up a linux VM, so please be patient :) My screenshots were taken on OS X. In OS X scrollbars are not visible until you actually scroll.

**Comment by k4nar** [comment]
I thought this was a scrollbar on the left in [this screenshot](https://camo.githubusercontent.com/4a0840eeb04ce1a99801200034453f7842aa5e9c/687474703a2f2f692e696d6775722e636f6d2f577872514c57622e706e67), but that must be the wrap line.

**Comment by silvestreh** [comment]
Yeah, that's the wrap line. I can add a toggle in the settings to make scrollbars really thin if that's what you'd like.

**Comment by silvestreh** [comment]
@k4nar I just published an update. Check the settings for new options :)

**Comment by peduxe** [comment]
@silvestreh Your theme gives One Dark UI a run for his money, great job.

Question: which is the current version? apm says 0.4.0, github (by your commits) says 0.3.2.

**Comment by silvestreh** [comment]
When I use APM to publish the theme it automatically touches my `package.json` version. The lastest published version should be 0.3.2:

    $ apm publish patch
    Preparing and tagging a new version ✓
    Pushing v0.3.2 tag ✓
    Publishing atom-material-ui@v0.3.2 ✓

I must've messed up something. I'm guessing Atom doesn't offer you the update, or does it let you update to a "previous" version?

**Comment by peduxe** [comment]
It wasn't showing your newer changes, I hacked over it with apm install atom-material-ui#0.3.2

**Comment by peduxe** [comment]
The package list probably got messed up when you downgraded the version, it was at 0.4.0.

**Comment by silvestreh** [comment]
@peduxe I just republished the package. Versions should be in sync. Try uninstalling it first. Sorry for the mess!

**Comment by peduxe** [comment]
@silvestreh It's no big deal, I still could've copy pasted the changes myself on the packages folder anyway, fwiw, some people may not know such things.

**Comment by peduxe** [comment]
version 0.3.3, it got sorted out, great.

**Comment by silvestreh** [comment]
great! I'm closing this issue then :)
thanks!

**Comment by peduxe** [comment]
wait a minute, can you share a screenshot with Roboto Mono activated? Renders pretty bad for me. [Roboto Mono](http://i.imgur.com/elcWOPf.png) / [Consolas](http://i.imgur.com/3FYezMs.png), well maybe it's just how the font.

**Comment by silvestreh** [comment]
Here's a screenshot

![captura de pantalla 2015-06-22 a las 13 23 42](https://cloud.githubusercontent.com/assets/1133339/8286777/f32cfed2-18e1-11e5-82f1-dda22090a824.png)

Yours looks as if it was lacking antialias. Maybe it's OS-related. I'll investigate a little further.

**Comment by silvestreh** [comment]
@peduxe I added antialiasing to Roboto Mono. Try updating. 

BTW, you could probably clone the repo and use `apm link`. I'm afraid it might bother some people to have 10 updates per day :smile:

**Comment by peduxe** [comment]
Looks good now, but still doesn't beat my Consolas :grinning:

**Comment by k4nar** [comment]
Scrollbars are much better integrated now, thanks :) .
