### ISSUE TITLE
Colors are too sharp

### ISSUE THREAD

**Issue by steelbrain** [silvestreh/atom-material-ui#30]
I tried every palette and **all** of them are super-sharp, I have 10/10 vision and my laptop screen's set to default color scheme, I had to revert to the `atom-dark-ui` to continue using Atom.
Here's a screenshot of how sharp they are
![screenshot from 2015-07-17 08-28-04](https://cloud.githubusercontent.com/assets/4278113/8749385/7bded464-2c5e-11e5-9eeb-925471c4e445.png)

**Comment by silvestreh** [comment]
The colors come from the [Material Design Spec](https://www.google.com/design/spec/style/color.html).

**Comment by steelbrain** [comment]
Right, then it must be my black background which doesn't mix with the spec, what syntax themes would you recommend?

**Comment by silvestreh** [comment]
Well, there's the [atom-material-syntax](https://atom.io/packages/atom-material-syntax) package specifically for this theme. Monokai looks nice too.

**Comment by steelbrain** [comment]
`atom-material-syntax` is even worse :sweat_smile:
btw, why is the command palette's color black when the background color is dark?

**Comment by silvestreh** [comment]
Got a screenshot?

Right now the Fuzzy Finder/Command Palette is white by default. There's an option to make it match the syntax theme. I plan to change this behavior and make it match the syntax theme by default.

**Comment by equinusocio** [comment]
Look at Atom One Dark, you can set the UI color base on the syntax used. It's a bit tricky, but you can do it. However, nice work with this porting :+1:

**Comment by silvestreh** [comment]
The UI colors are based on the syntax theme, very much like Atom's One Dark theme, except for the accent colors… those are kinda hard coded. :smile:

**Comment by krainboltgreene** [comment]
I've also noticed the contrast wouldn't pass accessibility standards. Any chance you could run these through tota11y and see about improving them?

**Comment by equinusocio** [comment]
@krainboltgreene so, Android Lollipop wouldn't pass accessibility standards?

**Comment by steelbrain** [comment]
@equinusocio I'm an Android Lollipop user, It looks great in there, but as you can see in the picture above, The wrong percentage colors have been chosen from the palette, Their combination hurts the eyes.

**Comment by krainboltgreene** [comment]
@equinusocio It wouldn't be the first time a company failed a11y.

**Comment by steelbrain** [comment]
If you guys look at the material design color spec, You will see a lot of different weights (I call them percentages) of colors, Some are soft, others are sharp. This theme is using the sharp ones.

**Comment by krainboltgreene** [comment]
From tota11y:

<div class="tota11y-info-error-description"><p>
    The color combination
    <span class="tota11y-color-hexes">#666666/#cccccc</span>
    has a contrast ratio of <strong>3.58</strong>, which is not
    sufficient. At this size, you will need a ratio of at least
    <strong>4.5</strong>.
</p>

<p>
    Consider using the following foreground/background combination:
</p>

<div class="tota11y-contrast-suggestion">
    <span class="tota11y-color-hexes">
        #575757/#cccccc
    </span>

    <span class="tota11y-swatches">
        <span class="tota11y-swatch" style="background-color: #575757">
        </span>
        /
        <span class="tota11y-swatch" style="background-color: #cccccc">
        </span>
    </span>

    has a ratio of

    <strong>4.50</strong>
</div>
</div>

**Comment by equinusocio** [comment]
Where is the #666/#ccc combination?

**Comment by krainboltgreene** [comment]
It's hard to tell, because the bookmarklet isn't quite working within atom well. I believe the #cc is the text? Like file list/tab name etc.

**Comment by silvestreh** [comment]
@krainboltgreene please note that most colors are determined by the syntax theme you're using. Background and foreground included. This issue should be moved to the [syntax theme repository](https://github.com/silvestreh/atom-material-syntax).

**Comment by silvestreh** [comment]
@steelbrain BTW... by "sharp" do you mean colors are too [saturated](https://en.wikipedia.org/wiki/Colorfulness#Saturation)? (sorry, english isn't my primary language)

**Comment by steelbrain** [comment]
@silvestreh by sharp I meant that colors don't mix very well, imagine a full white background with a low font width along with a black font color, that would hurt the eyes :)

**Comment by steelbrain** [comment]
In the image I posted in the first picture, the background color of the selected item and the font color don't mix very well.

**Comment by Icehunter** [comment]
I made this to go along with full on dark settings; however it really won't work with anything so far but this UI package.

https://atom.io/packages/icehunter-syntax

One issue is the highlight colours in the find box and how buttons look... but I kind of like my stuff dark; as the light was a little too hard on the eyes.

**Comment by Icehunter** [comment]
@silvestreh great work btw!

**Comment by silvestreh** [comment]
@Icehunter care to share a screenshot? I'm not sure what you're talking about.

**Comment by silvestreh** [comment]
@Icehunter actually… open a new issue. I'm closing this one as it's mostly about a subjective matter and not really about a bug.
