### ISSUE TITLE
Latest version has removed the ripple effect from tabs

### ISSUE THREAD

**Issue by bbuck** [silvestreh/atom-material-ui#36]
I know it's just a visually pleasing effect but I notice after updating the UI that the ripple from tabs is gone yet the animated underline remains present.

I assume you had good reason to remove it, but I would request that you add it back in and instead put it behind a configuration option. I quite like it, and it was one of the main things that really attracted me to the UI in the first place (although I'm not going to move away without it, it was nice to have).

**Comment by equinusocio** [comment]
The ripple effect still exist, this will be more visible in the next release

**Comment by silvestreh** [comment]
@equinusocio we could probably throw in a toggle to make the ripple effect use the accent color.

**Comment by equinusocio** [comment]
by default (with the dark background) i think the ripple must be white. We can make a setting to using the accent color. I don't know why now the ripple is black.

**Comment by silvestreh** [comment]
v0.5.9 should fix this.

**Comment by bbuck** [comment]
It looks great to be back. I :+1: the idea of having an option for it to use the Accent color - it is kind of faint on the background of your companion theme (which I also love by the way).

Thanks for making this happen so quickly!
