### ISSUE TITLE
After last update, filename is not showing in tab.

### ISSUE THREAD

**Issue by jcornil** [silvestreh/atom-material-ui#37]
I just updated to 0.5.6 and I can't see the filename in tab.

![2015-07-21 3 19 01](https://cloud.githubusercontent.com/assets/157859/8794212/ebd8a690-2fbb-11e5-8b54-5f8b61722cd0.png)

**Comment by silvestreh** [comment]
That's… odd to say the least. What type of file is that? Looks like a PHP file, am I right?

**Comment by jcornil** [comment]
I created some files for test...

<img width="1174" alt="2015-07-22 12 07 30" src="https://cloud.githubusercontent.com/assets/157859/8804177/d4c3ffd2-3005-11e5-9158-cef81e9e001a.png">

When I create a new file it's ok, but when I close it and open it again...filenames are gone.

**Comment by silvestreh** [comment]
Which other packages do you have installed? I ask this because I found that, for example, the `file-icons` package overrides the `top` property for some file types and their icons in tabs will look displaced.

Run `ls ~/.atom/packages/` inside a terminal and paste the output. I'll try your packages and see if I can find something odd.

**Comment by silvestreh** [comment]
Also, I noticed you have the depth setting enabled. Did you enable/disable anything else?

**Comment by jcornil** [comment]
Here is my ls...

$ ls ~/.atom/packages
README.md            atom-material-ui     color-picker         git-plus             linter               seti-icons
Remote-FTP           autoprefixer         compare-files        jshint               merge-conflicts      terminal-status
advanced-new-file    blade-snippets       emmet                language-blade       minimap              tool-bar
atom-alignment       browser-plus         flex-tool-bar        laravel              preview-plus         tool-bar-main
atom-material-syntax change-case          format-sql           laravel-theme        project-sidebar      vim-mode


And my theme setting...

<img width="363" alt="2015-07-22 1 07 56" src="https://cloud.githubusercontent.com/assets/157859/8805821/453ecde8-300e-11e5-994f-11f12eccbc96.png">

**Comment by jcornil** [comment]
I just turn on the 'Disable animations' option...and I can see the filename.

**Comment by silvestreh** [comment]
Yup, it's the `seti-icons` package. I'll try to work on a fix for it, but if you want to to continue using material-ui I'd you recommend to switch to [file-icons](https://atom.io/packages/file-icons) for a little while.

**Comment by jcornil** [comment]
Thx :+1:

**Comment by silvestreh** [comment]
Just pushed an update that should fix your problem :smile: 
Cheers!
