### ISSUE TITLE
Dark highlights in Command Palette dropdown

### ISSUE THREAD

**Issue by dallasbpeters** [silvestreh/atom-material-ui#38]
These dark characters make the command palette difficult to use. Is my setup wrong? Or is this a bug in the theme?

<img width="311" alt="screenshot 2015-07-21 11 04 36" src="https://cloud.githubusercontent.com/assets/91672/8805805/d7f437c0-2f98-11e5-86d8-b6a4415d3424.png">

**Comment by druellan** [comment]
I see the same thing. Fixed it using the "constrasting panels" option, but is not a good default IMHO.

**Comment by druellan** [comment]
I believe this is related to #31

**Comment by silvestreh** [comment]
Thanks! I'll look into it.

**Comment by silvestreh** [comment]
Fixed in 0.5.8. Thank you for the report!

**Comment by dallasbpeters** [comment]
:+1:

**Comment by equinusocio** [comment]
@silvestreh next time referer this issue in the commit message :+1:

**Comment by silvestreh** [comment]
@equinusocio sorry 'bout that. And I just pushed a couple fixes for some issues. Will reference them in future commits.
