### ISSUE TITLE
UI font size does not affect the panels and status bar

### ISSUE THREAD

**Issue by druellan** [silvestreh/atom-material-ui#39]
Hi! Thanks for this nice theme.

I'm using the "huge" font settings to compensate my hidpi screen (1920x1080 @ 13"). That works nice, but does not affect the status bar, nor the panels, that remains with a very small font size.
Not sure if this is bug or a limitation.

![2015-07-21 14_08_07-settings - c__users_psy_documents_motoshopping_htdocs_themes_default-bootstrap -](https://cloud.githubusercontent.com/assets/6965667/8807433/f516a3be-2fb2-11e5-8b84-4cff2ce401bf.png)

**Comment by silvestreh** [comment]
Fixed in 0.5.8. Thank you for the report!

**Comment by druellan** [comment]
:thumbsup:
