### ISSUE TITLE
Choose palette when just the syntax is active

### ISSUE THREAD

**Issue by peduxe** [silvestreh/atom-material-ui#40]
Hey, I prefer to have the syntax alongside One Dark UI, it does looks great.
Would be pretty cool if you could implement a way to set which palette one does want to use, currently it's sets to `teal` by default.

**Comment by silvestreh** [comment]
I'm not sure I follow. You want to have Material UI accents in One Dark UI? That wouldn't work as they're two different UI themes.

In Material UI theme you can change the accent color.

![captura de pantalla 2015-07-21 a las 16 08 14](https://cloud.githubusercontent.com/assets/1133339/8810060/c604b768-2fc2-11e5-8d4f-f3164231a5ac.png)

The syntax theme, however, is not configurable.

**Comment by peduxe** [comment]
@silvestreh It's okay.

**Comment by silvestreh** [comment]
Alright, I'm closing this issue then. Just so you know, One Dark will pick up colors from the syntax theme for the UI, so it might be picking the teal color from the syntax and, unfortunately, I cannot change that without affecting the syntax color.
