### ISSUE TITLE
One Light incompatibility - Package settings

### ISSUE THREAD

**Issue by skyrpex** [silvestreh/atom-material-ui#42]
Hi!

Another incopatibility with One Light. It occurs in all the package's settings panel.

![atom-material-one-light](https://cloud.githubusercontent.com/assets/1077520/8822743/f5e5e312-3067-11e5-9910-2eaa40f3a839.jpg)

Regards!

**Comment by skyrpex** [comment]
thanks!

**Comment by silvestreh** [comment]
No problem. I still have to push the update to APM. I'll push it as soon as I iron out some other issues.
