### ISSUE TITLE
Failed to activate the atom-material-ui theme

### ISSUE THREAD

**Issue by nicovdb** [silvestreh/atom-material-ui#44]
I can't load this theme anymore
1. Updated to latest version 
2. Restart Atom editor

Stacktrace:

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v0.5.9

### Stack Trace

Failed to activate the atom-material-ui theme

```
At Unrecognised input in C:\Users\15753\.atom\packages\atom-material-ui\styles\autocomplete.less:-1:0

LessError: Unrecognised input
  at C:\Users\15753\.atom\packages\atom-material-ui\styles\autocomplete.less:-1:0
```

### Commands

```
     -1:31.7.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -1:30.2.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
  6x -1:29.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:28 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
 12x -1:24.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  5x -1:22.1.0 core:delete (atom-text-editor.editor.is-focused)
     -1:18.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:06.0 core:delete (atom-text-editor.editor.is-focused)
  2x -1:05.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:05.0 core:delete (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:03.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:35.1.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  6x -0:34.4.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.5.0 application:show-settings (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "viriato"
    ],
    "fileEncoding": "iso88591",
    "disabledPackages": [
      "wrap-guide",
      "refactor",
      "refactor",
      "open-conemu-here"
    ],
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules"
    ]
  },
  "atom-material-ui": {
    "altCmdPalette": true,
    "depth": true,
    "panelContrast": true,
    "slimScrollbar": true,
    "tabSize": "Small"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
atom-pair, v1.1.6
color-picker, v2.0.11
css-snippets, v0.8.0
emmet, v2.3.12
file-icons, v1.5.8
grunt-runner, v0.11.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.3.9
linter-csslint, v0.0.14
minimap, v4.12.0
one-tab, v0.6.0
project-manager, v1.15.11
Sass-Syntax-Highlight, v0.1.1
Sublime-Style-Column-Selection, v1.3.0
svn, v0.0.7
tool-bar, v0.1.8
tool-bar-main, v0.0.8
viriato, v0.11.0

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
Might be a stupid question, but did you try to remove the package and reinstall it? Some people had problems and that seemed to work.

`At Unrecognised input in C:\Users\15753\.atom\packages\atom-material-ui\styles\autocomplete.less:-1:0`

That seems to indicate the error is on line `-1` which is quite unlikely. None the less, I'll investigate this and try to reproduce your problem.

BTW. Best. Bug. Report. Ever. Thank you!

**Comment by nicovdb** [comment]
Thx, just using the bug reporting tools from the Best. Editor. Ever.

**Comment by zacksmash** [comment]
This issue occurs when you drag the color picker outside of its area. Uninstalling and reinstalling does fix the issue, only until you drag the color picker outside of the picker area again.

**Comment by silvestreh** [comment]
@zacksmash which color picker are you talking about?  BTW, this bug is for 0.x, are you running 1.0.x?

Also, 1.0.x was unpublished, if you're still using it I recommend downgrading. However, if you want to help me out reporting issues then clone this repo and link it with APM. Instructions on #131.

**Comment by zacksmash** [comment]
@silvestreh I'm on 1.0.1, the Atom link brought me directly here, sorry about that. The color picker (on Mac) for Primary Color and Accent Color's both show the behavior noted in my previous comment. If you scroll too far outside of the color wheel, it reeeaaallly breaks some shit. The quick fix for it is to click on the accent color swatch, then click on the middle tab in the color picker UI and choose Web Safe Colors from the drop down menu and choose one of those colors. That will reset the UI back to normal.

**Comment by silvestreh** [comment]
@zacksmash do you have the complementary option selected? Because that can break some shit :grin:
