### ISSUE TITLE
File type icons showing under filename

### ISSUE THREAD

**Issue by hatched** [silvestreh/atom-material-ui#45]
When using the package https://atom.io/packages/file-icons the icons are shown below the filename in the tab.

![screenshot from 2015-07-23 09 17 12](https://cloud.githubusercontent.com/assets/532033/8854222/292de954-311c-11e5-8ffe-77cbc519f64e.png)

- All tabs show the icons in this way even if they aren't selected. 
- If I disable animations then the icons are hidden for all but the selected tab.
- Enabling 'Icons In Tabs' moves the selected tab text to the right but the icon does not move.

Atom 1.0.2
atom-material-ui 0.5.9
monokai 0.15.0

**Comment by silvestreh** [comment]
Looks like it's specific to go-lang files. I'll post an update briefly. Thanks!

**Comment by hatched** [comment]
Looks good, thanks for the quick fix!
