### ISSUE TITLE
after opening/closing folders, tree view can get garbled

### ISSUE THREAD

**Issue by smlombardi** [silvestreh/atom-material-ui#46]
See attached.  Sometimes it happens, sometimes not.  Atom 1.02, OSX 10.11b4, a-m-ui 0.5.9.

<img width="338" alt="screen shot 2015-07-25 at 1 40 49 pm" src="https://cloud.githubusercontent.com/assets/835148/8890556/360b4e9c-32d3-11e5-84bb-296ccb5d3e93.png">

**Comment by najela** [comment]
This happens to me quite often too

**Comment by silvestreh** [comment]
I can't seem to reproduce this. Do you guys have some more info?

**Comment by smlombardi** [comment]
I have the theme set to the "compact" tree.  I also have Roboto Mono
installed (In fact, I find I get better editing text if I un-check your
"use Roboto for editor" and simply choose through Atom prefs), not sure if
any of those things make it more likely.

FWIW, 10.11b4 seemed to have some video display wonkiness, let's see if it
happens again in beta 5

On Wed, Jul 29, 2015 at 3:08 PM, Silvestre Herrera <notifications@github.com

**Comment by najela** [comment]
@silvestreh Its quite difficult to reproduce as I don't even know what causes it.

I'm using OS X 10.10 btw

**Comment by sethlopezme** [comment]
I don't believe this is an issue with this theme, but an issue with [atom/treeview](https://github.com/atom/tree-view). I've seen this happen in other themes, as well.

**Comment by silvestreh** [comment]
I'm closing this one as it's been a while and haven't been able to reproduce it. Please reopen if you know how to reproduce it.
