### ISSUE TITLE
Errors in ATom

### ISSUE THREAD

**Issue by pranjalagrawal2012** [silvestreh/atom-material-ui#481]
Unhandled rejection Error: EPERM: operation not permitted, mkdir 'C:\Users\Its_me_\_cacache'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by harsh1732** [comment]
Can Run Directly

**Comment by pranjalagrawal2012** [comment]
> Can Run Directly

How can  is resolve this .. Please help me out

**Comment by silvestreh** [comment]
```
Unhandled rejection Error: EPERM: operation not permitted, mkdir 'C:\Users\Its_me__cacache'
npm ERR! cb() never called!
```

If you look at the error message it's saying `operation not permitted`. And by `mkdir` I imagine some process tried creating a directory and wasn't able to probably because it's lacking the necessary permissions to do so.

This does not seem to be an issue with the theme itself.
