### ISSUE TITLE
Bulky Interface

### ISSUE THREAD

**Issue by aminya** [silvestreh/atom-material-ui#483]
Atom material looks very bulky for me.
- It doesn't show the tab names correctly and shows the titles squashed together _(see right in the bottom images)_
- The project management is large and bulky for no reason _(see left in the bottom images)_
- The settings seem just cluttered (why that settings font is that big?)
- The new one (https://github.com/suda/tool-bar/pull/277): It doesn't show 21px toolbar buttons correctly.

Compare **One-Dark**:

![image](https://user-images.githubusercontent.com/16418197/75466557-fec78b00-594f-11ea-82a7-28108cdb851a.png)

![image](https://user-images.githubusercontent.com/16418197/75467352-210dd880-5951-11ea-8488-12e0b9ecd696.png)

To **Material**:

![image](https://user-images.githubusercontent.com/16418197/75466681-2a4a7580-5950-11ea-8db7-7cb8ac07e510.png)

![image](https://user-images.githubusercontent.com/16418197/75467393-2f5bf480-5951-11ea-9869-1a33e824d3bd.png)

Toolbar button issue:
Left Material, Right One-Dark
![image](https://user-images.githubusercontent.com/3742559/75122037-7bcdd880-56a2-11ea-80dc-a581611ea0c4.png)

**Comment by silvestreh** [comment]
This sounds more like an opinion instead of a bug report. If that's the case, please feel free to adjust things to your liking through the user stylesheet 😄

**Comment by aminya** [comment]
> 
> 
> This sounds more like an opinion instead of a bug report. If that's the case, please feel free to adjust things to your liking through the user stylesheet 😄

Since we don't have access to this repository, we can just ignore the problems
[Ref.](https://github.com/suda/tool-bar/pull/277#issuecomment-592074882)

**Comment by silvestreh** [comment]
Well, to be completely honest, I've switched to a more performant text editor a couple years ago and I don't have the time nor energy to maintain the theme properly. I'm just keeping an eye open for breaking changes in Atom.
