### ISSUE TITLE
Scrollbars on find and replace inputs

### ISSUE THREAD

**Issue by SK83RJOSH** [silvestreh/atom-material-ui#49]
When you select an input in the find and replace pop up you get these scrollbars:

![fin7hd0l](https://cloud.githubusercontent.com/assets/1371787/8973298/5585c30e-3631-11e5-9e29-641e13498db5.png)

**Comment by silvestreh** [comment]
Which OS are you on?

**Comment by SK83RJOSH** [comment]
Currently on Windows 10, if you need any additional information let me know :smile:

**Comment by diagramatics** [comment]
Hm, I'm running Windows 10 and I don't have scrollbars.

Any custom stylesheets? Running DevTools and see if anything overflows would help too.

**Comment by SK83RJOSH** [comment]
No custom stylesheets and inspecting the element reveals that the overflow is caused by atom-text-editor[mini]::shadow::before

The weird thing is it has a width of 100%, is absolutely positioned, and has no padding. So I don't see how it can be triggering the scrollbars. It also doesn't seem to happen after toggling the style attribute on and off.

All that said, I think the only solution is goiong to be disabling overflow on .find-container atom-text-editor.mini

**Comment by SK83RJOSH** [comment]
Actually you know what, it has a left position of 50% and a width of 100%. So what could be happening is for some reason it's falling on a half-pixel.

**Comment by diagramatics** [comment]
That, I believe, is the line animation when the input is focused. The 50% left position was the positioning to put the element on the middle and the 100% width was after the .is-focused class being applied to the input.

But yeah, the code looks the same to me but it didn't produce any scrollbars for me at all. It is a very weird way to produce that animation though.

**Comment by diagramatics** [comment]
If you're familiar with testing packages and themes on Atom, I've made changes on the transition effect over on my [repo](https://github.com/diagramatics/atom-material-ui). Maybe this will solve the problem you're having.

**Comment by SK83RJOSH** [comment]
Yeap that solves the issue!

**Comment by diagramatics** [comment]
Yeah, just as I expected, it's an anomaly of how your version of Atom reflows. Weird, though, I'd love to take a look at the DevTools timeline to figure out why.

I made a PR #50 for this fix.
