### ISSUE TITLE
Contrast and AtomLinter

### ISSUE THREAD

**Issue by peduxe** [silvestreh/atom-material-ui#5]
[Autocomplete provider](http://i.imgur.com/yPFmwSm.png) - the icon left to the suggestion method isn't noticeable when selected.

AtomLinter just got a major update today (got rewrited basically) and features an inline notification for errors, [currently the text of the notification doesn't display](http://i.imgur.com/oDMIVsQ.png), as opposed to [One Dark](http://i.imgur.com/wJQAVNg.png):

**Comment by silvestreh** [comment]
Nice catch. I'll fix it ASAP.

**Comment by silvestreh** [comment]
Is this the package? https://atom.io/packages/linter

**Comment by silvestreh** [comment]
Link me to the packages you're using. I don't have autocomplete for javascript and can't seem to find an `autocomplete-javascript` from Atom.

**Comment by peduxe** [comment]
Yep that one, in case you want to talk with steelbrain the faster way you need to get into the atom slack channel, room: #linter.

**Comment by peduxe** [comment]
The linter i'm using is linter-jshint, but it's down to the https://atom.io/packages/linter guys to provide that (styles, handle the plugins logic).

**Comment by silvestreh** [comment]
Just pushed an update. Let me know if it's any better.

**Comment by silvestreh** [comment]
I'm closing this issue as it's been solved in the lastest release. Feel free to reopen it if you're still having problems.
