### ISSUE TITLE
Tab file icons overlapping tab text

### ISSUE THREAD

**Issue by sethlopezme** [silvestreh/atom-material-ui#52]
It seems that a recent update to this theme is causing file type icons to overlap the text within open file tabs. I've switched between a few other themes to double-check and this only happens with `atom-material-ui`.

![image](https://cloud.githubusercontent.com/assets/5733658/9043494/e260e99c-39e3-11e5-84c6-e20dbcb48043.png)

![image](https://cloud.githubusercontent.com/assets/5733658/9043499/ec35d554-39e3-11e5-989d-0a299fc119cd.png)

**Comment by sethlopezme** [comment]
Whoops, just noticed there is an option for icons within tabs.  Not sure if this was a recent addition or not, but checking this fixed my issue.

**Comment by diagramatics** [comment]
Confirming this, I think this needs more investigation. With the option disabled the icons shouldn't show at all, and the Settings icon shows up on my end.

**Comment by silvestreh** [comment]
My bad! I'm pushing an update!
