### ISSUE TITLE
show icons on all tabs, have seperate option to disable icon animation

### ISSUE THREAD

**Issue by stefan-kern** [silvestreh/atom-material-ui#53]
im using the package https://atom.io/packages/file-icons which adds file icons to every tab.
while using atom-material-ui it only displays an icon on the active tab.
a big reason why i like file icons is that it makes it quicker to search through all the open tabs, because the icons provide an additional visual aid. (for example if youre looking for a .js file, you can identify the right tab much quicker by only looking at .js icons)
i'd like an option to restore icons on every tab.

**Comment by diagramatics** [comment]
Had nothing to do, so I did an implementation and it's live as a PR on #54.

It's way off the Material Design spec though since normally the icons are at the top of the text, but it wouldn't work in a text editor environment.

**Comment by stebiger** [comment]
I support this request - I first thought it was a bug of file-icons

https://github.com/DanBrooker/file-icons/issues/167
