### ISSUE TITLE
Please don't disable editor features (specifically the close tab button)

### ISSUE THREAD

**Issue by zyklus** [silvestreh/atom-material-ui#55]
I don't think the close tab button should be removed, at least not without the option to re-enable it (and not have to go writing custom CSS to undo what the theme did).  Note that this only applies when animations are off.

I don't think it's the place of a theme to disable any features in an editor.

**Comment by diagramatics** [comment]
What do you mean? As in the close tab button only shown when you hover over the tab? The default themes do this and I'm pretty sure this theme is based on the One themes as well.

If by that you mean you want the option to always show the close button, we can definitely do that.

**Comment by zyklus** [comment]
No, the close doesn't _ever_ show until I _click_ on the tab to select it.  Not even on hover :(

**Comment by diagramatics** [comment]
Ah, right. I tested it on mine, animations off or on, and they work fine. I think you got a bug in your hands.

Are you familiar with debugging Atom? Can you try and see which property declaration is affecting this? Screenshots would help too, especially the styles tab of the close icon. It also seems like another plugin is conflicting this, so if you can run `apm list --installed --bare` on the terminal and paste it here along with the Atom version that'll be great.

> When they're on the behavior is different (but I think the tab highlighting it's too distracting)

Additional info about this would be great as well.

**Comment by silvestreh** [comment]
@zyklus I *think* you came across #47. Are you sure you have your packages up to date?

> When they're on the behavior is different (but I think the tab highlighting it's too distracting)

I believe you mean the animations while switching tabs, right? Those can be disabled in settings. The issue where tab controls wouldn't become visible on hover when animations were off was resolved and an update was pushed to APM (about a week ago, I think.)

**Comment by zyklus** [comment]
You're right.  Atom was showing it as up-to-date, but I blame my horrible internet connection (I'm in Indonesia at the moment) for causing Atom to lie to me ;)

Thanks!

**Comment by diagramatics** [comment]
Indonesia? Yep, can confirm.
