### ISSUE TITLE
Unable to clearly see Show Invisible characters

### ISSUE THREAD

**Issue by Maelstrome26** [silvestreh/atom-material-ui#56]
I have Show Invisibles is turned on, however they're extremely hard to see.

Invisibles turn on: http://i.imgur.com/DCDLPp5.png

Invisibles turn off: http://i.imgur.com/5hYXwID.png

**Comment by diagramatics** [comment]
Seems like this is a mix between messed up property specificity and your syntax theme. What syntax theme are you using?

**Comment by Maelstrome26** [comment]
I believe it was Base16 Tomorrow Dark.

I didn't consider the syntax theme to be affecting this, I should have thought of that. :S

**Comment by Maelstrome26** [comment]
After applying the Atom Material UI Syntax theme, works fine, my bad :-/
