### ISSUE TITLE
Small style issue with close button on inline errors

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#57]
A screenshot says a thousand words:
![atommaterial](https://cloud.githubusercontent.com/assets/55841/9191962/296ef774-4007-11e5-87db-8621b626ee70.png)

**Comment by diagramatics** [comment]
#59 should fix it.

**Comment by equinusocio** [comment]
@diagramatics when commit use issue reference by typing "Close or fix #issue" number in the title or in the description. So when we merge with master brach the issue will be automagically closed. :)

**Comment by diagramatics** [comment]
@equinusocio I read the sudden comment from the email. Fixed with the auto-closing commit message :smile:.

**Comment by equinusocio** [comment]
:+1:
