### ISSUE TITLE
Command palette has very poor contrast

### ISSUE THREAD

**Issue by rjv** [silvestreh/atom-material-ui#6]
The styling for the command palette basically has white text on a white background. See attached.
![screenshot at 153634](https://cloud.githubusercontent.com/assets/532439/8315356/280383b0-19be-11e5-8baa-420070430800.png)

**Comment by silvestreh** [comment]
Oh… that's interesting… mine looks like this:

![](https://cloud.githubusercontent.com/assets/1133339/8315436/2a0fef28-19c7-11e5-8279-42f95164f3ec.png)

There's little contrast and that IS a problem, but tell me more… 
what OS and version are you using? 
Are you using some other syntax theme? (if so, tell me which one)

In the mean time, I'll fix the contrast :smile:

**Comment by rjv** [comment]
Ah, it was definitely the syntax theme that was the main culprit; thanks for pointing that out. I switched to your Atom Material syntax and I'm seeing something more akin to your screenshot.

For your reference, though, here is my configuration:

**OS:** Windows 7 Professional
**Atom:** 0.211.0

The syntax theme I had enabled was Monokai v0.14.0 (https://atom.io/themes/monokai)

**Comment by silvestreh** [comment]
Thanks. While the UI theme kinda works with other syntax themes, you'll find many things that are off. That's mainly because the UI theme didn't support other syntax themes on day 1 and it's something that I'm working on. 

Anyway, I have a fix that I'm testing. I'll push it as soon as I finish it. Thanks!

**Comment by silvestreh** [comment]
Fix pushed! Check for updates :smile:

**Comment by silvestreh** [comment]
I'm closing this issue as it's been solved in the lastest release. Feel free to reopen it if you're still having problems.
