### ISSUE TITLE
Theme style does not change

### ISSUE THREAD

**Issue by moltaire** [silvestreh/atom-material-ui#62]
The theme style switch in the settings doesn't work for me anymore. I'm on OS X 10.10, Atom 1.0.5 (fresh install). All other switches seem to work just fine. Let me know if you need anymore information than that.

Cheers for a great package!

/edit: should say, that I'm not sure it ever worked. I might have just switched to a darker syntax or mixed up my memories with Sublime Text..

**Comment by diagramatics** [comment]
Huh, weird. I can't find any CSS styling on this. Was this ever implemented apart from the options?

**Comment by silvestreh** [comment]
This, apparently, came with ac36615790bf4492fa00b0d09542dd5c14d4a4ec though I fail to see any styling.

Thing is… I'm not sure if it makes sense to have this option. The UI theme uses syntax colors to either show a light or dark user interface.

**Comment by diagramatics** [comment]
How about using them and then replacing the 500-700 configuration with something like 300-500 for light and 700-900 for dark?

**Comment by silvestreh** [comment]
Those colors are determined by the syntax theme. I think all I could be able to do is use LESS' color functions, `darken` and `lighten`, to manipulate a background color. Would that be something useful?

**Comment by diagramatics** [comment]
People wanted them, so I don't see any reason not to I guess.

**Comment by silvestreh** [comment]
Nah… can't do it as a setting. I'll have to make another syntax theme for this.
