### ISSUE TITLE
Theme overrides file-icons package

### ISSUE THREAD

**Issue by goronfreeman** [silvestreh/atom-material-ui#64]
The latest update causes the icons provided by the [file-icons](https://atom.io/packages/file-icons) package to not show up.

**Comment by diagramatics** [comment]
Confirming this. Doesn't seem like the latest release fixes it.

**Comment by Chotaz** [comment]
This was happening to me as well but a reload fixed it.
This will happen if both packages are enabled and you update atom-material-ui via package manager.

**Comment by diagramatics** [comment]
I suspect it's because of the programmatically checking for any icon packs installed isn't being run on update.

**Comment by silvestreh** [comment]
Yep, forgot to mention. You need to reload Atom after the latest update. I OS X just hit `Ctrl` + `Alt` + `Cmd` + `L`.

**Comment by silvestreh** [comment]
Also reload the editor after enabling/disabling one of the supported files icons packages. I'll check Atom's API and see if there's a way to watch those packages' status and act accordingly.

**Comment by goronfreeman** [comment]
Thanks, looks like that fixes the problem. The issue can be closed.

**Comment by silvestreh** [comment]
@goronfreeman I pushed another update that fixes the reloading requirement. It should work as expected now.
