### ISSUE TITLE
Overrides custom file-type icons

### ISSUE THREAD

**Issue by sethlopezme** [silvestreh/atom-material-ui#66]
I think a recent release for this theme is overriding custom file-type icons. I also have the [file-icons](https://github.com/DanBrooker/file-icons) package installed, and they're not showing up anymore.

![image](https://cloud.githubusercontent.com/assets/5733658/9255733/35a2f21c-41b9-11e5-88a3-76a5f94e3760.png)

_Edit:_ It looks like the `.dont-change-icons` class on the HTML element fixes things. Was this an option that was mistakenly left out, perhaps?

**Comment by silvestreh** [comment]
Reload Atom after enabling/disabling a custom icon package such as `file-icons`. 

`Ctrl` + `Alt` + `Cmd` + `L` should do the trick on OS X.

**Comment by sethlopezme** [comment]
Ah, that fixed my issue. Sorry about that!
