### ISSUE TITLE
scrool bar seems non native

### ISSUE THREAD

**Issue by muhasturk** [silvestreh/atom-material-ui#68]
- Move your cursor on to position of scrool bar (scrool bar should be invisible)
- Scrool up-down
- You will see following issue

![](https://leto12f.storage.yandex.net/rdisk/fe844301da66beb3e4cf4c4eb0737506e8198203794f7d8ef4091fe6b9563d3f/inf/O9zbkeXu2JaQwQltyCaFVE1EGlFai-BYM6nfv8hOiCIkESFo54ZdL8zUiXaBiAUsB-yX1EcoFZacmm3sFnoxDQ==?uid=137163141&filename=Screen%20Shot%202015-08-13%20at%2022.45.46.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=2c796fcc0024a961ae7617d4ff784388&force_default=yes&ycrid=na-faa3e30bd589189c5671ed03ed64fde0-downloader13g)

Atom 1.0.7

**Comment by silvestreh** [comment]
Those scrollbars ARE native.

**Comment by silvestreh** [comment]
I just pushed an update that styles the scrollbars when your OS settings are to always show them.

**Comment by muhasturk** [comment]
Can you make an option to disable native scrool bar for editor? Is it possible?

Looks ugly like this.

![](https://leto2f.storage.yandex.net/rdisk/8a8171737a9f3f0f1f96724038abb63d239c5af0b9a95261248d619f38d4d838/inf/cnSQg2YRT0FsoAZWdT5gHohUFCDaRaFEVSokGDp6sMPrioaMB5c6DI-RwXGHGu-0nf_La_2AMB-UGnE4GOh8RQ==?uid=0&filename=Screen%20Shot%202015-08-14%20at%2000.00.27.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=2c796fcc0024a961ae7617d4ff784388&force_default=no&ycrid=na-ea8214fd0534559bf1b6a98246481824-downloader8g)

**Comment by silvestreh** [comment]
I'll see what I can do, but I'm not sure I'll be able to do much about it since that's how OS X behaves.
