### ISSUE TITLE
After reloading/restarting editor, cursor becomes misaligned with content

### ISSUE THREAD

**Issue by whoisforte** [silvestreh/atom-material-ui#69]
![screen shot 2015-08-14 at 1 26 53 am](https://cloud.githubusercontent.com/assets/2560683/9267803/a0665458-4223-11e5-9f0b-18c56113165e.PNG)

If I either restart the editor or reload it via the "View" menu, I run into an issue where the cursor doesn't align with the file content and doesn't accurately reflect where the text is and isn't. For example, in the above screenshot the cursor position is the farthest out I can go, yet hitting the backspace key deletes that last character on that line as expected.

I'm on OS X 10.10.4, Atom 1.0.7
Quick testing shows that the issue is theme-dependant as it doesn't occur in the default "One Dark" theme.

**Comment by diagramatics** [comment]
Is the bug consistent? I can't reproduce it at all, but then again I'm running on Windows 10.

Is it recent? Are there any errors reported on DevTools? Can you run `apm list --installed --bare` on terminal to show your installed packages and paste the results here?

**Comment by silvestreh** [comment]
I can't reproduce it either. Same OS and Atom version.
