### ISSUE TITLE
Miss all file icons

### ISSUE THREAD

**Issue by ZheFeng** [silvestreh/atom-material-ui#7]
This is an awesome ui.

After install, everything is good, except all file icons (js, css, etc...) are missed.
![screen shot 2015-06-24 at 10 38 17 am](https://cloud.githubusercontent.com/assets/1264113/8320355/27cf8d9a-1a5d-11e5-95b3-1e7211d7076f.png)

**Comment by silvestreh** [comment]
That's odd. I'm using [File-icons](https://atom.io/packages/file-icons) package and I can see all custom icons.

![captura de pantalla 2015-06-23 a las 22 16 09](https://cloud.githubusercontent.com/assets/1133339/8320789/7aec016a-19f5-11e5-8eb6-781a93fb97f4.png)

Are you sure the File-icons package is enabled?

**Comment by ZheFeng** [comment]
Oh, OK. I didn't use File-icons. Thanks for help, issue solved. :+1:

**Comment by silvestreh** [comment]
Which package were you using? (So I can check it out and see if there's something wrong)

**Comment by ZheFeng** [comment]
I didn't use any other package, I thought the ui bring the file icons.

**Comment by silvestreh** [comment]
Aaahh… ok, I'll close this issue then. Glad you liked the theme!
