### ISSUE TITLE
Autosize inputs broken

### ISSUE THREAD

**Issue by d4rkr00t** [silvestreh/atom-material-ui#70]
Hi! When renaming files with long path or name there is a bug with input size:

![screen shot 2015-08-14 at 15 19 58](https://cloud.githubusercontent.com/assets/200119/9273745/126d87aa-4298-11e5-885c-32bb5727f9a1.png)

Issue with height property for atom-text-editor[mini]: https://github.com/silvestreh/atom-material-ui/blob/master/styles/editor.less#L12

**Comment by silvestreh** [comment]
I don't see whats wrong. Can you elaborate a little more? Seems fine for me.

**Comment by d4rkr00t** [comment]
Yes sure. 

![out](https://cloud.githubusercontent.com/assets/200119/9277127/c630c564-42b0-11e5-81fc-aa54679b1c34.gif)

But atom by default do auto resize inputs for long text.

**Comment by d4rkr00t** [comment]
When i set height to auto it's look like this:

![screen shot 2015-08-14 at 18 18 58](https://cloud.githubusercontent.com/assets/200119/9277167/07d42dda-42b1-11e5-9896-2668bc982ca1.png)

**Comment by silvestreh** [comment]
Welp… I can't seem to reproduce this. Care to share which packages you got installed? Run `apm list --installed --bare` in a terminal and copy the output.

**Comment by silvestreh** [comment]
OOOOK… I managed to reproduce this. You have "soft wrap" enabled in Atom settings. I'll push a fix shortly!

**Comment by d4rkr00t** [comment]
Yes i do :). Thanks!
