### ISSUE TITLE
No feedback that package is installing

### ISSUE THREAD

**Issue by IrksomeZeus** [silvestreh/atom-material-ui#71]
When I click to install a package in the settings menu there is nothing that indicates that I have actually clicked and that the package is installing like in the One Dark theme. After the package installs it switches to the uninstall button but there is nothing in between those two states. This isn't a huge problem but it would be nice to have this back.

I have Atom 1.0.7 and this happens on both Windows 8.1 Pro and Linux Mint 17.2

**Comment by silvestreh** [comment]
The install button gets a background animation. That's what I see here at least.

**Comment by IrksomeZeus** [comment]
I only see this animation if I go back to the list of results.
For example:
If I try installing this package - just the top featured this morning - Before clicking install when I move the mouse over it the text turns blue indicating that I can click it but as soon as I click it this is what it looks like, however it doesn't let me click it again which is good and I guess sort of feedback.

![image](https://cloud.githubusercontent.com/assets/10698732/9305679/3a68b7f4-44c1-11e5-9711-38dfb73c7b50.png)

However, if i click install and then go back to the list of packages that can be installed by clicking the install button I do get the installing animation on the package in the list:

![image](https://cloud.githubusercontent.com/assets/10698732/9305747/c72df8a2-44c1-11e5-86d9-bf7cffc5ef7a.png)

I hope this helps and thanks for looking into it for me.

**Comment by swthate** [comment]
I am receiving the following error after trying to install both from within Atom and from the command line:

`Unable to download https://www.atom.io/api/packages/atom-material-ui/versions/0.5.21/tarball: 500`

This theme looks absolutely amazing, can't wait to try it out!

**Comment by IrksomeZeus** [comment]
Thanks for posting - I think you have a bit of a different issue than this and you might get more help creating a new issue specifically for that problem. Also it would be really helpful for people to help you and fix the problem if you can give some information on what version of Atom you have and what operating system you're running

**Comment by silvestreh** [comment]
@swthate looks like an issue with Atom's servers, not really related to the theme. Try installing again. Also, make sure Atom is not behind a firewall or something.

**Comment by swthate** [comment]
@IrksomeZeus, apologies.

@silvestreh, you're right. Yesterday it worked fine.

Thanks, all!

**Comment by IrksomeZeus** [comment]
No problem, glad you got it working.
