### ISSUE TITLE
Make Markdown Preview match the syntax theme color

### ISSUE THREAD

**Issue by diagramatics** [silvestreh/atom-material-ui#72]
Related to #11, since mostly we can tweak the text color and background color to match the syntax theme if it's dark or not.

Other possibility could be changing the link color to match the theme main color, but considering it is a Markdown Preview for GitHub maybe we don't really need to do that.

**Comment by silvestreh** [comment]
I'm not sure I follow. I wasn't aware you could preview Markdown files, how does that work? 

When you open a package's settings page, the README.md file is rendered there. Links in that rendered Markdown file use the UI theme's accent color.

**Comment by diagramatics** [comment]
Ctrl+Shift+M allows you to have a preview of the Markdown file you're writing with the Markdown Preview package.

![screenshot 6](https://cloud.githubusercontent.com/assets/5153378/9292620/cc55a5f2-4447-11e5-83c5-3eabb687ebf5.png)

One Dark has the overall look turned into dark, basically. We should follow suit.

**Comment by silvestreh** [comment]
@diagramatics: Just pushed the update!

**Comment by diagramatics** [comment]
Storming through bugs and feature requests, I like it! Great work.
