### ISSUE TITLE
option to change UI font to Roboto

### ISSUE THREAD

**Issue by mattsawyer77** [silvestreh/atom-material-ui#73]
Saw the option to use Roboto Mono in the editor. Thought it would be cool to have an option to use Roboto and/or Roboto Light for the UI (tree view, etc.).

**Comment by silvestreh** [comment]
Yeah, I tried that but, truth be told, it looked like crap. Besides, it would require to include another font and I'm not really comfortable with adding to the download size.

To try it open your stylesheet

![](https://cloud.githubusercontent.com/assets/1133339/9346290/627e32d8-45f1-11e5-86d5-b79ae7ed524b.png)

and paste this at the very end

    html, .tab-bar, atom-panel-container, .pane, .settings-view {
        font-family: 'Roboto';
    }

**Comment by silvestreh** [comment]
BTW… that would require you to have the font installed.

**Comment by diagramatics** [comment]
Considering some themes do this even with a wide array of fonts to pick, it shouldn't be a bad thing to do IMO.

We can also add another option text field for the custom UI font the user can fill in with, to anticipate feature requests wanting other fonts to be available.

**Comment by diagramatics** [comment]
Submitted a PR at #78 with only WOFF2 files used. Explanations are in the PR comment.
