### ISSUE TITLE
Markdown preview takes the syntax style

### ISSUE THREAD

**Issue by crscardellino** [silvestreh/atom-material-ui#75]
Hello!

After the last update of the UI Theme, the Markdown Preview (ctrl+shift+m on mac) is now taking the syntax style of the current syntax theme. So if the syntax theme is Atom Material, the background of the preview is blueish-indigo (instead of white) and the font is colored as of the syntax simple text (instead of black), if I change the syntax theme, it adopts the background and foreground color of the new syntax theme and so on.

It looks like it is a problem of the UI Theme, since when I change the UI to one of the preinstalled ones, I get the markdown preview in the original format.

Thanks!

**Comment by diagramatics** [comment]
Um, it's actually intentional. #72 and I'm the one to blame for.

I noticed Atom's One Dark UI is doing the same, so I suggested that. You mentioned... the preinstalled themes don't behave the same?

**Comment by crscardellino** [comment]
Oh... Didn't know that. Actually, with Atom Dark it doesn't match the syntax, but with One Dark it does... Anyhow, is there a way to have the original markdown preview style? (is easier when taking notes to read them afterwards)

**Comment by diagramatics** [comment]
Just checked the package, and you're in luck! The Markdown Preview package settings has a "Use GitHub.com style" option. Check it out!

**Comment by crscardellino** [comment]
Cool! Thanks a lot!
