### ISSUE TITLE
Using different syntax theme with material ui theme

### ISSUE THREAD

**Issue by swthate** [silvestreh/atom-material-ui#76]
Hi there,

I'm using OSX with Atom 1.0.7 and atom-material-ui 0.6.0.

I love the dark material ui, but unfortunately the dark material syntax has too much contrast for me. Every time I try to use my favorite syntax theme, base16-ocean-dark-spacegray (0.10.0), the material ui theme switches to the light variant.

How can I force it to stay on the dark UI theme when using a syntax that is not the dark material syntax?

Thanks!

**Comment by diagramatics** [comment]
Marking this related to #11.

I guess it would be better if we separate the theme to Atom Material Dark and Atom Material Light. This might be the reason why the One theme is separated to the Dark and Light versions too.

**Comment by swthate** [comment]
Yes, I was thrown though a little bit of a loop, because the theme describes itself as a "dark UI theme", but behaves as though it's both light and dark depending on your syntax.

Thanks again!

**Comment by silvestreh** [comment]
@swthate yeah, that description of it being a dark ui theme was before I actually made it a dynamic theme.

I'm not exactly sure, but seems like some (probably old) syntax themes don't expose the variables needed to make the UI match its colors.

If you switch to One Dark you'll notice that some parts of the UI have a light background (active tabs for example).

For these themes, the best one can hope for is that the author updates its code to support dynamic UI themes like One Dark or Material UI.

In most cases (I don't want to generalize and say *all* cases) patching these themes is pretty simple, you have to move all styles to `styles/base.less`, create a new file `styles/syntax-variables.less` and create two variables, `@syntax-background-color` and `@syntax-text-color` inside it. Then, in the `index.less` file you just write `@import "./styles/base.less";`. Also, you would have to change all instances of the HEX / RGB / RGBA / HSL color with the corresponding variable.

I'll go the extra mile and send a pull request to the author of the theme you want to use (I actually patched it while typing this post, it's THAT easy)

**Comment by silvestreh** [comment]
Well, the pull request I sent was merged. I'm closing this issue.
