### ISSUE TITLE
More effort to adhere to MD specs

### ISSUE THREAD

**Issue by diagramatics** [silvestreh/atom-material-ui#79]
I was going over the possibilities of adding more features that are enabled by options to make the theme more closer to the specs, even though some of them ruins the editor's usability. Just to prove that we can and to serve as a usability test for Material Design in a power-user environment. I'm looking up on adding options to the settings page under a separate section right now so the page wouldn't be cluttered too much when these features are added.

Since I'm not a collaborator, I'm asking for permissions and to sync minds with this issue. I worked on a Material theme on my own before realizing it has been done and I wanted to bring some approaches I did there to here.

- [x] Button text as uppercase
- [ ] Tree view
  - [x] Project root to have the same height as the tab bar
  - [ ] Material Design spec size for the tree view items
- [ ] Tab bar
  - [ ] Uppercase text
  - [ ] Icons on top of text
  - [ ] Item size cannot collapse
  - [ ] Left and right icons on each side of tab bar for scrolling, also tab bar is scrollable with mouse wheel

**Comment by silvestreh** [comment]
Sounds good. I'm really not too experienced with Atom themes. This was my first attempt at making one and the first time I used LESS (I'm a Sass kind of person)

I've been thinking about restarting from scratch with the theme. I initially forked the old Atom Dark theme and started from there and there's probably a lot of inherited code that conflicts with the things I'm trying to and I end up using those horrible `!important` flags all over.

So yeah, I'm all ears. And I also made you a contributor :smile:

**Comment by diagramatics** [comment]
I did mine from scratch, it was complicated to say the least. Then again that was my first attempt in an Atom theme as well, so we're on the same page.

The codebase was fairly clean to work on so far, really, but if you're willing to start from scratch then I'll help in any way I can.

Ah, and thanks for the contributor status! :dancer:

I can list out the things we can improve on on the top of the issue here.

**Comment by silvestreh** [comment]
I don't think we should use upper case text for tabs as it's not a title, it's the file name and in some filesystems `SOME_FILE` is not the same as `Some_file` or `some_file`.

Icons on top of text… that would make for some huge tabs. But I don't think it would be a problem if it's behind a toggle in the settings pane.

**Comment by diagramatics** [comment]
The things I've listed here are more like "doing it just because we can" sort of thing, then putting it in the "experimental" section on the settings page. They're not UX-friendly in a text editor's case, I completely agree.

**Comment by Pupix** [comment]
@silvestreh If you wish to start from scratch you are better off waiting until chrome releases the CSS variables for easier configuration. They already implemented it in Canary.
