### ISSUE TITLE
Visual break between file finder and editor

### ISSUE THREAD

**Issue by shaunbent** [silvestreh/atom-material-ui#8]
Something I've noticed whilst using the UI and Syntax for the last few days in that there is no clear divide between the File Finder and the main editor. The two just blend together.

Just wondering if there would be some value in adding a subtle dividing line between the two? This should make it easier when it comes to resizing the file finder.

**Editor**
![file-finder](https://cloud.githubusercontent.com/assets/608566/8324274/d4022198-1a46-11e5-8be2-b335050303a7.png)

There is a very subtle dividing line within the settings panel currently, its only subtle but it really helps divide the settings tabs and the content of each tab.

**Settings**
![devide-in-settings](https://cloud.githubusercontent.com/assets/608566/8324277/d7de2bd6-1a46-11e5-9380-c2c655db744d.png)

I love this UI and Syntax by the way, thanks for putting the time in to make this.

**Comment by silvestreh** [comment]
This has been resolved in the 0.4.6 release. You will find an option in the theme's settings to enhance contrast between panels and the text editor.
