### ISSUE TITLE
Atom Material dark syntax graphical issue: "Use shadow DOM

### ISSUE THREAD

**Issue by hanslowinc** [silvestreh/atom-material-ui#80]
![capture](https://cloud.githubusercontent.com/assets/3399497/9419434/a6ef7b90-4829-11e5-9684-6f133a2e8e79.PNG)
![capture1](https://cloud.githubusercontent.com/assets/3399497/9419435/a6fff3b2-4829-11e5-9b09-ccdf08c87ecf.PNG)

That white line disappears when I turn off "Use Shadow DOM". Other themes don't have this issue.
Only occurs when using material dark syntax.

**Comment by diagramatics** [comment]
Material Dark Syntax repo is [this way](https://github.com/silvestreh/atom-material-syntax).
