### ISSUE TITLE
Accent color not so readable for AutoComplete

### ISSUE THREAD

**Issue by JohnMurga** [silvestreh/atom-material-ui#81]
Hi,

I was wondering if it was possible to add a custom accent color ...
Or even a Gray one ?

I am using the Noj Syntax, and with that none of the default accent colors are readable.

What I resorted to doing is changing the build in "White" accent to :
```
html.white {
    .accent(darken(@md-grey, 30%));
    .settings-view input[type="checkbox"] {
        -webkit-filter: grayscale(1);
    }
}
```

Which looks OK

**Comment by diagramatics** [comment]
Um, which part of the accent color application is unreadable?

But yeah, I might put the Material Design's Grey 500 in the accent colors available.

**Comment by JohnMurga** [comment]
For me it was auto-complete that wasn't readable ...
But maybe it is my eyes ;-)

**Comment by diagramatics** [comment]
Oh, I completely missed the autocomplete part. My apologies.

I'm actually curious to how the result is on your end. Can you show me a screenshot of the autocomplete?

**Comment by silvestreh** [comment]
@JohnMurga are you having issues only with the white accent?
