### ISSUE TITLE
Blurry icons

### ISSUE THREAD

**Issue by baurigae** [silvestreh/atom-material-ui#82]
I am running this theme's version 0.6.0 on Ubuntu 15.04. Folder icons in tree-view are blurry, as if not scaled properly:

![folders](https://cloud.githubusercontent.com/assets/5447269/9428161/4f270da0-49a1-11e5-9dca-62bd6ed9685c.png)

(left are tree view folders under Material UI; right under One Light UI)

Icons are also blurry in various places in Settings. 

Thanks for looking into it.

**Comment by silvestreh** [comment]
The icons are not aligned to a pixel grid, that's why they look blurry. The optimal size to avoid this blurriness is 24px, but that looks huge.

So far it seems to be something we'll have to live with. Either that or make our own icon font instead of using Google's.

**Comment by baurigae** [comment]
Is there a way to use (what seems to be) the default set, shown on the right - with your theme?

**Comment by silvestreh** [comment]
Not right now, no. Default icons are replaced. If you have a custom file icons package installed, those icons would be used instead (except for folders, those are always replaced)

I'll try to make a new font with the icons in the right size to avoid this "blurriness".

**Comment by tststs** [comment]
You may just overwrite ```-webkit-font-smoothing``` to ```none``` for the three view.
Works for me.

![bildschirmfoto 2015-10-29 um 16 31 19](https://cloud.githubusercontent.com/assets/3591665/10823135/87044ede-7e5a-11e5-8d35-e0b85d8c88f9.png)

**Comment by silvestreh** [comment]
@tststs the problem with that is that the shapes get distorted. Some borders will look thicker than they should. Check the folder:

![folder](https://cloud.githubusercontent.com/assets/1133339/10830989/8d960ba0-7e61-11e5-85a5-3874ba965d62.png)

The bottom border looks thicker than the sides. They should be the same width.

The only real solution here is having "optimized" icons for a given size. That means, if I want the icon to be 24 x 24 pixels, I should create an icon with that exact size and align all borders and shapes to a pixel grid.

**Comment by tststs** [comment]
I agree with that. This was just a quick fix i used, cause it it annoys me. Sorry for the unprofessional post here! Haven't mentioned it.

**Comment by silvestreh** [comment]
@tststs No need to apologize! :smiley: I just haven't had the time to work on those icons. It's something I want to do. Hopefully I'll work on it during the weekend.

**Comment by silvestreh** [comment]
I reverted to using the default icon set in the development version. Check the **contributing** section of the `README.md` file to test it :smile:
