### ISSUE TITLE
Roboto Mono smoothing on Linux

### ISSUE THREAD

**Issue by mslynch** [silvestreh/atom-material-ui#84]
Text doesn't seem to be antialiased on Linux when using Roboto Mono. DejaVu Sans Mono and Liberation Mono both work fine. I saw that you said it was fixed in #3, but the issue still persists for me.
I'm using Atom 1.0.7 on Ubuntu 15.04. 
![material](https://cloud.githubusercontent.com/assets/5151225/9508428/e335be62-4c1a-11e5-852c-7c540f433928.png)
Atom Dark theme with antialiasing for comparison:
![atom](https://cloud.githubusercontent.com/assets/5151225/9508431/e91e5578-4c1a-11e5-8259-1270e2b0d3f5.png)

**Comment by peduxe** [comment]
Try using ![Infinality](http://www.webupd8.org/2013/06/better-font-rendering-in-linux-with.html), set OSX rendering.

**Comment by silvestreh** [comment]
@mslynch I could try to adjust font smoothing on linux. I'll have to create a virtual machine or something. Hang in there!

**Comment by tecbeast42** [comment]
I had the same problem.

Adding to my style

```less
.editor {
  -webkit-font-smoothing: auto;
}

.tree-view {
  -webkit-font-smoothing: auto;
}
```

helped.

**Comment by silvestreh** [comment]
@tecbeast42 The `.editor` selector is deprecated. Try using `atom-text-editor` instead :smile:
