### ISSUE TITLE
Viewing file icons on tab labels

### ISSUE THREAD

**Issue by roee-indegy** [silvestreh/atom-material-ui#85]
I use the file-icons extension, and i only see the file icons in the tree view and not in the tab's label with the file's name. Is there a way to resolve this?

**Comment by diagramatics** [comment]
Hm, that doesn't sound right. Have you enabled them on the theme settings? There's an "Icons in tabs" configuration option in there.

Otherwise that sounds like packages clashing. Can you try and run `apm list --installed --bare` and giving us the list of your packages installed from it?

**Comment by roee-indegy** [comment]
I missed that setting, turned it on and it works like a charm :)
