### ISSUE TITLE
Sometimes when dragging a tab it's surrounded by rectangle

### ISSUE THREAD

**Issue by roee-indegy** [silvestreh/atom-material-ui#86]
![image](https://cloud.githubusercontent.com/assets/10956268/9634423/58cc64da-519a-11e5-8225-57c1fe372b84.png)
This happens occasionally when i drag tabs.

**Comment by silvestreh** [comment]
It's been a month and I still cannot reproduce it. I'll close the issue. Feel free to reopen it if you have concise instructions on how to reproduce the bug.
