### ISSUE TITLE
autogrow for tabs

### ISSUE THREAD

**Issue by haringsrob** [silvestreh/atom-material-ui#87]
Hi,

Can we have an option to make the tabs receive an automatic width to make the top bar always filled completely.

Thanks

**Comment by silvestreh** [comment]
You want tabs to always fill the tab-bar so that when you have one file open it would have a 100% width tab?

I'm not sure that's how tabs are supposed to work in the design spec.

**Comment by haringsrob** [comment]
Yes that is the request.

**Comment by silvestreh** [comment]
I'm sorry, but I don't believe is a good idea and it doesn't quite follow the MD spec for tabs (except for the case where you only have up to three tabs)
