### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by tomahl** [silvestreh/atom-material-ui#88]
Would be nice to have file related icons in the sidebar. Maybe a setting for static vs related?
https://github.com/equinusocio/material-theme

**Comment by silvestreh** [comment]
No, that's why we have packages like [file-icons](https://atom.io/packages/file-icons) to fill in those gaps. I don't believe it's up to the UI theme to bring that functionality, it should only replace default icons like we do now for folders, text files and images.
