### ISSUE TITLE
No indication of unsaved files in latest Atom

### ISSUE THREAD

**Issue by karai17** [silvestreh/atom-material-ui#94]
I am running Atom 1.0.13 and the normal indicators (coloured X/circle) that a file is unsaved do not seem to be displaying.

**Comment by silvestreh** [comment]
Yeah, it's there. Contrast is too low (I have to fix it… I think there was a pull request somewhere)

**Comment by silvestreh** [comment]
Yeah, looks like Atom is no longer adding the `modified` class to tabs.

**Comment by silvestreh** [comment]
I'm closing this issue as it's not related to the theme. It's an Atom bug. For now you can remove the `~/.atom/storage` file or close and reopen the file you're having problems with.

**Comment by karai17** [comment]
All right. Are you going to file this bug with Atom?


---
Landon Manning
lmanning17@gmail.com

**Comment by karai17** [comment]
Upgrading to 1.0.15 seems to have fixed this.

**Comment by silvestreh** [comment]
@karai17 It was already reported :)
