### ISSUE TITLE
Is there a way to change the size of the tabs. 

### ISSUE THREAD

**Issue by MohhamedRafi** [silvestreh/atom-material-ui#95]
When I am using atom the tabs look to big. Is there any way I can change the size of the tabs

**Comment by silvestreh** [comment]
Yep, there's a setting for that. Go to Atom's `Settings > Themes` once in there, click the cog icon next to the UI theme dropdown menu and then look for the `Tab bar size` option (it's a dropdown menu with three options: small, normal, and big)
