### ISSUE TITLE
Selected item background color

### ISSUE THREAD

**Issue by feimosi** [silvestreh/atom-material-ui#96]
This theme is almost perfect. The only thing I'd change is the background color for selected items or allow to set it manually, because the contrast is too low.
![settings](https://cloud.githubusercontent.com/assets/5721520/10041842/a8c9bd86-61e7-11e5-93b4-f3ef51f896e5.png)
Especially on the tree-view:
![tree-view](https://cloud.githubusercontent.com/assets/5721520/10041844/afaff87c-61e7-11e5-9d1c-8c7a8d80ef0d.png)

**Comment by silvestreh** [comment]
You can change the accent color from the settings. Click the cog icon next to the UI theme selector.

![](https://camo.githubusercontent.com/23b92d4bf351cd5e76cc8d76e64a296cfd85f206/687474703a2f2f692e696d6775722e636f6d2f4a42326941356d2e706e67)

In there, you'll find all the options.

**Comment by feimosi** [comment]
Thanks for a quick response. Nonetheless I still think that every possible color from the list is too bright for white-color text in the tree-view. It'd be nice to be able to choose your own RGB value without modifying style files. Btw. `md-indigo` which is not used by default worked best for me
