### ISSUE TITLE
Scrollbars barely visible in light theme

### ISSUE THREAD

**Issue by justin97530** [silvestreh/atom-material-ui#98]
When I use the Material light UI with the Material Syntax, the scrollbars are barely visible and hard to find.
![screen shot 2015-09-24 at 9 53 14 pm](https://cloud.githubusercontent.com/assets/2884155/10079308/dbe381aa-6306-11e5-95c6-c75353e34112.png)

**Comment by xiaoxiyao** [comment]
yes, I can't find the scrollbars in dark theme too!

**Comment by silvestreh** [comment]
Well, I'll increase contrast on those.
