### ISSUE TITLE
option: tab title min-width with scrolling

### ISSUE THREAD

**Issue by guymguym** [silvestreh/atom-material-ui#99]
Hey, This is a great theme.

However I usually open many tabs and then their titles all show just '...'
For users like me I think a better solution is to set a min-width to the tab titles, and do horizontal scrolling, as done by default on the 'One Dark' theme.
It will also be useful to have a configurable option on how wide to set the tab titles (maybe just 3 levels), but even one good level would work.

What do you think?

Thanks!
Guy

**Comment by silvestreh** [comment]
@guymguym I thought about it. I actually tried it for a little while today. What worries me is that in some OS, scrollbars aren't always visible (I'm looking at you, OS X) and it might not be obvious for some users… especially when switching tabs using keyboard shortcuts and not seeing where the hell the active tab is.

I like the idea of having a min-width for tabs, but the above scenario kinda worries me a bit. I'll see if there's something in Atom's API to select the newly active tab or something like that and I'll probably add the feature.

**Comment by silvestreh** [comment]
This has been implemented in 0.8.0
